import DashboardLayout from "@/components/DashboardLayout";
import { PWA_OPEN_INSTALL_EVENT } from "@/components/PwaStatus";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import { ArrowUpRight, Download, Info, ShieldCheck, Smartphone, WifiOff } from "lucide-react";

export const RASEEN_APP_VERSION = "1.0.0";
export const RASEEN_ANDROID_PACKAGE_ID = "com.nawa.erp";

export default function AboutApp() {
  const { language, direction } = useLanguage();
  const copy = language === "ar" ? { eyebrow: "منصة رصين", title: "حول التطبيق", description: "رصين لإدارة الأعمال منصة تشغيل موحدة للمؤسسات متعددة الفروع، مع صلاحيات وعزل بيانات على مستوى المؤسسة.", version: "إصدار المنصة", pwa: "تطبيق الويب", android: "تطبيق Android", offline: "الوصول دون اتصال", install: "تثبيت التطبيق", status: "جاهز للتثبيت", secure: "العزل المؤسسي والحسابات الخادمية مفعلة", detail: "تفاصيل تقنية", packageId: "معرف حزمة Android", worker: "تحديثات PWA", workerValue: "تصل تلقائياً عند توفر إصدار جديد", offlineValue: "واجهة التطبيق فقط؛ لا تُخزن بيانات المؤسسة أو API", note: "تتطلب الكاميرا والطباعة إذناً صريحاً من المستخدم عند استخدامها." } : language === "fr" ? { eyebrow: "Plateforme RASEEN", title: "À propos", description: "RASEEN ERP est une plateforme opérationnelle unifiée pour les organisations multi-sites, avec des autorisations et une isolation des données par organisation.", version: "Version de la plateforme", pwa: "Application web", android: "Application Android", offline: "Accès hors connexion", install: "Installer l’application", status: "Prête à installer", secure: "Isolation de l’organisation et calculs serveur actifs", detail: "Détails techniques", packageId: "Identifiant du package Android", worker: "Mises à jour PWA", workerValue: "Appliquées lorsqu’une nouvelle version est disponible", offlineValue: "Shell de l’application uniquement; aucune donnée d’organisation ni API en cache", note: "La caméra et l’impression demandent une autorisation explicite au moment de l’utilisation." } : { eyebrow: "RASEEN platform", title: "About the app", description: "RASEEN ERP is a unified operations platform for multi-site organizations, with role controls and organization-level data isolation.", version: "Platform version", pwa: "Web app", android: "Android app", offline: "Offline access", install: "Install app", status: "Ready to install", secure: "Tenant isolation and server-side calculations are active", detail: "Technical details", packageId: "Android package ID", worker: "PWA updates", workerValue: "Applied when a new version is available", offlineValue: "Application shell only; organization data and API are never cached", note: "Camera and printing request explicit user permission when used." };

  return <DashboardLayout><main dir={direction} className="mx-auto w-full max-w-5xl space-y-6"><section className="surface relative overflow-hidden rounded-3xl border p-7 md:p-10"><div className="absolute -left-16 -top-16 h-56 w-56 rounded-full bg-primary/10 blur-3xl" /><div className="relative"><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><Info className="h-6 w-6" /></div><div><p className="text-sm text-primary">{copy.eyebrow}</p><h1 className="mt-1 text-3xl font-bold text-white">{copy.title}</h1><p className="mt-3 max-w-3xl text-sm leading-8 text-muted-foreground">{copy.description}</p></div></div><div className="mt-7 flex flex-wrap gap-3"><Badge className="border border-primary/20 bg-primary/10 px-3 py-2 text-primary"><ShieldCheck className="me-2 h-4 w-4" />{copy.secure}</Badge><Badge className="border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-emerald-300"><Download className="me-2 h-4 w-4" />{copy.status}</Badge></div></div></section><section className="grid gap-4 md:grid-cols-3"><div className="surface rounded-3xl border p-6"><p className="text-sm text-muted-foreground">{copy.version}</p><p className="mt-3 text-3xl font-bold text-white">{RASEEN_APP_VERSION}</p><p className="mt-2 text-xs text-primary">RASEEN ERP</p></div><div className="surface rounded-3xl border p-6"><Smartphone className="h-5 w-5 text-primary" /><p className="mt-4 text-sm font-semibold text-white">{copy.android}</p><p className="mt-2 text-xs text-muted-foreground">{copy.packageId}: <span className="latin">{RASEEN_ANDROID_PACKAGE_ID}</span></p></div><div className="surface rounded-3xl border p-6"><WifiOff className="h-5 w-5 text-primary" /><p className="mt-4 text-sm font-semibold text-white">{copy.offline}</p><p className="mt-2 text-xs leading-6 text-muted-foreground">{copy.offlineValue}</p></div></section><section className="surface rounded-3xl border p-7"><p className="text-sm text-primary">{copy.detail}</p><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="font-semibold text-white">{copy.pwa}</p><p className="mt-2 text-sm leading-7 text-muted-foreground">{copy.worker}: {copy.workerValue}</p></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="font-semibold text-white">{copy.install}</p><p className="mt-2 text-sm leading-7 text-muted-foreground">{copy.note}</p><Button variant="outline" className="mt-4 gap-2" onClick={() => window.dispatchEvent(new Event(PWA_OPEN_INSTALL_EVENT))}>{copy.install}<ArrowUpRight className="h-4 w-4" /></Button></div></div></section></main></DashboardLayout>;
}
