import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { Check, ClipboardList, MailCheck, ShieldCheck, Store, X } from "lucide-react";
import React, { useMemo, useState } from "react";
import { toast } from "sonner";

const text = {
  ar: { title: "إدارة Nawa Retail", subtitle: "إدارة علاقات التجار وسياسات الظهور والطلبات ضمن المؤسسة", approve: "اعتماد وتحويل", reject: "رفض", empty: "لا توجد طلبات Retail للمراجعة.", items: "البنود", error: "تعذر إتمام العملية.", converted: "تم اعتماد الطلب وتحويله إلى Sales Order.", rejected: "تم رفض الطلب.", prompt: "اكتب سبب الرفض", access: "علاقات التجار", suspended: "تعليق", revoked: "إلغاء الوصول", active: "تفعيل", resend: "إعادة إرسال", policy: "سياسة التتبع", priceList: "قائمة الأسعار", availability: "إتاحة المخزون", none: "لا توجد علاقات تجار مهيأة.", orders: "طلبات Retail", all: "الكل", invited: "مدعو", suspendedLabel: "معلق", revokedLabel: "ملغى", activeLabel: "نشط", retailer: "التاجر", users: "مستخدم Retail", visibility: "سياسات الظهور", role: "الدور" },
  fr: { title: "Gestion Nawa Retail", subtitle: "Gérez les relations détaillants, les politiques de visibilité et les commandes", approve: "Approuver et convertir", reject: "Rejeter", empty: "Aucune commande Retail à examiner.", items: "Articles", error: "L’opération a échoué.", converted: "Commande approuvée et convertie en Sales Order.", rejected: "Commande rejetée.", prompt: "Saisissez le motif du refus", access: "Relations détaillants", suspended: "Suspendre", revoked: "Révoquer", active: "Activer", resend: "Renvoyer", policy: "Suivi", priceList: "Liste de prix", availability: "Disponibilité", none: "Aucune relation détaillant configurée.", orders: "Commandes Retail", all: "Toutes", invited: "Invité", suspendedLabel: "Suspendu", revokedLabel: "Révoqué", activeLabel: "Actif", retailer: "Détaillant", users: "Utilisateur Retail", visibility: "Politiques de visibilité", role: "Rôle" },
  en: { title: "Nawa Retail Management", subtitle: "Manage retailer relationships, visibility policies, and retail orders", approve: "Approve & convert", reject: "Reject", empty: "No retail orders to review.", items: "Items", error: "The operation could not be completed.", converted: "Order approved and converted to a Sales Order.", rejected: "Order rejected.", prompt: "Enter rejection reason", access: "Retailer relationships", suspended: "Suspend", revoked: "Revoke", active: "Activate", resend: "Resend", policy: "Tracking policy", priceList: "Price list", availability: "Availability", none: "No retailer relationships configured.", orders: "Retail orders", all: "All", invited: "Invited", suspendedLabel: "Suspended", revokedLabel: "Revoked", activeLabel: "Active", retailer: "Retailer", users: "Retail user", visibility: "Visibility policies", role: "Role" },
} as const;

export default function B2BOrders() {
  const { language, direction, formatNumber } = useLanguage();
  const copy = text[language];
  const utils = trpc.useUtils();
  const [busyId, setBusyId] = useState<number | null>(null);
  const [filter, setFilter] = useState<"all" | "invited" | "active" | "suspended" | "revoked">("all");
  const orders = trpc.erp.b2b.management.orders.useQuery();
  const accesses = trpc.erp.b2b.management.accesses.useQuery();
  const review = trpc.erp.b2b.review.useMutation({ onSuccess: () => utils.erp.b2b.management.orders.invalidate(), onError: () => toast.error(copy.error), onSettled: () => setBusyId(null) });
  const accessStatus = trpc.erp.b2b.management.accessStatus.useMutation({ onSuccess: () => utils.erp.b2b.management.accesses.invalidate(), onError: () => toast.error(copy.error) });
  const resendInvite = trpc.erp.b2b.management.resendInvite.useMutation({ onSuccess: () => toast.success(copy.resend), onError: () => toast.error(copy.error) });
  const visibleAccesses = useMemo(() => filter === "all" ? accesses.data ?? [] : (accesses.data ?? []).filter((access: any) => access.status === filter), [accesses.data, filter]);
  const statusLabel = (status: string) => status === "invited" ? copy.invited : status === "active" ? copy.activeLabel : status === "suspended" ? copy.suspendedLabel : copy.revokedLabel;
  const approve = (orderId: number) => { setBusyId(orderId); review.mutate({ orderId, action: "approve" }, { onSuccess: () => toast.success(copy.converted) }); };
  const reject = (orderId: number) => { const reason = window.prompt(copy.prompt); if (!reason?.trim()) return; setBusyId(orderId); review.mutate({ orderId, action: "reject", reason }, { onSuccess: () => toast.success(copy.rejected) }); };
  const filters = [{ id: "all", label: copy.all }, { id: "invited", label: copy.invited }, { id: "active", label: copy.activeLabel }, { id: "suspended", label: copy.suspendedLabel }, { id: "revoked", label: copy.revokedLabel }] as const;

  return <main dir={direction} className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-6xl space-y-5 px-4 py-6 sm:px-6"><header className="rounded-3xl border border-primary/20 bg-gradient-to-br from-primary/15 via-card to-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Nawa Retail</p><h1 className="mt-1 text-2xl font-bold">{copy.title}</h1><p className="mt-1 text-sm text-muted-foreground">{copy.subtitle}</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/15 text-primary"><Store className="h-6 w-6" /></div></div></header>
    <section className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{copy.access}</p><p className="mt-1 text-2xl font-bold">{accesses.data?.length ?? "—"}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{copy.orders}</p><p className="mt-1 text-2xl font-bold">{orders.data?.length ?? "—"}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{copy.activeLabel}</p><p className="mt-1 text-2xl font-bold">{accesses.data?.filter((access: any) => access.status === "active").length ?? "—"}</p></CardContent></Card></section>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-5 w-5 text-primary" />{copy.access}</CardTitle><CardDescription>{copy.visibility} · {copy.priceList} · {copy.users}</CardDescription></CardHeader><CardContent><div className="mb-4 flex flex-wrap gap-2">{filters.map(item => <Button key={item.id} variant={filter === item.id ? "default" : "outline"} size="sm" onClick={() => setFilter(item.id)}>{item.label}</Button>)}</div><div className="space-y-2">{visibleAccesses.map((access: any) => <article key={access.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border p-3 text-sm"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong>{access.customerName}</strong><span className="rounded-full bg-muted px-2 py-0.5 text-xs">{statusLabel(access.status)}</span></div><p className="mt-1 text-xs text-muted-foreground">{copy.users}: #{access.userId} · {copy.role}: {access.retailerRole} · {copy.priceList}: {access.priceListName ?? "—"} · {copy.policy}: {access.deliveryTrackingPolicy} · {copy.availability}: {access.availabilityDisclosure}</p></div><div className="flex flex-wrap gap-2">{access.status === "invited" ? <Button size="sm" variant="outline" disabled={resendInvite.isPending} onClick={() => resendInvite.mutate({ accessId: access.id })}><MailCheck className="me-1 h-4 w-4" />{copy.resend}</Button> : null}{access.status !== "active" && access.status !== "revoked" ? <Button size="sm" variant="outline" onClick={() => accessStatus.mutate({ accessId: access.id, status: "active" })}><Check className="me-1 h-4 w-4" />{copy.active}</Button> : null}{access.status === "active" ? <Button size="sm" variant="outline" onClick={() => accessStatus.mutate({ accessId: access.id, status: "suspended" })}>{copy.suspended}</Button> : null}{access.status !== "revoked" ? <Button size="sm" variant="outline" onClick={() => accessStatus.mutate({ accessId: access.id, status: "revoked" })}>{copy.revoked}</Button> : null}</div></article>)}{!accesses.isLoading && !visibleAccesses.length ? <p className="py-4 text-sm text-muted-foreground">{copy.none}</p> : null}</div></CardContent></Card>
    <section><div className="mb-3 flex items-center gap-2"><ClipboardList className="h-5 w-5 text-primary" /><h2 className="font-bold">{copy.orders}</h2></div>{orders.isLoading ? <Card><CardContent className="p-6 text-sm text-muted-foreground">…</CardContent></Card> : !orders.data?.length ? <Card><CardContent className="p-6 text-sm text-muted-foreground">{copy.empty}</CardContent></Card> : <div className="space-y-4">{orders.data.map((order: any) => <Card key={order.id}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">{order.orderNumber}</CardTitle><CardDescription>{order.retailerName} · {order.status} · {order.accessStatus}</CardDescription></div><strong>{formatNumber(Number(order.totalAmount))} {order.currencyCode}</strong></div></CardHeader><CardContent><p className="mb-2 text-sm font-medium">{copy.items}</p><div className="space-y-2">{order.items.map((item: any) => <div className="flex justify-between rounded-lg bg-muted/50 p-2 text-sm" key={item.id}><span>{item.productId} · {item.unit}</span><span>{formatNumber(Number(item.quantity))} × {formatNumber(Number(item.unitPrice))}</span></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><Button disabled={busyId === order.id || order.status === "cancelled" || order.status === "confirmed"} onClick={() => approve(order.id)}><Check className="me-1 h-4 w-4" />{copy.approve}</Button><Button variant="outline" disabled={busyId === order.id || order.status === "cancelled" || order.status === "confirmed"} onClick={() => reject(order.id)}><X className="me-1 h-4 w-4" />{copy.reject}</Button></div></CardContent></Card>)}</div>}</section>
  </div></main>;
}
