import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import { useTheme } from "@/contexts/ThemeContext";
import { trpc } from "@/lib/trpc";
import { Check, Palette, Sparkles } from "lucide-react";
import { toast } from "sonner";

export const raseenPalettes = [
  { id: "gold", color: "#D7A942", ring: "#F3D891", ar: "ذهب رصين", fr: "Or RASEEN", en: "RASEEN Gold", note: { ar: "الهوية الأساسية للمنصة", fr: "Identité principale", en: "Primary platform identity" } },
  { id: "blue", color: "#5C8FEA", ring: "#B7CCFF", ar: "كحلي القرار", fr: "Bleu décision", en: "Decision Navy", note: { ar: "للتحليل والإدارة", fr: "Pour l’analyse et l’administration", en: "For analysis and administration" } },
  { id: "emerald", color: "#3ABF8B", ring: "#9CE4C7", ar: "أخضر النماء", fr: "Vert croissance", en: "Growth Emerald", note: { ar: "للتشغيل والنجاح", fr: "Pour l’exécution et la réussite", en: "For operations and success" } },
  { id: "violet", color: "#9B7BEB", ring: "#D2C4FF", ar: "بنفسج التخطيط", fr: "Violet planification", en: "Planning Violet", note: { ar: "للتخطيط والإنتاج", fr: "Pour la planification et la production", en: "For planning and manufacturing" } },
] as const;

export default function BrandAppearance() {
  const { language, direction } = useLanguage();
  const { preferences, updatePreferences } = useTheme();
  const saveUser = trpc.erp.preferences.saveUser.useMutation({ onSuccess: () => toast.success(language === "ar" ? "تم حفظ لون الهوية" : language === "fr" ? "Couleur de marque enregistrée" : "Brand color saved"), onError: () => toast.error(language === "ar" ? "تعذر حفظ اللون" : language === "fr" ? "Impossible d’enregistrer la couleur" : "Could not save the color") });
  const copy = language === "ar" ? { eyebrow: "هوية رصين", title: "ألوان الواجهة", description: "اختر لون التمييز المناسب لدورك مع بقاء هوية رصين وتباين الوصول ثابتين.", current: "اللون النشط", preview: "معاينة تشغيلية", action: "إجراء أساسي", status: "حالة نشطة", safe: "يحفظ الاختيار ضمن تفضيلاتك الشخصية ولا يغير بيانات المؤسسة أو ألوان المستندات الرسمية." } : language === "fr" ? { eyebrow: "Identité RASEEN", title: "Couleurs de l’interface", description: "Choisissez une couleur d’accent adaptée à votre rôle tout en conservant l’identité et le contraste RASEEN.", current: "Couleur active", preview: "Aperçu opérationnel", action: "Action principale", status: "État actif", safe: "Le choix est enregistré dans vos préférences personnelles et ne modifie ni les données de l’organisation ni les documents officiels." } : { eyebrow: "RASEEN identity", title: "Interface colors", description: "Choose an accent suited to your role while keeping the RASEEN identity and accessible contrast intact.", current: "Active color", preview: "Operational preview", action: "Primary action", status: "Active status", safe: "This is saved in your personal preferences and does not change organization data or official document colors." };
  const selectPalette = (accentColor: typeof preferences.accentColor) => { updatePreferences({ accentColor }); saveUser.mutate({ accentColor }); };

  return <DashboardLayout><main dir={direction} className="mx-auto w-full max-w-6xl space-y-6"><section className="surface relative overflow-hidden rounded-3xl border p-7 md:p-9"><div className="absolute -left-16 -top-16 h-52 w-52 rounded-full bg-primary/10 blur-3xl" /><div className="relative"><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><Palette className="h-6 w-6" /></div><div><p className="text-sm text-primary">{copy.eyebrow}</p><h1 className="mt-1 text-3xl font-bold text-white">{copy.title}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">{copy.description}</p></div></div><p className="mt-6 rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm leading-7 text-muted-foreground">{copy.safe}</p></div></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{raseenPalettes.map(palette => { const selected = preferences.accentColor === palette.id; return <button key={palette.id} aria-pressed={selected} onClick={() => selectPalette(palette.id)} className={`relative overflow-hidden rounded-3xl border p-5 text-start transition-all ${selected ? "border-primary bg-primary/10 shadow-lg shadow-primary/10" : "border-white/10 bg-white/[.025] hover:border-primary/40 hover:bg-white/[.05]"}`}><div className="absolute inset-x-0 top-0 h-1.5" style={{ background: palette.color }} /><div className="mt-2 flex items-start justify-between gap-4"><span className="grid h-10 w-10 place-items-center rounded-2xl" style={{ background: `${palette.color}22`, color: palette.color, boxShadow: `inset 0 0 0 1px ${palette.ring}55` }}><Sparkles className="h-5 w-5" /></span>{selected ? <Badge className="gap-1 bg-primary text-primary-foreground"><Check className="h-3.5 w-3.5" />{copy.current}</Badge> : null}</div><h2 className="mt-5 text-lg font-bold text-white">{palette[language]}</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">{palette.note[language]}</p></button>; })}</section><section className="surface rounded-3xl border p-6"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-sm text-primary">{copy.preview}</p><h2 className="mt-1 text-xl font-bold text-white">RASEEN ERP</h2></div><div className="flex flex-wrap items-center gap-3"><Button>{copy.action}</Button><Badge className="border border-primary/20 bg-primary/10 text-primary"><Check className="me-1 h-3.5 w-3.5" />{copy.status}</Badge></div></div></section></main></DashboardLayout>;
}
