import { useAuth } from "@/_core/hooks/useAuth";
import { DriverDailyOperations } from "@/components/DriverDailyOperations";
import { DriverDeliveryProof } from "@/components/DriverDeliveryProof";
import { MapView } from "@/components/Map";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Skeleton } from "@/components/ui/skeleton";
import { useLanguage } from "@/contexts/LanguageContext";
import { getQueuedDriverLocations, queueDriverLocation, removeQueuedDriverLocations } from "@/lib/driverLocationQueue";
import { trpc } from "@/lib/trpc";
import { CircleAlert, Crosshair, LocateFixed, MapPinned, Navigation, Pause, Play, RefreshCcw, Route, ShieldCheck, Signal, Truck, WifiOff } from "lucide-react";
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const copy = {
  ar: { eyebrow: "واجهة السائق", title: "جولتي الميدانية", subtitle: "المسار والمحطات ومشاركة الموقع تظهر فقط للجولات المسندة إليك.", back: "مركز العمليات", tracking: "تتبع الموقع", trackingHint: "يُستخدم الموقع لتسجيل تقدم الجولة، ويمكن إيقافه في أي وقت.", consent: "أوافق على مشاركة موقعي أثناء الجولة النشطة.", startTracking: "بدء مشاركة الموقع", stopTracking: "إيقاف مشاركة الموقع", trackingOn: "الموقع قيد المشاركة", trackingOff: "الموقع متوقف", gpsUnavailable: "لا يدعم الجهاز تحديد الموقع أو تم رفض الإذن.", gpsError: "تعذر تحديث الموقع حالياً.", activeRoute: "الجولة الحالية", noRoute: "لا توجد جولة مسندة ونشطة حالياً.", noRouteHint: "تظهر الجولات عندما يربطها مدير التوزيع بعضويتك.", stops: "محطات التسليم", stop: "المحطة", navigate: "فتح الملاحة", arrived: "تأكيد الوصول", arrivedDone: "تم تسجيل الوصول للمحطة.", startDelivery: "بدء التنفيذ", returning: "بدء العودة", vehicle: "المركبة", routeDate: "التاريخ", map: "خريطة المسار", mapHint: "تظهر المحطات ذات الإحداثيات المسجلة فقط.", privacy: "خصوصية الموقع", privacyHint: "لا يبدأ التتبع ولا يُرسل أي موقع قبل موافقتك الصريحة.", routeUpdateFailed: "تعذر تحديث حالة الجولة.", positionUnknown: "الموقع الحالي غير متاح بعد.", destinationMissing: "لا تتوفر إحداثيات لهذه المحطة.", arrivalState: "تم الوصول", pendingState: "بانتظار الوصول", sync: "مزامنة الطابور", queued: "نقطة موقع محفوظة محلياً", queuedPlural: "نقاط موقع محفوظة محلياً", offline: "دون اتصال — ستُزامن النقاط عند عودة الإنترنت.", online: "متصل", sort: "ترتيب الجولات", priority: "الأولوية", distance: "المسافة", sequence: "التسلسل", selected: "الجولة المختارة", proof: "إثبات التسليم", proofDone: "إثبات مسجل", proofHint: "التقط صورة التسليم واطلب توقيع المستلم قبل الحفظ.", signer: "اسم المستلم", signerPlaceholder: "اكتب اسم المستلم", photo: "صورة التسليم", signature: "توقيع المستلم", clear: "مسح", submit: "حفظ الإثبات", submitted: "تم حفظ إثبات التسليم.", photoRequired: "يلزم التقاط صورة بحجم لا يتجاوز 5 ميغابايت.", signatureRequired: "يلزم توقيع المستلم داخل المساحة.", proofFailed: "تعذر حفظ إثبات التسليم." },
  fr: { eyebrow: "Espace conducteur", title: "Ma tournée terrain", subtitle: "L’itinéraire, les arrêts et la localisation ne concernent que vos tournées attribuées.", back: "Centre d’opérations", tracking: "Suivi de position", trackingHint: "La position sert au suivi de la tournée et peut être arrêtée à tout moment.", consent: "J’accepte le partage de ma position pendant la tournée active.", startTracking: "Démarrer le partage", stopTracking: "Arrêter le partage", trackingOn: "Position partagée", trackingOff: "Position arrêtée", gpsUnavailable: "La géolocalisation est indisponible ou refusée.", gpsError: "Impossible d’actualiser la position.", activeRoute: "Tournée actuelle", noRoute: "Aucune tournée active ne vous est attribuée.", noRouteHint: "Les tournées apparaissent après attribution par le responsable.", stops: "Arrêts de livraison", stop: "Arrêt", navigate: "Ouvrir la navigation", arrived: "Confirmer l’arrivée", arrivedDone: "L’arrivée a été enregistrée.", startDelivery: "Démarrer l’exécution", returning: "Commencer le retour", vehicle: "Véhicule", routeDate: "Date", map: "Carte de l’itinéraire", mapHint: "Seuls les arrêts géolocalisés s’affichent.", privacy: "Confidentialité", privacyHint: "Aucun suivi ni envoi avant votre accord explicite.", routeUpdateFailed: "Impossible d’actualiser la tournée.", positionUnknown: "La position actuelle est indisponible.", destinationMissing: "Les coordonnées sont indisponibles.", arrivalState: "Arrivé", pendingState: "En attente", sync: "Synchroniser la file", queued: "point enregistré localement", queuedPlural: "points enregistrés localement", offline: "Hors ligne — les points seront synchronisés au retour du réseau.", online: "En ligne", sort: "Trier les tournées", priority: "Priorité", distance: "Distance", sequence: "Séquence", selected: "Tournée sélectionnée", proof: "Preuve de livraison", proofDone: "Preuve enregistrée", proofHint: "Prenez une photo et demandez la signature du destinataire.", signer: "Nom du destinataire", signerPlaceholder: "Saisissez le nom", photo: "Photo de livraison", signature: "Signature du destinataire", clear: "Effacer", submit: "Enregistrer la preuve", submitted: "La preuve a été enregistrée.", photoRequired: "Une photo de 5 Mo maximum est requise.", signatureRequired: "La signature est requise.", proofFailed: "Impossible d’enregistrer la preuve." },
  en: { eyebrow: "Driver workspace", title: "My field route", subtitle: "Route, stops, and location are shown only for routes assigned to you.", back: "Operations center", tracking: "Location tracking", trackingHint: "Location is used to progress the route and can be stopped at any time.", consent: "I agree to share my location during the active route.", startTracking: "Start sharing location", stopTracking: "Stop sharing location", trackingOn: "Location is shared", trackingOff: "Location is stopped", gpsUnavailable: "Geolocation is unavailable or permission was denied.", gpsError: "Location could not be updated.", activeRoute: "Current route", noRoute: "No active route is assigned to you.", noRouteHint: "Routes appear after a distribution manager assigns them to your membership.", stops: "Delivery stops", stop: "Stop", navigate: "Open navigation", arrived: "Confirm arrival", arrivedDone: "Arrival has been recorded.", startDelivery: "Start execution", returning: "Start return", vehicle: "Vehicle", routeDate: "Date", map: "Route map", mapHint: "Only stops with saved coordinates are shown.", privacy: "Location privacy", privacyHint: "No tracking or location is sent before your explicit consent.", routeUpdateFailed: "Route status could not be updated.", positionUnknown: "Current location is not available yet.", destinationMissing: "Coordinates are not available for this stop.", arrivalState: "Arrived", pendingState: "Awaiting arrival", sync: "Sync queue", queued: "location point stored locally", queuedPlural: "location points stored locally", offline: "Offline — points will sync when the network returns.", online: "Online", sort: "Sort routes", priority: "Priority", distance: "Distance", sequence: "Sequence", selected: "Selected route", proof: "Proof of delivery", proofDone: "Proof recorded", proofHint: "Capture delivery photo and recipient signature before saving.", signer: "Recipient name", signerPlaceholder: "Enter recipient name", photo: "Delivery photo", signature: "Recipient signature", clear: "Clear", submit: "Save proof", submitted: "Proof of delivery saved.", photoRequired: "A photo up to 5 MB is required.", signatureRequired: "Recipient signature is required.", proofFailed: "Proof of delivery could not be saved." },
} as const;
const operationCopy = {
  ar: { delivery: "تسليم", partial: "جزئي", failed: "تعذر التسليم", collect: "تحصيل", return: "مرتجع", expense: "مصروف", closing: "إرسال إغلاق الجولة", quantity: "الكمية", amount: "المبلغ", reason: "السبب أو الملاحظة", save: "حفظ", actualCash: "النقد المسلّم", currency: "العملة", receipt: "الإيصال", inventory: "مخزون المركبة", noInventory: "لا توجد دفعات متاحة في مخزون المركبة لهذه الجولة.", operationDone: "تم حفظ العملية الميدانية.", operationFailed: "تعذر حفظ العملية الميدانية.", paymentMethod: "طريقة الدفع", condition: "حالة المرتجع", cash: "نقدي", card: "بطاقة", transfer: "تحويل", resalable: "صالح لإعادة البيع", damaged: "تالف", quarantine: "عزل" },
  fr: { delivery: "Livraison", partial: "Partielle", failed: "Échec", collect: "Encaisser", return: "Retour", expense: "Dépense", closing: "Soumettre la clôture", quantity: "Quantité", amount: "Montant", reason: "Motif ou note", save: "Enregistrer", actualCash: "Espèces remises", currency: "Devise", receipt: "Reçu", inventory: "Stock véhicule", noInventory: "Aucun lot disponible dans le véhicule pour cette tournée.", operationDone: "L’opération terrain est enregistrée.", operationFailed: "Impossible d’enregistrer l’opération.", paymentMethod: "Moyen de paiement", condition: "État du retour", cash: "Espèces", card: "Carte", transfer: "Virement", resalable: "Revendable", damaged: "Endommagé", quarantine: "Quarantaine" },
  en: { delivery: "Deliver", partial: "Partial", failed: "Cannot deliver", collect: "Collect", return: "Return", expense: "Expense", closing: "Submit route closing", quantity: "Quantity", amount: "Amount", reason: "Reason or note", save: "Save", actualCash: "Cash handed in", currency: "Currency", receipt: "Receipt", inventory: "Vehicle inventory", noInventory: "No batches are available in the vehicle for this route.", operationDone: "Field operation saved.", operationFailed: "Field operation could not be saved.", paymentMethod: "Payment method", condition: "Return condition", cash: "Cash", card: "Card", transfer: "Transfer", resalable: "Resalable", damaged: "Damaged", quarantine: "Quarantine" },
} as const;

type Coordinates = { latitude: number; longitude: number; accuracy?: number };
type SortMode = "priority" | "distance" | "sequence";
const priorityScore: Record<string, number> = { critical: 4, high: 3, normal: 2, low: 1 };
const asNumber = (value: unknown) => value === null || value === undefined ? null : Number(value);
const radians = (degrees: number) => degrees * Math.PI / 180;
const distanceMeters = (from: Coordinates, lat: number, lng: number) => { const a = Math.sin(radians(lat - from.latitude) / 2) ** 2 + Math.cos(radians(from.latitude)) * Math.cos(radians(lat)) * Math.sin(radians(lng - from.longitude) / 2) ** 2; return 2 * 6371000 * Math.asin(Math.sqrt(a)); };

function DriverRouteMap({ stops, current }: { stops: Array<{ id: number; sequence: number; customerName: string; customerLatitude: unknown; customerLongitude: unknown }>; current: Coordinates | null }) {
  const points = useMemo(() => stops.map(stop => ({ ...stop, lat: asNumber(stop.customerLatitude), lng: asNumber(stop.customerLongitude) })).filter((stop): stop is typeof stop & { lat: number; lng: number } => Number.isFinite(stop.lat) && Number.isFinite(stop.lng)), [stops]);
  const initial = current ? { lat: current.latitude, lng: current.longitude } : points[0] ? { lat: points[0].lat, lng: points[0].lng } : { lat: 36.7538, lng: 3.0588 };
  return <MapView initialCenter={initial} initialZoom={points.length ? 12 : 6} className="h-[300px] overflow-hidden rounded-2xl" onMapReady={map => { const bounds = new window.google.maps.LatLngBounds(); if (current) { new window.google.maps.marker.AdvancedMarkerElement({ map, position: { lat: current.latitude, lng: current.longitude } }); bounds.extend({ lat: current.latitude, lng: current.longitude }); } points.forEach(point => { new window.google.maps.marker.AdvancedMarkerElement({ map, position: { lat: point.lat, lng: point.lng }, title: `${point.sequence}. ${point.customerName}` }); bounds.extend({ lat: point.lat, lng: point.lng }); }); if (points.length > 1) new window.google.maps.Polyline({ map, path: points.map(point => ({ lat: point.lat, lng: point.lng })), strokeColor: "#d9b46b", strokeOpacity: .9, strokeWeight: 4 }); if (!bounds.isEmpty()) map.fitBounds(bounds, 48); }} />;
}

export default function Driver() {
  const { language, direction, formatDate } = useLanguage(); const text = copy[language]; const [, setLocation] = useLocation(); const { user } = useAuth();
  const routesQuery = trpc.erp.distribution.driver.myRoutes.useQuery();
  const transition = trpc.erp.distribution.driver.transition.useMutation({ onSuccess: () => void routesQuery.refetch(), onError: () => toast.error(text.routeUpdateFailed) });
  const reportLocation = trpc.erp.distribution.tracking.location.useMutation();
  const geofence = trpc.erp.distribution.tracking.geofence.useMutation({ onSuccess: () => { void routesQuery.refetch(); toast.success(text.arrivedDone); }, onError: () => toast.error(text.gpsError) });
  const [consent, setConsent] = useState(false); const [tracking, setTracking] = useState(false); const [position, setPosition] = useState<Coordinates | null>(null); const [sortMode, setSortMode] = useState<SortMode>("priority"); const [selectedRouteId, setSelectedRouteId] = useState<number | null>(null); const [online, setOnline] = useState(() => typeof navigator === "undefined" ? true : navigator.onLine); const [queuedCount, setQueuedCount] = useState(0); const watchId = useRef<number | null>(null);
  const rankedRoutes = useMemo(() => (routesQuery.data ?? []).map(route => ({ route, priority: Math.max(0, ...route.stops.map(stop => priorityScore[String(stop.visitPriority)] ?? 0)), distance: position ? Math.min(...route.stops.filter(stop => !["delivered", "partial"].includes(stop.deliveryStatus)).map(stop => { const lat = asNumber(stop.customerLatitude); const lng = asNumber(stop.customerLongitude); return lat === null || lng === null ? Number.MAX_SAFE_INTEGER : distanceMeters(position, lat, lng); }), Number.MAX_SAFE_INTEGER) : Number.MAX_SAFE_INTEGER })).sort((a, b) => sortMode === "priority" ? b.priority - a.priority || a.route.id - b.route.id : sortMode === "distance" ? a.distance - b.distance || b.priority - a.priority : a.route.id - b.route.id), [routesQuery.data, sortMode, position]);
  useEffect(() => { if (!rankedRoutes.length) { setSelectedRouteId(null); return; } if (!rankedRoutes.some(item => item.route.id === selectedRouteId)) setSelectedRouteId(rankedRoutes[0].route.id); }, [rankedRoutes, selectedRouteId]);
  const route = rankedRoutes.find(item => item.route.id === selectedRouteId)?.route ?? rankedRoutes[0]?.route;
  const inventoryInput = useMemo(() => ({ routeId: route?.id ?? 0 }), [route?.id]);
  const inventory = trpc.erp.distribution.driver.inventory.useQuery(inventoryInput, { enabled: Boolean(route?.id) });
  const flushQueue = useCallback(async () => { if (!route || !navigator.onLine) return; const pending = getQueuedDriverLocations(route.id); const accepted: string[] = []; for (const point of pending) { try { await reportLocation.mutateAsync({ vehicleId: point.vehicleId, routeId: point.routeId, latitude: point.latitude, longitude: point.longitude, accuracy: point.accuracy, recordedAt: new Date(point.recordedAt), source: "driver_app" }); accepted.push(point.id); } catch { break; } } setQueuedCount(removeQueuedDriverLocations(route.id, accepted)); }, [route, reportLocation]);
  useEffect(() => { if (!route) return; setQueuedCount(getQueuedDriverLocations(route.id).length); const onOnline = () => { setOnline(true); void flushQueue(); }; const onOffline = () => setOnline(false); window.addEventListener("online", onOnline); window.addEventListener("offline", onOffline); return () => { window.removeEventListener("online", onOnline); window.removeEventListener("offline", onOffline); }; }, [route?.id, flushQueue]);
  const routeRef = useRef(route); useEffect(() => { routeRef.current = route; }, [route]);
  const stopTracking = () => { if (watchId.current !== null) navigator.geolocation?.clearWatch(watchId.current); watchId.current = null; setTracking(false); }; useEffect(() => () => stopTracking(), []);
  const persistLocation = async (point: Coordinates, currentRoute: NonNullable<typeof route>) => { if (!navigator.onLine) { setQueuedCount(queueDriverLocation({ routeId: currentRoute.id, vehicleId: currentRoute.vehicleId!, ...point, recordedAt: new Date().toISOString() })); return; } try { await reportLocation.mutateAsync({ vehicleId: currentRoute.vehicleId!, routeId: currentRoute.id, latitude: point.latitude, longitude: point.longitude, accuracy: point.accuracy, recordedAt: new Date(), source: "driver_app" }); } catch { setQueuedCount(queueDriverLocation({ routeId: currentRoute.id, vehicleId: currentRoute.vehicleId!, ...point, recordedAt: new Date().toISOString() })); } };
  const startTracking = () => { if (!consent || !route?.vehicleId || !navigator.geolocation) { toast.error(text.gpsUnavailable); return; } watchId.current = navigator.geolocation.watchPosition(next => { const currentRoute = routeRef.current; if (!currentRoute?.vehicleId) return; const point = { latitude: next.coords.latitude, longitude: next.coords.longitude, accuracy: next.coords.accuracy }; setPosition(point); void persistLocation(point, currentRoute); }, () => { stopTracking(); toast.error(text.gpsUnavailable); }, { enableHighAccuracy: true, maximumAge: 15000, timeout: 20000 }); setTracking(true); };
  const markArrival = (stop: NonNullable<typeof route>["stops"][number]) => { if (!route?.vehicleId || !position) { toast.error(text.positionUnknown); return; } const latitude = asNumber(stop.customerLatitude); const longitude = asNumber(stop.customerLongitude); if (latitude === null || longitude === null) { toast.error(text.destinationMissing); return; } geofence.mutate({ routeId: route.id, stopId: stop.id, vehicleId: route.vehicleId, eventType: "arrival", distanceMeters: distanceMeters(position, latitude, longitude), recordedAt: new Date() }); };
  return <main dir={direction} className="min-h-screen w-full max-w-full overflow-x-hidden bg-background text-foreground"><div className="mx-auto w-full max-w-3xl space-y-5 px-4 py-5 sm:px-6"><header className="flex items-center justify-between gap-3"><Button variant="outline" onClick={() => setLocation("/distribution")} className="gap-2"><Route className="h-4 w-4" />{text.back}</Button><p className="text-sm text-muted-foreground">{user?.name ?? ""}</p></header><section className="rounded-3xl border border-primary/25 bg-gradient-to-br from-primary/15 via-card to-card p-6"><p className="text-xs font-semibold tracking-[.16em] text-primary">{text.eyebrow}</p><h1 className="mt-2 text-3xl font-bold">{text.title}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{text.subtitle}</p></section>
  {routesQuery.isLoading ? <div className="space-y-4"><Skeleton className="h-48 rounded-3xl" /><Skeleton className="h-60 rounded-3xl" /></div> : routesQuery.isError ? <Card className="border-destructive/30"><CardContent className="flex gap-3 p-5 text-destructive"><CircleAlert className="h-5 w-5" />{text.routeUpdateFailed}</CardContent></Card> : !route ? <Card><CardContent className="p-8 text-center"><Truck className="mx-auto h-9 w-9 text-primary" /><h2 className="mt-3 font-bold">{text.noRoute}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text.noRouteHint}</p></CardContent></Card> : <><Card><CardHeader><CardTitle>{text.sort}</CardTitle><CardDescription>{text.selected}: {route.routeNumber}</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2">{(["priority", "distance", "sequence"] as SortMode[]).map(mode => <Button key={mode} size="sm" variant={sortMode === mode ? "default" : "outline"} onClick={() => setSortMode(mode)}>{text[mode]}</Button>)}</div>{rankedRoutes.length > 1 ? <div className="flex gap-2 overflow-x-auto pb-1">{rankedRoutes.map(item => <Button key={item.route.id} size="sm" variant={route.id === item.route.id ? "secondary" : "ghost"} onClick={() => setSelectedRouteId(item.route.id)}>{item.route.routeNumber}</Button>)}</div> : null}</CardContent></Card><Card className="border-primary/20"><CardHeader><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-primary">{text.activeRoute}</p><CardTitle className="mt-1">{route.routeNumber}</CardTitle><CardDescription>{text.routeDate}: {formatDate(route.routeDate)} · {text.vehicle}: {route.vehicleCode ?? "—"}</CardDescription></div><Badge variant={route.status === "in_progress" ? "default" : "secondary"}>{route.status}</Badge></div></CardHeader><CardContent className="flex flex-wrap gap-2">{route.status === "started" ? <Button onClick={() => transition.mutate({ routeId: route.id, status: "in_progress" })} disabled={transition.isPending} className="gap-2"><Play className="h-4 w-4" />{text.startDelivery}</Button> : null}{route.status === "in_progress" ? <Button variant="outline" onClick={() => transition.mutate({ routeId: route.id, status: "returning" })} disabled={transition.isPending} className="gap-2"><Pause className="h-4 w-4" />{text.returning}</Button> : null}</CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><LocateFixed className="h-5 w-5 text-primary" />{text.tracking}</CardTitle><CardDescription>{text.trackingHint}</CardDescription></CardHeader><CardContent className="space-y-3"><label className="flex items-start gap-3 rounded-2xl border border-border/70 p-3 text-sm"><Checkbox checked={consent} onCheckedChange={checked => setConsent(checked === true)} /><span>{text.consent}</span></label><div className="flex items-center justify-between gap-3 rounded-2xl bg-muted/50 p-3"><span className="flex items-center gap-2 text-sm">{tracking ? <Signal className="h-4 w-4 text-primary" /> : <WifiOff className="h-4 w-4" />}{tracking ? text.trackingOn : text.trackingOff}</span><Button onClick={tracking ? stopTracking : startTracking} disabled={!tracking && !consent} variant={tracking ? "outline" : "default"} className="gap-2">{tracking ? <Pause className="h-4 w-4" /> : <Crosshair className="h-4 w-4" />}{tracking ? text.stopTracking : text.startTracking}</Button></div><div className="flex items-center justify-between gap-3 rounded-2xl border border-border/70 p-3"><p className="text-xs text-muted-foreground">{queuedCount ? `${queuedCount} ${queuedCount === 1 ? text.queued : text.queuedPlural}` : (online ? text.online : text.offline)}</p><Button size="sm" variant="outline" onClick={() => void flushQueue()} disabled={!queuedCount || !online} className="gap-2"><RefreshCcw className="h-3.5 w-3.5" />{text.sync}</Button></div><div className="rounded-2xl border border-primary/15 p-3"><p className="flex items-center gap-2 text-sm font-semibold text-primary"><ShieldCheck className="h-4 w-4" />{text.privacy}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{text.privacyHint}</p></div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><MapPinned className="h-5 w-5 text-primary" />{text.map}</CardTitle><CardDescription>{text.mapHint}</CardDescription></CardHeader><CardContent><DriverRouteMap stops={route.stops} current={position} /></CardContent></Card><DriverDailyOperations routeId={route.id} vehicleId={route.vehicleId} stop={route.stops.find(stop => stop.deliveryStatus === "arrived") ?? route.stops[0]} inventory={inventory.data ?? []} labels={operationCopy[language]} onSuccess={() => { void routesQuery.refetch(); void inventory.refetch(); }} /><Card><CardHeader><CardTitle>{text.stops}</CardTitle></CardHeader><CardContent className="space-y-3">{[...route.stops].sort((a, b) => sortMode === "priority" ? (priorityScore[String(b.visitPriority)] ?? 0) - (priorityScore[String(a.visitPriority)] ?? 0) : sortMode === "distance" && position ? (() => { const aLat = asNumber(a.customerLatitude), aLng = asNumber(a.customerLongitude), bLat = asNumber(b.customerLatitude), bLng = asNumber(b.customerLongitude); return (aLat === null || aLng === null ? Number.MAX_SAFE_INTEGER : distanceMeters(position, aLat, aLng)) - (bLat === null || bLng === null ? Number.MAX_SAFE_INTEGER : distanceMeters(position, bLat, bLng)); })() : a.sequence - b.sequence).map(stop => { const latitude = asNumber(stop.customerLatitude), longitude = asNumber(stop.customerLongitude); const arrived = stop.deliveryStatus === "arrived" || Boolean(stop.arrivedAt); const navigationUrl = latitude === null || longitude === null ? null : `https://www.google.com/maps/dir/?api=1&destination=${latitude},${longitude}`; return <article key={stop.id} className="rounded-2xl border border-border/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-primary">{stop.sequence}. {text.stop}</p><h3 className="mt-1 font-bold">{stop.customerName}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{stop.customerAddress ?? stop.deliveryNotes ?? text.destinationMissing}</p></div><Badge variant={arrived ? "default" : "outline"}>{arrived ? text.arrivalState : text.pendingState}</Badge></div><div className="mt-3 flex flex-wrap gap-2">{navigationUrl ? <Button asChild variant="outline" size="sm"><a href={navigationUrl} target="_blank" rel="noreferrer" className="gap-2"><Navigation className="h-3.5 w-3.5" />{text.navigate}</a></Button> : null}{!arrived ? <Button size="sm" onClick={() => markArrival(stop)} disabled={geofence.isPending} className="gap-2"><MapPinned className="h-3.5 w-3.5" />{text.arrived}</Button> : <DriverDeliveryProof routeId={route.id} stopId={stop.id} customerId={stop.customerId} proofId={stop.proofId} onSuccess={() => void routesQuery.refetch()} text={text} />}</div></article>; })}</CardContent></Card></>}
  </div></main>;
}
