import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { BookOpen, Download, FileText, Landmark, Loader2, RefreshCcw, Scale, WalletCards } from "lucide-react";
import { toast } from "sonner";
import React from "react";

const copy = {
  ar: { title: "مركز المالية والمحاسبة", subtitle: "قيود مدققة مرتبطة بالأحداث التشغيلية الفعلية داخل مؤسستك.", overview: "نظرة عامة", accounts: "دليل الحسابات", entries: "القيود", aging: "الذمم", treasury: "الخزينة", reports: "التقارير", reconciliation: "المصالحات", dimensions: "الأبعاد", budget: "الميزانية مقابل الفعلي", bootstrap: "تهيئة نواة المالية", bootstrapHint: "أنشئ دليل الحسابات والدفاتر والمطابقات العامة لمؤسستك.", revenue: "ذمم مدينة", payable: "ذمم دائنة", cash: "الصناديق والبنوك", journal: "قيود مرسّلة", current: "حالي", overdue: "متأخر", empty: "لا توجد بيانات قابلة للعرض حالياً.", exportExcel: "Excel", exportPdf: "PDF", exportHint: "صدّر الملخص الظاهر للمراجعة والمشاركة.", initialized: "تمت تهيئة نواة المالية.", status: "الحالة", account: "الحساب", amount: "الرصيد", reference: "المرجع", date: "التاريخ", code: "الرمز", bank: "بنك", cashbox: "صندوق", trialBalance: "ميزان المراجعة", profitLoss: "قائمة الدخل", balanceSheet: "الميزانية العمومية", cashFlow: "التدفق النقدي", generalLedger: "الأستاذ العام", netProfit: "صافي الربح", reconciled: "المصالحات المسجلة", costCenters: "مراكز التكلفة" },
  fr: { title: "Centre finance et comptabilité", subtitle: "Écritures auditées reliées aux événements opérationnels réels de votre organisation.", overview: "Vue d’ensemble", accounts: "Plan comptable", entries: "Écritures", aging: "Créances et dettes", treasury: "Trésorerie", reports: "Rapports", reconciliation: "Rapprochements", dimensions: "Dimensions", budget: "Budget vs réalisé", bootstrap: "Initialiser la finance", bootstrapHint: "Créez le plan comptable, les journaux et les correspondances génériques.", revenue: "Créances clients", payable: "Dettes fournisseurs", cash: "Caisses et banques", journal: "Écritures comptables", current: "Courant", overdue: "En retard", empty: "Aucune donnée à afficher.", exportExcel: "Excel", exportPdf: "PDF", exportHint: "Exportez le résumé visible pour revue et partage.", initialized: "Noyau financier initialisé.", status: "Statut", account: "Compte", amount: "Solde", reference: "Référence", date: "Date", code: "Code", bank: "Banque", cashbox: "Caisse", trialBalance: "Balance", profitLoss: "Compte de résultat", balanceSheet: "Bilan", cashFlow: "Flux de trésorerie", generalLedger: "Grand livre", netProfit: "Résultat net", reconciled: "Rapprochements enregistrés", costCenters: "Centres de coûts" },
  en: { title: "Finance & accounting center", subtitle: "Audited journals tied to your organization’s real operational events.", overview: "Overview", accounts: "Chart of accounts", entries: "Journal entries", aging: "Receivables & payables", treasury: "Treasury", reports: "Reports", reconciliation: "Reconciliations", dimensions: "Dimensions", budget: "Budget vs actual", bootstrap: "Initialize finance", bootstrapHint: "Create the standard chart, journals, and account mappings for your organization.", revenue: "Accounts receivable", payable: "Accounts payable", cash: "Cashboxes & banks", journal: "Posted journals", current: "Current", overdue: "Overdue", empty: "No data available yet.", exportExcel: "Excel", exportPdf: "PDF", exportHint: "Export the visible summary for review and sharing.", initialized: "Financial core initialized.", status: "Status", account: "Account", amount: "Balance", reference: "Reference", date: "Date", code: "Code", bank: "Bank", cashbox: "Cashbox", trialBalance: "Trial balance", profitLoss: "Profit & loss", balanceSheet: "Balance sheet", cashFlow: "Cash flow", generalLedger: "General ledger", netProfit: "Net profit", reconciled: "Recorded reconciliations", costCenters: "Cost centers" },
} as const;
type FinanceText = { [K in keyof (typeof copy)["ar"]]: string };

function money(value: number) { return new Intl.NumberFormat(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); }

export default function Finance() {
  const { language, direction } = useLanguage();
  const text = copy[language];
  const utils = trpc.useUtils();
  const accounts = trpc.erp.finance.chartOfAccounts.useQuery();
  const entries = trpc.erp.finance.journalEntries.useQuery();
  const aging = trpc.erp.finance.aging.receivables.useQuery();
  const payables = trpc.erp.finance.aging.payables.useQuery();
  const treasury = trpc.erp.finance.treasury.list.useQuery();
  const trialBalance = trpc.erp.finance.reports.trialBalance.useQuery();
  const profitAndLoss = trpc.erp.finance.reports.profitAndLoss.useQuery();
  const balanceSheet = trpc.erp.finance.reports.balanceSheet.useQuery();
  const cashFlow = trpc.erp.finance.reports.cashFlow.useQuery();
  const ledger = trpc.erp.finance.reports.generalLedger.useQuery();
  const reconciliations = trpc.erp.finance.reconciliations.list.useQuery();
  const costCenters = trpc.erp.finance.planning.costCenters.useQuery();
  const budgets = trpc.erp.finance.planning.budgets.useQuery();
  const activeBudgetId = budgets.data?.[0]?.id;
  const budgetInput = React.useMemo(() => ({ budgetId: activeBudgetId ?? 1 }), [activeBudgetId]);
  const budgetVsActual = trpc.erp.finance.planning.budgetVsActual.useQuery(budgetInput, { enabled: Boolean(activeBudgetId) });
  const bootstrap = trpc.erp.finance.bootstrap.useMutation({ onSuccess: () => { toast.success(text.initialized); void Promise.all([utils.erp.finance.chartOfAccounts.invalidate(), utils.erp.finance.setup.invalidate()]); }, onError: error => toast.error(error.message) });
  const totalReceivable = Object.values(aging.data?.totals ?? {}).reduce((sum, value) => sum + Number(value), 0);
  const totalPayable = Object.values(payables.data?.totals ?? {}).reduce((sum, value) => sum + Number(value), 0);
  const totalTreasury = [...(treasury.data?.cashboxes ?? []), ...(treasury.data?.banks ?? [])].reduce((sum, item) => sum + Number(item.balance), 0);
  const rows = entries.data ?? [];
  const exportExcel = () => { const exportRows = ledger.data?.length ? ledger.data.map(row => [new Date(row.entryDate).toLocaleDateString(), row.journalNumber, row.accountNameAr, money(row.balance)]) : rows.map(row => [new Date(row.entryDate).toLocaleDateString(), row.journalNumber, row.status, row.reference ?? ""]); const body = exportRows.map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join("")}</tr>`).join(""); const blob = new Blob([`<table><tr><th>${text.date}</th><th>${text.reference}</th><th>${text.account}</th><th>${text.amount}</th></tr>${body}</table>`], { type: "application/vnd.ms-excel;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "nawa-finance-report.xls"; a.click(); URL.revokeObjectURL(url); };
  const metricCards: Array<{ label: string; value: number; Icon: typeof Scale }> = [{ label: text.revenue, value: totalReceivable, Icon: Scale }, { label: text.payable, value: totalPayable, Icon: Scale }, { label: text.cash, value: totalTreasury, Icon: WalletCards }, { label: text.journal, value: rows.filter(row => row.status === "posted").length, Icon: BookOpen }];
  return <DashboardLayout><main dir={direction} className="mx-auto w-full max-w-[1500px] space-y-6 p-4 md:p-7"><section className="rounded-3xl border border-primary/20 bg-gradient-to-br from-primary/15 via-card to-card p-6 shadow-2xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-primary"><Landmark className="h-5 w-5" /><span className="text-sm font-semibold">Nawa ERP</span></div><h1 className="text-3xl font-bold tracking-tight">{text.title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{text.subtitle}</p></div><Button onClick={() => bootstrap.mutate()} disabled={bootstrap.isPending} className="bg-primary text-primary-foreground"><RefreshCcw className={`me-2 h-4 w-4 ${bootstrap.isPending ? "animate-spin" : ""}`} />{text.bootstrap}</Button></div></section>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metricCards.map(({ label, value, Icon }) => <Card key={label} className="border-white/10 bg-card/80"><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{money(value)}</p></div><Icon className="h-8 w-8 text-primary" /></CardContent></Card>)}</div>
  <Tabs defaultValue="overview" className="space-y-5"><TabsList className="h-auto flex-wrap justify-start gap-1 bg-card p-1">{[["overview",text.overview],["accounts",text.accounts],["entries",text.entries],["aging",text.aging],["treasury",text.treasury],["reconciliation",text.reconciliation],["dimensions",text.dimensions],["reports",text.reports]].map(([value,label])=><TabsTrigger key={value} value={value}>{label}</TabsTrigger>)}</TabsList>
  <TabsContent value="overview"><Card><CardHeader><CardTitle>{text.overview}</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-muted/40 p-4"><p className="text-sm text-muted-foreground">{text.current}</p><p className="mt-1 text-xl font-semibold">{money(Number(aging.data?.totals.current ?? 0))}</p></div><div className="rounded-2xl bg-amber-500/10 p-4"><p className="text-sm text-muted-foreground">{text.overdue}</p><p className="mt-1 text-xl font-semibold text-amber-500">{money(totalReceivable-Number(aging.data?.totals.current ?? 0))}</p></div></CardContent></Card></TabsContent>
  <TabsContent value="accounts"><FinanceTable headers={[text.code,text.account,text.status]} rows={(accounts.data??[]).map(row=>[row.code,row.nameAr,row.status])} empty={text.empty} /></TabsContent>
  <TabsContent value="entries"><FinanceTable headers={[text.reference,text.status,text.date,text.code]} rows={rows.map(row=>[row.journalNumber,row.status,new Date(row.entryDate).toLocaleDateString(),row.reference??"—"])} empty={text.empty} /></TabsContent>
  <TabsContent value="aging"><div className="grid gap-5 lg:grid-cols-2"><AgingCard title={text.revenue} data={aging.data?.totals} text={text}/><AgingCard title={text.payable} data={payables.data?.totals} text={text}/></div></TabsContent>
  <TabsContent value="treasury"><div className="grid gap-5 lg:grid-cols-2"><FinanceTable headers={[text.code,text.cashbox,text.amount]} rows={(treasury.data?.cashboxes??[]).map(row=>[row.code,row.name,money(Number(row.balance))])} empty={text.empty}/><FinanceTable headers={[text.code,text.bank,text.amount]} rows={(treasury.data?.banks??[]).map(row=>[row.code,row.name,money(Number(row.balance))])} empty={text.empty}/></div></TabsContent>
  <TabsContent value="reconciliation"><div className="grid gap-5 lg:grid-cols-2"><FinanceTable headers={[text.bank,text.date,text.status,text.amount]} rows={(reconciliations.data?.banks??[]).map(row=>[String(row.bankAccountId),new Date(row.statementDate).toLocaleDateString(),row.status,money(Number(row.difference))])} empty={text.empty}/><FinanceTable headers={[text.cashbox,text.date,text.status,text.amount]} rows={(reconciliations.data?.cash??[]).map(row=>[String(row.cashboxId),new Date(row.reconciledAt).toLocaleDateString(),row.status,money(Number(row.difference))])} empty={text.empty}/></div></TabsContent>
  <TabsContent value="dimensions"><div className="space-y-5"><FinanceTable headers={[text.code,text.costCenters,text.status]} rows={(costCenters.data??[]).map(row=>[row.code,row.name,row.status])} empty={text.empty}/><Card><CardHeader><CardTitle>{text.budget}</CardTitle></CardHeader><CardContent><FinanceTable headers={[text.account,text.amount,text.status]} rows={(budgetVsActual.data?.lines??[]).map(row=>[row.accountNameAr,`${money(row.budgetAmount)} / ${money(row.actual)}`,money(row.variance)])} empty={text.empty}/></CardContent></Card></div></TabsContent>
  <TabsContent value="reports"><div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><ReportMetric title={text.netProfit} value={Number(profitAndLoss.data?.netProfit??0)}/><ReportMetric title={text.cashFlow} value={Number(cashFlow.data?.netCashFlow??0)}/><ReportMetric title={text.balanceSheet} value={Number(balanceSheet.data?.totals.assets??0)}/></div><FinanceTable headers={[text.code,text.account,text.amount]} rows={(trialBalance.data?.lines??[]).map(row=>[row.code,row.nameAr,money(Number(row.closingDebit)-Number(row.closingCredit))])} empty={text.empty}/><FinanceTable headers={[text.date,text.reference,text.account,text.amount]} rows={(ledger.data??[]).map(row=>[new Date(row.entryDate).toLocaleDateString(),row.journalNumber,row.accountNameAr,money(row.balance)])} empty={text.empty}/><Card><CardHeader><CardTitle>{text.reports}</CardTitle></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-4"><p className="text-sm text-muted-foreground">{text.exportHint}</p><div className="flex gap-2"><Button variant="outline" onClick={exportExcel}><Download className="me-2 h-4 w-4"/>{text.exportExcel}</Button><Button variant="outline" onClick={()=>window.print()}><FileText className="me-2 h-4 w-4"/>{text.exportPdf}</Button></div></CardContent></Card></div></TabsContent></Tabs></main></DashboardLayout>;
}
function FinanceTable({ headers, rows, empty }: { headers: string[]; rows: string[][]; empty: string }) { return <Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/40 text-muted-foreground"><tr>{headers.map(header=><th key={header} className="whitespace-nowrap px-4 py-3 text-start font-medium">{header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row,index)=><tr key={`${row[0]}-${index}`} className="border-t border-border/60">{row.map((cell,i)=><td key={i} className="whitespace-nowrap px-4 py-3">{i===1&&["posted","draft","reversed","active","inactive"].includes(cell)?<Badge variant="outline">{cell}</Badge>:cell}</td>)}</tr>) : <tr><td colSpan={headers.length} className="px-4 py-10 text-center text-muted-foreground">{empty}</td></tr>}</tbody></table></div></CardContent></Card>; }
function AgingCard({ title, data, text }: { title: string; data: Record<string, number> | undefined; text: FinanceText }) { const labels: Record<string,string>={current:text.current,"1_30":"1–30","31_60":"31–60","61_90":"61–90","90_plus":"90+"}; return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="space-y-3">{Object.entries(labels).map(([key,label])=><div key={key} className="flex items-center justify-between border-b border-border/50 pb-2 text-sm"><span className="text-muted-foreground">{label}</span><span className="font-semibold">{money(Number(data?.[key]??0))}</span></div>)}</CardContent></Card>; }
function ReportMetric({ title, value }: { title: string; value: number }) { return <Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">{title}</p><p className="mt-1 text-xl font-bold">{money(value)}</p></CardContent></Card>; }
