import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { Building2, FileText, PackagePlus, RefreshCw, Search, ShoppingCart, Store, Truck } from "lucide-react";
import React, { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type CartLine = { productId: number; quantity: number; unit: string };
type RetailerCopy = { title: string; subtitle: string; choose: string; catalog: string; search: string; cart: string; add: string; empty: string; total: string; send: string; orders: string; documents: string; reorder: string; noAccess: string; noProducts: string; available: string; low: string; unavailable: string; request: string; quantity: string; submitted: string; error: string; newest: string; debt: string; delivery: string; remove: string };
const copy: Record<"ar" | "fr" | "en", RetailerCopy> = {
  ar: { title: "بوابة المحل", subtitle: "الطلبات والأسعار المخصصة في مكان واحد", choose: "اختر المؤسسة", catalog: "الكتالوج", search: "ابحث باسم المنتج أو SKU", cart: "السلة", add: "إضافة", empty: "السلة فارغة", total: "الإجمالي", send: "إرسال الطلب", orders: "طلباتي", documents: "المستندات والرصيد", reorder: "إعادة الطلب", noAccess: "لا توجد مؤسسة مصرح بها لهذا الحساب.", noProducts: "لا توجد منتجات مطابقة.", available: "متاح", low: "توفر محدود", unavailable: "غير متاح", request: "عند الطلب", quantity: "الكمية", submitted: "تم إرسال الطلب للمراجعة.", error: "تعذر إتمام العملية حالياً.", newest: "أحدث الطلبات", debt: "الرصيد المتبقي", delivery: "حالة التوصيل", remove: "إزالة" },
  fr: { title: "Portail détaillant", subtitle: "Vos commandes et tarifs dédiés au même endroit", choose: "Choisir l’organisation", catalog: "Catalogue", search: "Rechercher par produit ou SKU", cart: "Panier", add: "Ajouter", empty: "Le panier est vide", total: "Total", send: "Envoyer la commande", orders: "Mes commandes", documents: "Documents et solde", reorder: "Commander à nouveau", noAccess: "Aucune organisation n’est autorisée pour ce compte.", noProducts: "Aucun produit correspondant.", available: "Disponible", low: "Disponibilité limitée", unavailable: "Indisponible", request: "Sur demande", quantity: "Quantité", submitted: "Commande envoyée pour examen.", error: "L’opération n’a pas pu être effectuée.", newest: "Dernières commandes", debt: "Solde restant", delivery: "État de livraison", remove: "Retirer" },
  en: { title: "Retailer portal", subtitle: "Your dedicated orders and prices in one place", choose: "Choose organisation", catalog: "Catalog", search: "Search product or SKU", cart: "Cart", add: "Add", empty: "Your cart is empty", total: "Total", send: "Submit order", orders: "My orders", documents: "Documents and balance", reorder: "Reorder", noAccess: "No organisation is authorised for this account.", noProducts: "No matching products.", available: "Available", low: "Low availability", unavailable: "Out of stock", request: "On request", quantity: "Quantity", submitted: "Order sent for review.", error: "The operation could not be completed.", newest: "Recent orders", debt: "Outstanding balance", delivery: "Delivery status", remove: "Remove" },
};

export default function Retailer() {
  const { language, direction, formatNumber } = useLanguage();
  const text = copy[language];
  const utils = trpc.useUtils();
  const [accessId, setAccessId] = useState("");
  const [search, setSearch] = useState("");
  const [cart, setCart] = useState<CartLine[]>([]);
  const accesses = trpc.erp.b2b.accesses.useQuery();
  const selected = accesses.data?.find(item => String(item.id) === accessId);
  const catalogInput = useMemo(() => ({ accessId: Number(accessId || 0), query: search || undefined }), [accessId, search]);
  const catalog = trpc.erp.b2b.catalog.useQuery(catalogInput, { enabled: Boolean(accessId) });
  const orders = trpc.erp.b2b.orders.list.useQuery({ accessId: Number(accessId || 0) }, { enabled: Boolean(accessId) });
  const documents = trpc.erp.b2b.documents.useQuery({ accessId: Number(accessId || 0) }, { enabled: Boolean(accessId) });
  useEffect(() => {
    if (!accessId) return;
    try { setCart(JSON.parse(localStorage.getItem(`nawa-b2b-cart-${accessId}`) || "[]")); } catch { setCart([]); }
  }, [accessId]);
  useEffect(() => { if (accessId) localStorage.setItem(`nawa-b2b-cart-${accessId}`, JSON.stringify(cart)); }, [accessId, cart]);
  const createOrder = trpc.erp.b2b.orders.create.useMutation({ onSuccess: () => { setCart([]); toast.success(text.submitted); utils.erp.b2b.orders.list.invalidate({ accessId: Number(accessId) }); }, onError: () => toast.error(text.error) });
  const reorder = trpc.erp.b2b.orders.reorder.useMutation({ onSuccess: () => { toast.success(text.submitted); utils.erp.b2b.orders.list.invalidate({ accessId: Number(accessId) }); }, onError: () => toast.error(text.error) });
  const cartProducts = catalog.data?.filter((product: any) => cart.some(line => line.productId === product.id)) ?? [];
  const total = cart.reduce((sum, line) => { const product = cartProducts.find((item: any) => item.id === line.productId); return sum + Number(product?.unitPrice ?? 0) * line.quantity; }, 0);
  const availabilityLabel = (status: string) => status === "available" ? text.available : status === "low_availability" ? text.low : status === "on_request" ? text.request : text.unavailable;
  const productName = (product: NonNullable<typeof catalog.data>[number]) => language === "ar" ? product.nameAr || product.name : language === "fr" ? product.nameFr || product.name : product.nameEn || product.name;
  const changeQuantity = (productId: number, unit: string, delta: number) => setCart(current => { const found = current.find(item => item.productId === productId); if (!found && delta > 0) return [...current, { productId, unit, quantity: delta }]; if (!found) return current; const quantity = found.quantity + delta; return quantity <= 0 ? current.filter(item => item.productId !== productId) : current.map(item => item.productId === productId ? { ...item, quantity } : item); });
  return <main dir={direction} className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-6xl space-y-5 px-4 py-6 sm:px-6"><header className="rounded-3xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-primary">Nawa B2B</p><h1 className="mt-1 text-2xl font-bold">{text.title}</h1><p className="mt-1 text-sm text-muted-foreground">{text.subtitle}</p></div><Store className="h-10 w-10 text-primary" /></div><div className="mt-5 max-w-md"><Label>{text.choose}</Label><Select value={accessId} onValueChange={setAccessId}><SelectTrigger><SelectValue placeholder={text.choose} /></SelectTrigger><SelectContent>{accesses.data?.map((item: any) => <SelectItem key={item.id} value={String(item.id)}>{item.organizationName} · {item.customerName}</SelectItem>)}</SelectContent></Select></div></header>
  {accesses.isLoading ? <Card><CardContent className="p-6 text-sm text-muted-foreground">…</CardContent></Card> : !accesses.data?.length ? <Card><CardContent className="p-6 text-sm text-muted-foreground">{text.noAccess}</CardContent></Card> : selected ? <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><section className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><PackagePlus className="h-5 w-5 text-primary" />{text.catalog}</CardTitle><CardDescription>{selected.organizationName}</CardDescription></CardHeader><CardContent><div className="relative mb-4"><Search className="absolute start-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="ps-9" value={search} onChange={event => setSearch(event.target.value)} placeholder={text.search} /></div><div className="grid gap-3 sm:grid-cols-2">{catalog.data?.map((product: any) => <article key={product.id} className="rounded-2xl border border-border p-4"><div className="flex items-start justify-between gap-2"><div><h2 className="font-semibold">{productName(product)}</h2><p className="mt-1 text-xs text-muted-foreground">{product.sku} · {product.salesUnit}</p>{product.promotionLabel ? <p className="mt-2 text-xs font-medium text-primary">{product.promotionLabel}</p> : null}</div><span className="rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">{availabilityLabel(product.availability)}</span></div><div className="mt-4 flex items-center justify-between"><strong>{formatNumber(Number(product.unitPrice))} {product.currencyCode}</strong><Button size="sm" disabled={product.availability === "out_of_stock"} onClick={() => changeQuantity(product.id, product.salesUnit, 1)}>{text.add}</Button></div></article>)}{!catalog.isLoading && !catalog.data?.length ? <p className="text-sm text-muted-foreground">{text.noProducts}</p> : null}</div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><Truck className="h-5 w-5 text-primary" />{text.newest}</CardTitle></CardHeader><CardContent className="space-y-3">{orders.data?.map((order: any) => <div key={order.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-border p-3"><div><p className="font-medium">{order.orderNumber}</p><p className="text-xs text-muted-foreground">{order.displayStatus} · {order.paymentStatus} · {formatNumber(Number(order.totalAmount))} {order.currencyCode}</p></div><Button variant="outline" size="sm" disabled={reorder.isPending} onClick={() => reorder.mutate({ accessId: Number(accessId), orderId: order.id })}><RefreshCw className="me-1 h-4 w-4" />{text.reorder}</Button></div>)}</CardContent></Card></section>
  <aside className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShoppingCart className="h-5 w-5 text-primary" />{text.cart}</CardTitle></CardHeader><CardContent className="space-y-3">{cart.map(line => { const product = cartProducts.find((item: any) => item.id === line.productId); return <div key={line.productId} className="rounded-xl border border-border p-3"><p className="font-medium">{product ? productName(product) : line.productId}</p><div className="mt-2 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Button size="icon" variant="outline" onClick={() => changeQuantity(line.productId, line.unit, -1)}>−</Button><span>{formatNumber(line.quantity)}</span><Button size="icon" variant="outline" onClick={() => changeQuantity(line.productId, line.unit, 1)}>+</Button></div><Button size="sm" variant="ghost" onClick={() => setCart(current => current.filter(item => item.productId !== line.productId))}>{text.remove}</Button></div></div>; })}{!cart.length ? <p className="text-sm text-muted-foreground">{text.empty}</p> : <><div className="flex justify-between border-t border-border pt-3 font-semibold"><span>{text.total}</span><span>{formatNumber(total)} {selected.organizationCurrency}</span></div><Button className="w-full" disabled={createOrder.isPending} onClick={() => createOrder.mutate({ accessId: Number(accessId), lines: cart })}>{text.send}</Button></>}</CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileText className="h-5 w-5 text-primary" />{text.documents}</CardTitle></CardHeader><CardContent className="space-y-2">{documents.data?.map((document: any) => <div key={document.id} className="rounded-lg bg-muted/50 p-3 text-sm"><p className="font-medium">{document.invoiceNumber}</p><p className="text-muted-foreground">{text.debt}: {formatNumber(Number(document.grandTotal) - Number(document.amountPaid))} {document.currencyCode}</p></div>)}</CardContent></Card></aside></div> : null}</div></main>;
}
