import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useLanguage } from "@/contexts/LanguageContext";
import { buildRetailerReportCsv, buildRetailerReportPdf } from "@/lib/retailerReportExport";
import { trpc } from "@/lib/trpc";
import { Building2, Download, FileSpreadsheet, FileText, Heart, LayoutDashboard, PackagePlus, ReceiptText, RefreshCw, Search, ShoppingBag, ShoppingCart, Store, Truck } from "lucide-react";
import React, { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type CartLine = { productId: number; quantity: number; unit: string };
type RetailTab = "home" | "catalog" | "cart" | "orders" | "documents";
type Copy = { title: string; subtitle: string; supplier: string; choose: string; home: string; catalog: string; cart: string; orders: string; documents: string; activeOrders: string; debt: string; promotions: string; favorites: string; frequent: string; search: string; add: string; remove: string; total: string; send: string; reorder: string; delivery: string; noAccess: string; noProducts: string; noFavorites: string; noOrders: string; noDocuments: string; empty: string; available: string; low: string; request: string; unavailable: string; loading: string; submitted: string; favoriteAdded: string; favoriteRemoved: string; error: string; browse: string; items: string; monthlyReport: string; exportCsv: string; exportPdf: string; reportMonth: string };
const copy: Record<"ar" | "fr" | "en", Copy> = {
  ar: { title: "واجهة طلباتك التجارية", subtitle: "اطلب من مورديك المعتمدين بأسعارك الخاصة", supplier: "المورد", choose: "اختر المورد", home: "الرئيسية", catalog: "الكتالوج", cart: "السلة", orders: "طلباتي", documents: "المستندات والرصيد", activeOrders: "طلبات نشطة", debt: "الرصيد المتبقي", promotions: "عروض متاحة", favorites: "مفضلاتي", frequent: "تشتريه غالباً", search: "ابحث باسم المنتج أو SKU", add: "أضف", remove: "إزالة", total: "الإجمالي", send: "إرسال الطلب", reorder: "إعادة الطلب", delivery: "حالة التوصيل", noAccess: "لا توجد مؤسسة مصرح بها لهذا الحساب.", noProducts: "لا توجد منتجات مطابقة.", noFavorites: "أضف منتجاتك المفضلة للوصول إليها بسرعة.", noOrders: "لم تسجل طلبات بعد.", noDocuments: "لا توجد مستندات متاحة.", empty: "السلة فارغة", available: "متاح", low: "توفر محدود", request: "عند الطلب", unavailable: "غير متاح", loading: "جارٍ التحميل…", submitted: "تم إرسال الطلب للمراجعة.", favoriteAdded: "أضيف المنتج إلى المفضلة.", favoriteRemoved: "أزيل المنتج من المفضلة.", error: "تعذر إتمام العملية حالياً.", browse: "تصفح الكتالوج", items: "منتجات", monthlyReport: "التقرير الشهري", exportCsv: "CSV", exportPdf: "PDF", reportMonth: "الشهر" },
  fr: { title: "Votre espace d’achat", subtitle: "Commandez auprès de vos fournisseurs autorisés à vos tarifs dédiés", supplier: "Fournisseur", choose: "Choisir le fournisseur", home: "Accueil", catalog: "Catalogue", cart: "Panier", orders: "Mes commandes", documents: "Documents et solde", activeOrders: "Commandes actives", debt: "Solde restant", promotions: "Offres disponibles", favorites: "Favoris", frequent: "Commandé fréquemment", search: "Rechercher un produit ou SKU", add: "Ajouter", remove: "Retirer", total: "Total", send: "Envoyer la commande", reorder: "Commander à nouveau", delivery: "État de livraison", noAccess: "Aucune organisation n’est autorisée pour ce compte.", noProducts: "Aucun produit correspondant.", noFavorites: "Ajoutez vos produits préférés pour y accéder rapidement.", noOrders: "Aucune commande pour le moment.", noDocuments: "Aucun document disponible.", empty: "Le panier est vide", available: "Disponible", low: "Disponibilité limitée", request: "Sur demande", unavailable: "Indisponible", loading: "Chargement…", submitted: "Commande envoyée pour examen.", favoriteAdded: "Produit ajouté aux favoris.", favoriteRemoved: "Produit retiré des favoris.", error: "L’opération n’a pas pu être effectuée.", browse: "Parcourir le catalogue", items: "produits", monthlyReport: "Rapport mensuel", exportCsv: "CSV", exportPdf: "PDF", reportMonth: "Mois" },
  en: { title: "Your trade ordering space", subtitle: "Order from your authorised suppliers at your dedicated prices", supplier: "Supplier", choose: "Choose supplier", home: "Home", catalog: "Catalog", cart: "Cart", orders: "My orders", documents: "Documents and balance", activeOrders: "Active orders", debt: "Outstanding balance", promotions: "Available offers", favorites: "Favorites", frequent: "Frequently ordered", search: "Search product or SKU", add: "Add", remove: "Remove", total: "Total", send: "Submit order", reorder: "Reorder", delivery: "Delivery status", noAccess: "No organisation is authorised for this account.", noProducts: "No matching products.", noFavorites: "Add your preferred products for quick access.", noOrders: "No orders yet.", noDocuments: "No documents available.", empty: "Your cart is empty", available: "Available", low: "Low availability", request: "On request", unavailable: "Unavailable", loading: "Loading…", submitted: "Order sent for review.", favoriteAdded: "Product added to favorites.", favoriteRemoved: "Product removed from favorites.", error: "The operation could not be completed.", browse: "Browse catalog", items: "items", monthlyReport: "Monthly report", exportCsv: "CSV", exportPdf: "PDF", reportMonth: "Month" },
};

const availabilityStyle = (value: string) => value === "available" ? "bg-emerald-500/10 text-emerald-400" : value === "low_availability" ? "bg-amber-400/10 text-amber-300" : value === "on_request" ? "bg-sky-400/10 text-sky-300" : "bg-rose-400/10 text-rose-300";
const download = (name: string, content: BlobPart, type: string) => {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  URL.revokeObjectURL(url);
};

export default function Retailer() {
  const { language, direction, formatNumber } = useLanguage();
  const text = copy[language];
  const utils = trpc.useUtils();
  const [accessId, setAccessId] = useState("");
  const [search, setSearch] = useState("");
  const [activeTab, setActiveTab] = useState<RetailTab>("home");
  const [cart, setCart] = useState<CartLine[]>([]);
  const [selectedOutletId, setSelectedOutletId] = useState("");
  const [clientOperationId, setClientOperationId] = useState("");
  const [reportPeriod, setReportPeriod] = useState(() => new Date().toISOString().slice(0, 7));
  const accesses = trpc.erp.b2b.accesses.useQuery();
  const selected = accesses.data?.find(item => String(item.id) === accessId);
  const accessInput = useMemo(() => ({ accessId: Number(accessId || 0) }), [accessId]);
  const catalogInput = useMemo(() => ({ ...accessInput, query: search.trim() || undefined }), [accessInput, search]);
  const reportInput = useMemo(() => ({ ...accessInput, month: Number(reportPeriod.slice(5, 7)), year: Number(reportPeriod.slice(0, 4)) }), [accessInput, reportPeriod]);
  const catalog = trpc.erp.b2b.catalog.useQuery(catalogInput, { enabled: Boolean(accessId) });
  const orders = trpc.erp.b2b.orders.list.useQuery(accessInput, { enabled: Boolean(accessId) });
  const documents = trpc.erp.b2b.documents.useQuery(accessInput, { enabled: Boolean(accessId) });
  const summary = trpc.erp.b2b.summary.useQuery(accessInput, { enabled: Boolean(accessId) });
  const favorites = trpc.erp.b2b.favorites.list.useQuery(accessInput, { enabled: Boolean(accessId) });
  const frequent = trpc.erp.b2b.frequent.useQuery(accessInput, { enabled: Boolean(accessId) });
  const outlets = trpc.erp.b2b.outletsForAccess.useQuery(accessInput, { enabled: Boolean(accessId) });
  const monthlyReport = trpc.erp.b2b.report.monthly.useQuery(reportInput, { enabled: Boolean(accessId) && activeTab === "documents" });

  useEffect(() => {
    const manifest = document.querySelector<HTMLLinkElement>('link[rel="manifest"]');
    const previousManifest = manifest?.getAttribute("href");
    manifest?.setAttribute("href", "/retail.webmanifest");
    if ("serviceWorker" in navigator) navigator.serviceWorker.register("/nawa-retail-sw.js", { scope: "/retailer" }).catch(() => undefined);
    return () => { if (previousManifest) manifest?.setAttribute("href", previousManifest); };
  }, []);
  useEffect(() => { if (!accessId && accesses.data?.[0]) setAccessId(String(accesses.data[0].id)); }, [accessId, accesses.data]);
  useEffect(() => { if (!accessId) return; try { setCart(JSON.parse(localStorage.getItem(`nawa-b2b-cart-${accessId}`) || "[]")); } catch { setCart([]); } }, [accessId]);
  useEffect(() => { if (outlets.data?.length === 1) setSelectedOutletId(String(outlets.data[0].id)); else if (!outlets.data?.some(outlet => String(outlet.id) === selectedOutletId)) setSelectedOutletId(""); }, [outlets.data, selectedOutletId]);
  useEffect(() => { if (accessId) localStorage.setItem(`nawa-b2b-cart-${accessId}`, JSON.stringify(cart)); }, [accessId, cart]);

  const refresh = () => { utils.erp.b2b.orders.list.invalidate(accessInput); utils.erp.b2b.summary.invalidate(accessInput); };
  const createOrder = trpc.erp.b2b.orders.create.useMutation({ onSuccess: () => { setCart([]); setClientOperationId(""); toast.success(text.submitted); refresh(); }, onError: () => toast.error(text.error) });
  const reorder = trpc.erp.b2b.orders.reorder.useMutation({ onSuccess: () => { toast.success(text.submitted); refresh(); }, onError: () => toast.error(text.error) });
  const toggleFavorite = trpc.erp.b2b.favorites.toggle.useMutation({ onSuccess: result => { toast.success(result.favorite ? text.favoriteAdded : text.favoriteRemoved); utils.erp.b2b.favorites.list.invalidate(accessInput); }, onError: () => toast.error(text.error) });

  const products = Array.from(new Map([...(catalog.data ?? []), ...(favorites.data ?? []), ...(frequent.data ?? [])].map((product: any) => [product.id, product])).values());
  const total = cart.reduce((sum, line) => sum + Number((products.find((product: any) => product.id === line.productId) as any)?.unitPrice ?? 0) * line.quantity, 0);
  const productName = (product: any) => language === "ar" ? product.nameAr || product.name : language === "fr" ? product.nameFr || product.name : product.nameEn || product.name;
  const availability = (value: string) => value === "available" ? text.available : value === "low_availability" ? text.low : value === "on_request" ? text.request : text.unavailable;
  const isFavorite = (id: number) => Boolean(favorites.data?.some((product: any) => product.id === id));
  const changeQuantity = (productId: number, unit: string, delta: number) => setCart(current => {
    const found = current.find(item => item.productId === productId && item.unit === unit);
    if (!found && delta > 0) return [...current, { productId, unit, quantity: delta }];
    if (!found) return current;
    const quantity = found.quantity + delta;
    return quantity <= 0 ? current.filter(item => !(item.productId === productId && item.unit === unit)) : current.map(item => item.productId === productId && item.unit === unit ? { ...item, quantity } : item);
  });
  const reportName = `nawa-retail-${reportPeriod}`;
  const exportCsv = () => monthlyReport.data && download(`${reportName}.csv`, buildRetailerReportCsv(monthlyReport.data), "text/csv;charset=utf-8");
  const exportPdf = async () => { if (!monthlyReport.data) return; try { const bytes = await buildRetailerReportPdf(monthlyReport.data); const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer; download(`${reportName}.pdf`, buffer, "application/pdf"); } catch { toast.error(text.error); } };
  const tabs: Array<{ id: RetailTab; label: string; icon: React.ElementType }> = [{ id: "home", label: text.home, icon: LayoutDashboard }, { id: "catalog", label: text.catalog, icon: ShoppingBag }, { id: "cart", label: text.cart, icon: ShoppingCart }, { id: "orders", label: text.orders, icon: Truck }, { id: "documents", label: text.documents, icon: FileText }];

  const ProductCard = ({ product, compact = false }: { product: any; compact?: boolean }) => <article className={`rounded-2xl border border-white/10 bg-card/90 p-3 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/35 ${compact ? "min-w-[220px]" : ""}`}>
    <div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate font-semibold">{productName(product)}</p><p className="mt-1 truncate text-xs text-muted-foreground">{product.sku} · {product.salesUnit}</p></div><Button variant="ghost" size="icon" className="shrink-0" aria-label={text.favorites} onClick={() => toggleFavorite.mutate({ ...accessInput, productId: product.id })}><Heart className={`h-4 w-4 ${isFavorite(product.id) ? "fill-primary text-primary" : ""}`} /></Button></div>
    {product.promotionLabel ? <p className="mt-3 truncate text-xs font-medium text-primary">{product.promotionLabel}</p> : null}
    <div className="mt-4 flex items-end justify-between gap-2"><div><p className="font-bold">{formatNumber(Number(product.unitPrice))} <span className="text-xs text-muted-foreground">{product.currencyCode}</span></p><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-[11px] font-medium ${availabilityStyle(product.availability)}`}>{availability(product.availability)}</span></div><Button size="sm" disabled={product.availability === "out_of_stock"} onClick={() => changeQuantity(product.id, product.salesUnit, 1)}><PackagePlus className="me-1 h-3.5 w-3.5" />{text.add}</Button></div>
  </article>;
  const CartPanel = () => <Card className="border-white/10 bg-card/95"><CardContent className="p-4"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold"><ShoppingCart className="h-4 w-4 text-primary" />{text.cart}</h2><span className="rounded-full bg-primary/10 px-2 py-1 text-xs font-semibold text-primary">{cart.reduce((sum, line) => sum + line.quantity, 0)} {text.items}</span></div>{cart.map(line => { const product: any = products.find((item: any) => item.id === line.productId); return <div key={`${line.productId}-${line.unit}`} className="mb-3 rounded-xl bg-muted/55 p-3"><p className="truncate font-medium">{product ? productName(product) : line.productId}</p><div className="mt-2 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Button size="icon" variant="outline" className="h-8 w-8" onClick={() => changeQuantity(line.productId, line.unit, -1)}>−</Button><span className="min-w-6 text-center text-sm font-semibold">{formatNumber(line.quantity)}</span><Button size="icon" variant="outline" className="h-8 w-8" onClick={() => changeQuantity(line.productId, line.unit, 1)}>+</Button></div><Button size="sm" variant="ghost" onClick={() => setCart(current => current.filter(item => !(item.productId === line.productId && item.unit === line.unit)))}>{text.remove}</Button></div></div>; })}{!cart.length ? <p className="py-7 text-center text-sm text-muted-foreground">{text.empty}</p> : <div className="mt-4 space-y-3 border-t border-border pt-4">{outlets.data?.length ? <Select value={selectedOutletId} onValueChange={setSelectedOutletId}><SelectTrigger><SelectValue placeholder={text.delivery} /></SelectTrigger><SelectContent>{outlets.data.map((outlet: any) => <SelectItem key={outlet.id} value={String(outlet.id)}>{outlet.name}</SelectItem>)}</SelectContent></Select> : null}<div className="flex justify-between font-bold"><span>{text.total}</span><span>{formatNumber(total)} {selected?.organizationCurrency}</span></div><Button className="w-full" disabled={createOrder.isPending || (outlets.data?.length ?? 0) > 1 && !selectedOutletId} onClick={() => { const operationId = clientOperationId || crypto.randomUUID(); setClientOperationId(operationId); createOrder.mutate({ ...accessInput, outletId: selectedOutletId ? Number(selectedOutletId) : undefined, clientOperationId: operationId, lines: cart }); }}>{createOrder.isPending ? text.loading : text.send}</Button></div>}</CardContent></Card>;
  const OrderList = ({ limit }: { limit?: number }) => <Card><CardContent className="divide-y divide-border p-0">{orders.data?.slice(0, limit).map((order: any) => <div key={order.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-semibold">{order.orderNumber}</p><p className="mt-1 text-xs text-muted-foreground">{text.delivery}: {order.displayStatus} · {formatNumber(Number(order.totalAmount))} {order.currencyCode}</p></div><Button variant="outline" size="sm" disabled={reorder.isPending} onClick={() => reorder.mutate({ ...accessInput, orderId: order.id })}><RefreshCw className="me-1 h-3.5 w-3.5" />{text.reorder}</Button></div>)}{!orders.data?.length ? <p className="p-6 text-center text-sm text-muted-foreground">{text.noOrders}</p> : null}</CardContent></Card>;

  return <main dir={direction} className="min-h-screen bg-[radial-gradient(circle_at_top,_hsl(var(--primary)/0.16),transparent_32rem),linear-gradient(180deg,hsl(var(--background)),hsl(var(--background)/0.93))] text-foreground"><div className="mx-auto max-w-6xl px-4 py-4 pb-28 sm:px-6 sm:py-6">
    <header className="overflow-hidden rounded-[1.7rem] border border-white/10 bg-card/90 shadow-xl shadow-black/10"><div className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-lg shadow-primary/25"><Store className="h-6 w-6" /></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Nawa Retail</p><h1 className="mt-1 text-xl font-bold sm:text-2xl">{text.title}</h1><p className="mt-1 text-sm text-muted-foreground">{text.subtitle}</p></div></div><div className="w-full sm:w-[290px]"><Label className="mb-1.5 block text-xs text-muted-foreground">{text.supplier}</Label><Select value={accessId} onValueChange={setAccessId}><SelectTrigger className="bg-background/60"><SelectValue placeholder={text.choose} /></SelectTrigger><SelectContent>{accesses.data?.map((item: any) => <SelectItem key={item.id} value={String(item.id)}>{item.organizationName} · {item.customerName}</SelectItem>)}</SelectContent></Select></div></div>{selected ? <nav className="flex gap-1 overflow-x-auto border-t border-white/10 bg-muted/20 px-3 py-2">{tabs.map(tab => { const Icon = tab.icon; return <Button key={tab.id} variant={activeTab === tab.id ? "default" : "ghost"} size="sm" className="shrink-0 rounded-xl" onClick={() => setActiveTab(tab.id)}><Icon className="me-1.5 h-4 w-4" />{tab.label}{tab.id === "cart" && cart.length ? <span className="ms-1 rounded-full bg-background/20 px-1.5 text-[10px]">{cart.length}</span> : null}</Button>; })}</nav> : null}</header>
    {accesses.isLoading ? <Card className="mt-5"><CardContent className="p-6 text-sm text-muted-foreground">{text.loading}</CardContent></Card> : !accesses.data?.length ? <Card className="mt-5"><CardContent className="p-8 text-center text-sm text-muted-foreground"><Building2 className="mx-auto mb-3 h-8 w-8 text-primary" />{text.noAccess}</CardContent></Card> : selected ? <>
      <section className="mt-5 grid gap-3 sm:grid-cols-3"><Card className="border-primary/25 bg-primary/10"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{text.activeOrders}</p><p className="mt-2 text-2xl font-bold">{summary.data?.activeOrders ?? "—"}</p></CardContent></Card><Card className="border-white/10"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{text.debt}</p><p className="mt-2 text-2xl font-bold">{summary.data ? `${formatNumber(summary.data.outstandingBalance)} ${summary.data.currencyCode}` : "—"}</p></CardContent></Card><Card className="border-white/10"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{text.promotions}</p><p className="mt-2 text-2xl font-bold">{summary.data?.activePromotions ?? "—"}</p></CardContent></Card></section>
      {activeTab === "home" ? <section className="mt-5 space-y-5"><Card className="border-primary/20 bg-gradient-to-br from-primary/15 via-card to-card"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold text-primary">{text.supplier}</p><h2 className="mt-1 text-lg font-bold">{selected.organizationName}</h2><p className="mt-1 text-sm text-muted-foreground">{selected.customerName}</p></div><Button onClick={() => setActiveTab("catalog")}><Search className="me-1.5 h-4 w-4" />{text.browse}</Button></CardContent></Card><div className="grid gap-5 lg:grid-cols-2"><section><h2 className="mb-3 flex items-center gap-2 font-bold"><Heart className="h-4 w-4 text-primary" />{text.favorites}</h2>{favorites.data?.length ? <div className="flex gap-3 overflow-x-auto pb-2">{favorites.data.slice(0, 8).map((product: any) => <ProductCard key={product.id} product={product} compact />)}</div> : <Card><CardContent className="p-5 text-sm text-muted-foreground">{text.noFavorites}</CardContent></Card>}</section><section><h2 className="mb-3 flex items-center gap-2 font-bold"><RefreshCw className="h-4 w-4 text-primary" />{text.frequent}</h2>{frequent.data?.length ? <div className="flex gap-3 overflow-x-auto pb-2">{frequent.data.slice(0, 8).map((product: any) => <ProductCard key={product.id} product={product} compact />)}</div> : <Card><CardContent className="p-5 text-sm text-muted-foreground">{text.noOrders}</CardContent></Card>}</section></div><h2 className="flex items-center gap-2 font-bold"><Truck className="h-4 w-4 text-primary" />{text.orders}</h2><OrderList limit={5} /></section> : null}
      {activeTab === "catalog" ? <section className="mt-5"><Card><CardContent className="p-4"><div className="relative"><Search className="absolute start-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="ps-9" value={search} onChange={event => setSearch(event.target.value)} placeholder={text.search} /></div></CardContent></Card><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{catalog.data?.map((product: any) => <ProductCard key={product.id} product={product} />)}</div>{catalog.isLoading ? <p className="mt-4 text-sm text-muted-foreground">{text.loading}</p> : !catalog.data?.length ? <Card className="mt-4"><CardContent className="p-6 text-center text-sm text-muted-foreground">{text.noProducts}</CardContent></Card> : null}</section> : null}
      {activeTab === "cart" ? <section className="mt-5 max-w-xl"><CartPanel /></section> : null}
      {activeTab === "orders" ? <section className="mt-5"><OrderList /></section> : null}
      {activeTab === "documents" ? <section className="mt-5 space-y-4"><Card><CardContent className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><label className="text-xs text-muted-foreground">{text.reportMonth}<Input className="mt-1.5 w-full sm:w-44" type="month" value={reportPeriod} onChange={event => setReportPeriod(event.target.value)} /></label><div className="flex gap-2"><Button variant="outline" disabled={!monthlyReport.data} onClick={exportCsv}><FileSpreadsheet className="me-1.5 h-4 w-4" />{text.exportCsv}</Button><Button variant="outline" disabled={!monthlyReport.data} onClick={exportPdf}><Download className="me-1.5 h-4 w-4" />{text.exportPdf}</Button></div></div>{monthlyReport.data ? <div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div className="rounded-xl bg-muted/50 p-3"><p className="text-xs text-muted-foreground">{text.orders}</p><p className="mt-1 font-bold">{monthlyReport.data.summary.orderCount} · {formatNumber(monthlyReport.data.summary.orderTotal)} {monthlyReport.data.currencyCode}</p></div><div className="rounded-xl bg-muted/50 p-3"><p className="text-xs text-muted-foreground">{text.documents}</p><p className="mt-1 font-bold">{monthlyReport.data.summary.invoiceCount} · {formatNumber(monthlyReport.data.summary.invoicedTotal)} {monthlyReport.data.currencyCode}</p></div><div className="rounded-xl bg-muted/50 p-3"><p className="text-xs text-muted-foreground">{text.debt}</p><p className="mt-1 font-bold">{formatNumber(monthlyReport.data.summary.outstandingBalance)} {monthlyReport.data.currencyCode}</p></div></div> : <p className="mt-4 text-sm text-muted-foreground">{monthlyReport.isLoading ? text.loading : text.noDocuments}</p>}</CardContent></Card><Card><CardContent className="divide-y divide-border p-0">{documents.data?.map((document: any) => <div key={document.id} className="flex items-center justify-between gap-3 p-4"><div className="flex min-w-0 items-center gap-3"><ReceiptText className="h-5 w-5 shrink-0 text-primary" /><div><p className="font-semibold">{document.invoiceNumber}</p><p className="mt-1 text-xs text-muted-foreground">{text.debt}: {formatNumber(Number(document.grandTotal) - Number(document.amountPaid))} {document.currencyCode}</p></div></div><span className="text-xs text-muted-foreground">{document.status}</span></div>)}{!documents.data?.length ? <p className="p-6 text-center text-sm text-muted-foreground">{text.noDocuments}</p> : null}</CardContent></Card></section> : null}
      {cart.length && activeTab !== "cart" ? <div className="fixed inset-x-4 bottom-4 z-30 mx-auto flex max-w-md items-center justify-between gap-3 rounded-2xl border border-primary/30 bg-card/95 p-3 shadow-2xl backdrop-blur"><div><p className="text-xs text-muted-foreground">{cart.reduce((sum, line) => sum + line.quantity, 0)} {text.items}</p><p className="font-bold">{formatNumber(total)} {selected.organizationCurrency}</p></div><Button onClick={() => setActiveTab("cart")}><ShoppingCart className="me-1.5 h-4 w-4" />{text.cart}</Button></div> : null}
    </> : null}
  </div></main>;
}
