import DashboardLayout from "@/components/DashboardLayout";
import { DocumentPreviewDownloadButton } from "@/components/DocumentPreviewDownloadButton";
import { ExchangeRatesPanel } from "@/components/ExchangeRatesPanel";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/contexts/LanguageContext";
import { useTheme } from "@/contexts/ThemeContext";
import { formatOrganizationCurrency, formatOrganizationDate } from "@/lib/formatting";
import { trpc } from "@/lib/trpc";
import { Building2, CalendarDays, ChevronLeft, Languages, Loader2, Palette, Printer, RefreshCw, Route, Settings2, Type, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const sections = [
  ["organization", Building2], ["language", Languages], ["currencies", WalletCards], ["exchangeRates", RefreshCw], ["dateAndNumbers", CalendarDays], ["appearance", Palette], ["typography", Type], ["moduleView", Route], ["printing", Printer], ["branches", Settings2],
] as const;
type SectionKey = (typeof sections)[number][0];
type DocumentDraft = { paperSize: "A4" | "A5" | "thermal"; headerText: string; footerText: string; legalInfo: string; showSignature: boolean };

function Placeholder({ title, text }: { title: string; text: string }) {
  return <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-8 text-muted-foreground">{text}</p></div>;
}

export default function SettingsPage() {
  const { language, setLanguage, t } = useLanguage();
  const { preferences, updatePreferences, resetPreferences } = useTheme();
  const [active, setActive] = useState<SectionKey>("organization");
  const [documentDraft, setDocumentDraft] = useState<DocumentDraft>({ paperSize: "A4", headerText: "", footerText: "", legalInfo: "", showSignature: true });
  const userPrefs = trpc.erp.preferences.user.useQuery();
  const organizationPrefs = trpc.erp.preferences.organization.useQuery();
  const catalog = trpc.erp.preferences.currencyCatalog.useQuery();
  const activeCurrencies = trpc.erp.preferences.currencies.useQuery();
  const saveUser = trpc.erp.preferences.saveUser.useMutation({ onSuccess: () => toast.success(t("saved")) });
  const saveOrganization = trpc.erp.preferences.saveOrganization.useMutation({ onSuccess: () => { toast.success(t("saved")); organizationPrefs.refetch(); } });
  const saveCurrency = trpc.erp.preferences.saveCurrency.useMutation({ onSuccess: () => { activeCurrencies.refetch(); organizationPrefs.refetch(); } });
  const settings = organizationPrefs.data;

  useEffect(() => {
    if (!userPrefs.data) return;
    setLanguage(userPrefs.data.language);
    updatePreferences({ themeMode: userPrefs.data.themeMode, sidebarMode: userPrefs.data.sidebarMode, density: userPrefs.data.density, fontFamily: userPrefs.data.fontFamily as typeof preferences.fontFamily, fontScale: userPrefs.data.fontScale, numeralStyle: userPrefs.data.numeralStyle, accentColor: userPrefs.data.accentColor as typeof preferences.accentColor, radiusPreset: userPrefs.data.radiusPreset, moduleViewMode: userPrefs.data.moduleViewMode });
  }, [userPrefs.data]);
  useEffect(() => {
    if (!settings) return;
    const source = settings.documentSettings;
    setDocumentDraft({ paperSize: source.paperSize, headerText: source.headerText ?? "", footerText: source.footerText ?? "", legalInfo: source.legalInfo ?? "", showSignature: source.showSignature ?? true });
    const format = { ...settings }; delete (format as { documentSettings?: unknown }).documentSettings;
    localStorage.setItem("nawa-organization-format", JSON.stringify(format)); window.dispatchEvent(new Event("nawa-organization-format"));
  }, [settings]);

  const previewSettings = useMemo(() => ({ currencyCode: settings?.currencyCode ?? "DZD", currencySymbolPosition: settings?.currencySymbolPosition ?? "after", decimalPlaces: settings?.decimalPlaces ?? 2, decimalSeparator: settings?.decimalSeparator ?? "dot", thousandsSeparator: settings?.thousandsSeparator ?? "comma", dateFormat: settings?.dateFormat ?? "DD/MM/YYYY", timeZone: settings?.timeZone ?? "Africa/Algiers", numeralStyle: preferences.numeralStyle }), [settings, preferences.numeralStyle]);
  const previewData = { direction: language === "ar" ? "rtl" as const : "ltr" as const, title: documentDraft.headerText || t("documentPreviewTitle"), date: formatOrganizationDate(new Date(), previewSettings), documentLabel: t("document"), amount: formatOrganizationCurrency(123456.75, previewSettings), footer: documentDraft.footerText || documentDraft.legalInfo, signatureLabel: documentDraft.showSignature ? t("signature") : undefined };
  const saveAppearance = (next: Partial<typeof preferences>) => { updatePreferences(next); saveUser.mutate(next); };

  const languagePanel = <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("language")}</h2><div className="mt-6 grid gap-3 sm:grid-cols-3">{(["ar", "fr", "en"] as const).map(code => <Button key={code} variant={language === code ? "default" : "outline"} onClick={() => { setLanguage(code); saveUser.mutate({ language: code }); }}>{code === "ar" ? "العربية" : code === "fr" ? "Français" : "English"}</Button>)}</div></div>;
  const appearancePanel = <div className="grid gap-5 xl:grid-cols-2"><div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("appearance")}</h2><div className="mt-6 space-y-4"><div className="flex gap-2">{(["light", "dark", "system"] as const).map(mode => <Button key={mode} variant={preferences.themeMode === mode ? "default" : "outline"} onClick={() => saveAppearance({ themeMode: mode })}>{t(mode)}</Button>)}</div><label className="block text-sm text-slate-200">{t("numeralStyle")}<select value={preferences.numeralStyle} onChange={event => saveAppearance({ numeralStyle: event.target.value as "western" | "arabic_indic" })} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option value="western">{t("westernDigits")}</option><option value="arabic_indic">{t("arabicIndicDigits")}</option></select></label><Button variant="outline" onClick={() => { resetPreferences(); saveUser.mutate({ themeMode: "dark", numeralStyle: "western" }); }}>{t("resetAppearance")}</Button></div></div><div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("livePreview")}</h2><p className="mt-5 text-sm text-muted-foreground">{t("totalSales")}</p><p className="mt-2 text-2xl font-bold text-white">{formatOrganizationCurrency(123456.75, previewSettings)}</p><p className="mt-5 text-sm text-muted-foreground">{formatOrganizationDate(new Date("2026-08-14"), previewSettings)}</p></div></div>;
  const datePanel = <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("dateAndNumbers")}</h2>{settings ? <div className="mt-6 grid gap-4 md:grid-cols-2"><label>{t("dateFormat")}<select value={settings.dateFormat} onChange={event => saveOrganization.mutate({ dateFormat: event.target.value as "DD/MM/YYYY" | "MM/DD/YYYY" | "YYYY-MM-DD" })} className="mt-2 h-10 w-full rounded-xl bg-white/[.04] px-3"><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label>{t("timeFormat")}<select value={settings.timeFormat} onChange={event => saveOrganization.mutate({ timeFormat: event.target.value as "12h" | "24h" })} className="mt-2 h-10 w-full rounded-xl bg-white/[.04] px-3"><option value="24h">24h</option><option value="12h">12h</option></select></label><label>{t("timeZone")}<Input defaultValue={settings.timeZone} onBlur={event => saveOrganization.mutate({ timeZone: event.target.value })} className="mt-2" /></label><label>{t("firstDay")}<select value={settings.firstDayOfWeek} onChange={event => saveOrganization.mutate({ firstDayOfWeek: event.target.value as "monday" | "sunday" | "saturday" })} className="mt-2 h-10 w-full rounded-xl bg-white/[.04] px-3"><option value="monday">{t("monday")}</option><option value="sunday">{t("sunday")}</option><option value="saturday">{t("saturday")}</option></select></label><label>{t("decimalSeparator")}<select value={settings.decimalSeparator} onChange={event => saveOrganization.mutate({ decimalSeparator: event.target.value as "dot" | "comma" })} className="mt-2 h-10 w-full rounded-xl bg-white/[.04] px-3"><option value="dot">.</option><option value="comma">,</option></select></label><label>{t("thousandsSeparator")}<select value={settings.thousandsSeparator} onChange={event => saveOrganization.mutate({ thousandsSeparator: event.target.value as "comma" | "dot" | "space" })} className="mt-2 h-10 w-full rounded-xl bg-white/[.04] px-3"><option value="comma">,</option><option value="dot">.</option><option value="space">{t("space")}</option></select></label></div> : <Loader2 className="mt-6 animate-spin" />}</div>;
  const currencyPanel = <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("currencies")}</h2><p className="mt-2 text-sm text-muted-foreground">{t("baseCurrency")}: {settings?.currencyCode ?? "…"}</p><div className="mt-6 grid gap-3 md:grid-cols-3">{catalog.data?.map(currency => { const current = activeCurrencies.data?.find(item => item.currencyCode === currency.code); return <button key={currency.code} onClick={() => saveCurrency.mutate({ currencyCode: currency.code, symbol: currency.symbol, decimalPlaces: currency.decimalPlaces, displayStyle: "symbol", status: current?.status === "active" ? "inactive" : "active", isBase: currency.code === settings?.currencyCode ? "yes" : "no" })} className="rounded-2xl border border-white/10 bg-white/[.025] p-4 text-start"><b>{currency.code} · {currency.symbol}</b><p className="mt-2 text-xs text-muted-foreground">{currency.names[language]}</p></button>; })}</div></div>;
  const printingPanel = <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("documentTemplate")}</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><label>{t("paperSize")}<select value={documentDraft.paperSize} onChange={event => setDocumentDraft(current => ({ ...current, paperSize: event.target.value as DocumentDraft["paperSize"] }))} className="mt-2 h-10 w-full rounded-xl bg-white/[.04] px-3"><option>A4</option><option>A5</option><option value="thermal">{t("thermalPaper")}</option></select></label><label>{t("header")}<Input value={documentDraft.headerText} onChange={event => setDocumentDraft(current => ({ ...current, headerText: event.target.value }))} className="mt-2" /></label><label>{t("footer")}<Input value={documentDraft.footerText} onChange={event => setDocumentDraft(current => ({ ...current, footerText: event.target.value }))} className="mt-2" /></label><label>{t("legalInfo")}<Input value={documentDraft.legalInfo} onChange={event => setDocumentDraft(current => ({ ...current, legalInfo: event.target.value }))} className="mt-2" /></label></div><div className="mt-6 flex flex-wrap gap-3"><Button onClick={() => saveOrganization.mutate({ documentSettings: documentDraft })}>{t("save")}</Button><DocumentPreviewDownloadButton label={t("printPreview")} filename={`nawa-${language}-${new Date().toISOString().slice(0, 10)}.html`} data={previewData} /></div></div><div className="rounded-3xl bg-white p-7 text-slate-900 shadow-2xl"><p className="text-sm font-bold">{previewData.title}</p><p className="mt-2 text-xs text-slate-500">{previewData.date}</p><div className="my-7 border-y py-4"><p>{previewData.documentLabel}</p><p className="mt-2 text-lg font-bold">{previewData.amount}</p></div><p className="text-xs text-slate-500">{previewData.footer}</p></div></div>;
  const content = active === "language" ? languagePanel : active === "appearance" ? appearancePanel : active === "currencies" ? currencyPanel : active === "exchangeRates" ? <ExchangeRatesPanel /> : active === "dateAndNumbers" ? datePanel : active === "printing" ? printingPanel : active === "moduleView" ? <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("moduleViewMode")}</h2><div className="mt-5 flex gap-3"><Button onClick={() => saveAppearance({ moduleViewMode: "classic" })}>{t("classic")}</Button><Button onClick={() => saveAppearance({ moduleViewMode: "nawa_flow" })}>{t("nawaFlow")}</Button></div></div> : <Placeholder title={t(active as never)} text={language === "ar" ? "هذه المساحة منظمة ضمن مركز الإعدادات وتحافظ على عزل المؤسسة القائم." : language === "fr" ? "Cette zone est structurée dans le centre des paramètres tout en préservant l’isolation existante." : "This area is organized in the settings center while preserving the existing tenant isolation."} />;
  return <DashboardLayout><main className="mx-auto max-w-7xl" dir={language === "ar" ? "rtl" : "ltr"}><div className="mb-7"><p className="text-sm text-primary">{t("preferences")}</p><h1 className="mt-2 text-3xl font-bold text-white">{t("settings")}</h1></div><div className="grid gap-6 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="surface rounded-3xl border p-3">{sections.map(([key, Icon]) => <button key={key} onClick={() => setActive(key)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm ${active === key ? "bg-primary text-primary-foreground" : "text-slate-300 hover:bg-white/[.05]"}`}><Icon className="h-4 w-4" /><span className="flex-1 text-start">{t(key as never)}</span>{active === key && <ChevronLeft className="h-4 w-4" />}</button>)}</aside><section>{content}</section></div></main></DashboardLayout>;
}
