import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/contexts/LanguageContext";
import { useTheme } from "@/contexts/ThemeContext";
import { formatOrganizationCurrency, formatOrganizationDate } from "@/lib/formatting";
import { trpc } from "@/lib/trpc";
import { Bell, Building2, CalendarDays, ChevronLeft, Languages, Loader2, LockKeyhole, Palette, Printer, Route, Settings2, ShieldCheck, Type, UsersRound, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const sections = [
  { key: "organization", icon: Building2 }, { key: "branches", icon: Settings2 }, { key: "users", icon: UsersRound }, { key: "language", icon: Languages }, { key: "currencies", icon: WalletCards }, { key: "dateAndNumbers", icon: CalendarDays }, { key: "appearance", icon: Palette }, { key: "typography", icon: Type }, { key: "moduleView", icon: Route }, { key: "notifications", icon: Bell }, { key: "printing", icon: Printer }, { key: "security", icon: LockKeyhole }, { key: "subscriptions", icon: ShieldCheck },
] as const;
type SectionKey = (typeof sections)[number]["key"];

function Placeholder({ title, text }: { title: string; text: string }) {
  return <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-8 text-muted-foreground">{text}</p></div>;
}

export default function SettingsPage() {
  const { language, setLanguage, t } = useLanguage();
  const { preferences, updatePreferences, resetPreferences } = useTheme();
  const [active, setActive] = useState<SectionKey>("organization");
  const [documentDraft, setDocumentDraft] = useState({ paperSize: "A4" as "A4" | "A5" | "thermal", headerText: "", footerText: "", address: "", phone: "", legalInfo: "", showSignature: true });
  const userPrefs = trpc.erp.preferences.user.useQuery();
  const organizationPrefs = trpc.erp.preferences.organization.useQuery();
  const currencyCatalog = trpc.erp.preferences.currencyCatalog.useQuery();
  const activeCurrencies = trpc.erp.preferences.currencies.useQuery();
  const saveUser = trpc.erp.preferences.saveUser.useMutation({ onSuccess: () => toast.success(t("saved")) });
  const saveOrganization = trpc.erp.preferences.saveOrganization.useMutation({ onSuccess: () => { toast.success(t("saved")); organizationPrefs.refetch(); } });
  const saveCurrency = trpc.erp.preferences.saveCurrency.useMutation({ onSuccess: () => { toast.success(t("saved")); activeCurrencies.refetch(); organizationPrefs.refetch(); } });

  useEffect(() => {
    if (!userPrefs.data) return;
    setLanguage(userPrefs.data.language);
    updatePreferences({ themeMode: userPrefs.data.themeMode, sidebarMode: userPrefs.data.sidebarMode, density: userPrefs.data.density, fontFamily: userPrefs.data.fontFamily as typeof preferences.fontFamily, fontScale: userPrefs.data.fontScale, numeralStyle: userPrefs.data.numeralStyle, accentColor: userPrefs.data.accentColor as typeof preferences.accentColor, radiusPreset: userPrefs.data.radiusPreset, moduleViewMode: userPrefs.data.moduleViewMode });
  }, [userPrefs.data]);

  useEffect(() => {
    if (!organizationPrefs.data) return;
    const documentSettings = organizationPrefs.data.documentSettings;
    setDocumentDraft({ paperSize: documentSettings.paperSize, headerText: documentSettings.headerText ?? "", footerText: documentSettings.footerText ?? "", address: documentSettings.address ?? "", phone: documentSettings.phone ?? "", legalInfo: documentSettings.legalInfo ?? "", showSignature: documentSettings.showSignature ?? true });
    const format = { ...organizationPrefs.data };
    delete (format as { documentSettings?: unknown }).documentSettings;
    localStorage.setItem("nawa-organization-format", JSON.stringify(format));
    window.dispatchEvent(new Event("nawa-organization-format"));
  }, [organizationPrefs.data]);

  const saveAppearance = (next: Partial<typeof preferences>) => { updatePreferences(next); saveUser.mutate(next); };
  const resetAppearance = () => { resetPreferences(); saveUser.mutate({ themeMode: "dark", accentColor: "gold", fontFamily: "ibm-plex", fontScale: "normal", numeralStyle: "western", density: "comfortable", radiusPreset: "rounded", sidebarMode: "expanded", moduleViewMode: "classic" }); };
  const settings = organizationPrefs.data;
  const previewSettings = useMemo(() => ({ currencyCode: settings?.currencyCode ?? "DZD", currencySymbolPosition: settings?.currencySymbolPosition ?? "after", decimalPlaces: settings?.decimalPlaces ?? 2, decimalSeparator: settings?.decimalSeparator ?? "dot", thousandsSeparator: settings?.thousandsSeparator ?? "comma", dateFormat: settings?.dateFormat ?? "DD/MM/YYYY", timeZone: settings?.timeZone ?? "Africa/Algiers", numeralStyle: preferences.numeralStyle }), [settings, preferences.numeralStyle]);

  const renderLanguage = () => <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("language")}</h2><div className="mt-6 grid gap-3 sm:grid-cols-3">{(["ar", "fr", "en"] as const).map(item => <button key={item} onClick={() => { setLanguage(item); saveUser.mutate({ language: item }); }} className={`rounded-2xl border p-5 text-start ${language === item ? "border-primary/40 bg-primary/10 text-primary" : "border-white/10 bg-white/[.025] text-slate-200"}`}><p className="font-bold">{item === "ar" ? "العربية" : item === "fr" ? "Français" : "English"}</p><p className="mt-2 text-xs text-muted-foreground">{item === "ar" ? "RTL" : "LTR"}</p></button>)}</div></div>;
  const renderAppearance = () => <div className="grid gap-5 xl:grid-cols-2"><div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("appearance")}</h2><div className="mt-6 space-y-5"><div className="flex flex-wrap gap-2">{(["light", "dark", "system"] as const).map(mode => <Button key={mode} onClick={() => saveAppearance({ themeMode: mode })} variant={preferences.themeMode === mode ? "default" : "outline"}>{t(mode)}</Button>)}</div><div className="flex gap-3">{(["gold", "blue", "emerald", "violet"] as const).map(color => <button key={color} onClick={() => saveAppearance({ accentColor: color })} className={`h-9 w-9 rounded-full ring-2 ${preferences.accentColor === color ? "ring-white" : "ring-transparent"} ${color === "gold" ? "bg-[#d9b46b]" : color === "blue" ? "bg-sky-400" : color === "emerald" ? "bg-emerald-400" : "bg-violet-400"}`} aria-label={color} />)}</div><label className="block text-sm text-slate-200">{t("numeralStyle")}<select value={preferences.numeralStyle} onChange={event => saveAppearance({ numeralStyle: event.target.value as "western" | "arabic_indic" })} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option value="western">{t("westernDigits")}</option><option value="arabic_indic">{t("arabicIndicDigits")}</option></select></label><Button variant="outline" onClick={resetAppearance} className="w-full border-white/10 bg-white/[.03] text-slate-200">{t("resetAppearance")}</Button></div></div><div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("livePreview")}</h2><div className="mt-6 rounded-2xl border border-primary/20 bg-primary/[.06] p-5"><p className="text-sm text-muted-foreground">{t("totalSales")}</p><p className="mt-2 text-2xl font-bold text-white">{formatOrganizationCurrency(123456.75, previewSettings)}</p><p className="mt-5 text-sm font-semibold text-white">{t("sampleCustomer")}</p><p className="mt-2 text-sm text-muted-foreground">{formatOrganizationDate(new Date("2026-08-14"), previewSettings)}</p></div></div></div>;
  const renderTypography = () => <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("typography")}</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><label className="text-sm text-slate-200">{t("fontFamily")}<select value={preferences.fontFamily} onChange={event => saveAppearance({ fontFamily: event.target.value as typeof preferences.fontFamily })} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option value="ibm-plex">IBM Plex Sans Arabic</option><option value="tajawal">Tajawal</option><option value="noto-arabic">Noto Sans Arabic</option><option value="inter">Inter</option><option value="system">System</option></select></label><label className="text-sm text-slate-200">{t("fontScale")}<select value={preferences.fontScale} onChange={event => saveAppearance({ fontScale: event.target.value as typeof preferences.fontScale })} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option value="small">Small</option><option value="normal">Normal</option><option value="large">Large</option><option value="extra_large">{t("extraLarge")}</option></select></label><label className="text-sm text-slate-200">{t("sidebar")}<select value={preferences.sidebarMode} onChange={event => saveAppearance({ sidebarMode: event.target.value as typeof preferences.sidebarMode })} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option value="expanded">{t("expanded")}</option><option value="compact">{t("compact")}</option><option value="collapsed">{t("collapsed")}</option></select></label></div></div>;
  const renderCurrencies = () => <div className="space-y-5"><div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("currencies")}</h2><p className="mt-2 text-sm text-muted-foreground">{t("baseCurrency")}: {settings?.currencyCode ?? "…"}</p><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{currencyCatalog.data?.map(currency => { const current = activeCurrencies.data?.find(item => item.currencyCode === currency.code); return <button key={currency.code} onClick={() => saveCurrency.mutate({ currencyCode: currency.code, symbol: currency.symbol, decimalPlaces: currency.decimalPlaces, displayStyle: "symbol", status: current?.status === "active" ? "inactive" : "active", isBase: currency.code === settings?.currencyCode ? "yes" : "no" })} className={`rounded-2xl border p-4 text-start ${current?.status === "active" ? "border-primary/35 bg-primary/[.07]" : "border-white/10 bg-white/[.025]"}`}><div className="flex items-center justify-between"><span className="font-bold text-white">{currency.code}</span><span className="text-primary">{currency.symbol}</span></div><p className="mt-2 text-xs text-muted-foreground">{currency.names[language]}</p><p className="mt-2 text-[11px] text-muted-foreground">{current?.status === "active" ? t("active") : t("activateCurrency")}</p></button>; })}</div></div><div className="surface rounded-3xl border p-7"><p className="text-sm font-semibold text-white">{t("enabledCurrencies")}</p><div className="mt-4 flex flex-wrap gap-2">{activeCurrencies.data?.filter(item => item.status === "active").map(item => <span key={item.currencyCode} className="rounded-full border border-primary/20 bg-primary/[.08] px-3 py-2 text-xs text-primary">{item.currencyCode} · {item.symbol}</span>)}</div></div></div>;
  const renderDates = () => <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("dateAndNumbers")}</h2>{settings ? <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label className="text-sm text-slate-200">{t("dateFormat")}<select defaultValue={settings.dateFormat} onChange={event => saveOrganization.mutate({ dateFormat: event.target.value as "DD/MM/YYYY" | "MM/DD/YYYY" | "YYYY-MM-DD" })} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label className="text-sm text-slate-200">{t("timeFormat")}<select defaultValue={settings.timeFormat} onChange={event => saveOrganization.mutate({ timeFormat: event.target.value as "12h" | "24h" })} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option value="24h">24h</option><option value="12h">12h</option></select></label><label className="text-sm text-slate-200">{t("timeZone")}<Input defaultValue={settings.timeZone} onBlur={event => saveOrganization.mutate({ timeZone: event.target.value })} className="mt-2 h-10 border-white/10 bg-white/[.04] text-white" /></label><label className="text-sm text-slate-200">{t("decimalSeparator")}<select defaultValue={settings.decimalSeparator} onChange={event => saveOrganization.mutate({ decimalSeparator: event.target.value as "dot" | "comma" })} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option value="dot">.</option><option value="comma">,</option></select></label><label className="text-sm text-slate-200">{t("thousandsSeparator")}<select defaultValue={settings.thousandsSeparator} onChange={event => saveOrganization.mutate({ thousandsSeparator: event.target.value as "comma" | "dot" | "space" })} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option value="comma">,</option><option value="dot">.</option><option value="space">space</option></select></label></div> : <Loader2 className="mt-8 animate-spin text-primary" />}</div>;
  const renderPrinting = () => <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("documentTemplate")}</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm text-slate-200">{t("paperSize")}<select value={documentDraft.paperSize} onChange={event => setDocumentDraft(current => ({ ...current, paperSize: event.target.value as typeof current.paperSize }))} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-white"><option>A4</option><option>A5</option><option value="thermal">Thermal</option></select></label><label className="text-sm text-slate-200">{t("header")}<Input value={documentDraft.headerText} onChange={event => setDocumentDraft(current => ({ ...current, headerText: event.target.value }))} className="mt-2 h-10 border-white/10 bg-white/[.04] text-white" /></label><label className="text-sm text-slate-200">{t("footer")}<Input value={documentDraft.footerText} onChange={event => setDocumentDraft(current => ({ ...current, footerText: event.target.value }))} className="mt-2 h-10 border-white/10 bg-white/[.04] text-white" /></label><label className="text-sm text-slate-200">{t("legalInfo")}<Input value={documentDraft.legalInfo} onChange={event => setDocumentDraft(current => ({ ...current, legalInfo: event.target.value }))} className="mt-2 h-10 border-white/10 bg-white/[.04] text-white" /></label></div><div className="mt-6 flex gap-3"><Button onClick={() => saveOrganization.mutate({ documentSettings: documentDraft })}>{t("save")}</Button><Button variant="outline" onClick={() => window.print()} className="border-white/10 bg-white/[.03] text-slate-200"><Printer className="me-2 h-4 w-4" />{t("printPreview")}</Button></div></div><div className="rounded-3xl bg-white p-7 text-slate-900 shadow-2xl"><p className="text-sm font-bold">{documentDraft.headerText || "Nawa ERP"}</p><p className="mt-2 text-xs text-slate-500">{formatOrganizationDate(new Date(), previewSettings)}</p><div className="my-7 border-y border-slate-200 py-4 text-sm"><p>{t("document")}</p><p className="mt-2 text-lg font-bold">{formatOrganizationCurrency(123456.75, previewSettings)}</p></div><p className="border-t border-slate-200 pt-3 text-xs text-slate-500">{documentDraft.footerText || documentDraft.legalInfo}</p>{documentDraft.showSignature && <div className="mt-7 border-t border-slate-300 pt-2 text-xs">{t("signature")}</div>}</div></div>;

  const content = () => {
    if (active === "language") return renderLanguage();
    if (active === "appearance") return renderAppearance();
    if (active === "typography") return renderTypography();
    if (active === "currencies") return renderCurrencies();
    if (active === "dateAndNumbers") return renderDates();
    if (active === "printing") return renderPrinting();
    if (active === "moduleView") return <div className="surface rounded-3xl border p-7"><h2 className="text-xl font-bold text-white">{t("moduleViewMode")}</h2><div className="mt-6 flex gap-3"><Button onClick={() => saveAppearance({ moduleViewMode: "classic" })} variant={preferences.moduleViewMode === "classic" ? "default" : "outline"}>{t("classic")}</Button><Button onClick={() => saveAppearance({ moduleViewMode: "nawa_flow" })} variant={preferences.moduleViewMode === "nawa_flow" ? "default" : "outline"}>{t("nawaFlow")}</Button></div></div>;
    return <Placeholder title={t(active as never)} text={language === "ar" ? "هذه المساحة منظمة ضمن مركز الإعدادات وتحافظ على عزل المؤسسة القائم." : language === "fr" ? "Cette zone est structurée dans le centre des paramètres tout en préservant l’isolation existante." : "This area is organized in the settings center while preserving the existing tenant isolation."} />;
  };

  return <DashboardLayout><main className="mx-auto max-w-7xl" dir={language === "ar" ? "rtl" : "ltr"}><div className="mb-7"><p className="text-sm text-primary">{t("preferences")}</p><h1 className="mt-2 text-3xl font-bold text-white">{t("settings")}</h1></div><div className="grid gap-6 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="surface thin-scrollbar max-h-[70vh] overflow-y-auto rounded-3xl border p-3">{sections.map(section => { const Icon = section.icon; const selected = active === section.key; return <button key={section.key} onClick={() => setActive(section.key)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm ${selected ? "bg-primary text-primary-foreground" : "text-slate-300 hover:bg-white/[.05]"}`}><Icon className="h-4 w-4" /><span className="flex-1 text-start">{t(section.key as never)}</span>{selected && <ChevronLeft className="h-4 w-4" />}</button>; })}</aside><section>{content()}</section></div></main></DashboardLayout>;
}
