import { afterEach, describe, expect, it } from "vitest";
import { and, eq } from "drizzle-orm";
import { attendanceRecords, auditLogs, employees, organizations } from "../drizzle/schema";
import { accountingJournals, accountingMappings, chartOfAccounts, fiscalPeriods, fiscalYears, journalEntries, journalLines } from "../drizzle/financeSchema";
import { allowanceTypes, commissionEntries, commissionRules, employeeAdvances, employeeAllowances, employeeContracts, payrollAdjustments, payrollPeriods, payrollRunEmployees, payslips } from "../drizzle/hrPayrollSchema";
import { createFiscalPeriod, createFiscalYear, seedDefaultChartOfAccounts } from "./finance";
import { approvePayroll, assignAllowance, calculatePayroll, createAllowanceType, createCommissionEntry, createEmployeeAdvance, createPayrollAdjustment, createPayrollPeriod } from "./payroll";
import { recordAttendance } from "./hr";
import { payPayrollPeriod, postEmployeeAdvance, postPayrollPeriod } from "./payrollPostingRules";
import { getDb } from "./db";

let organizationId: number | null = null;
 afterEach(async () => { if (!organizationId) return; const db = await getDb(); if (!db) return; const id = organizationId; await db.delete(auditLogs).where(eq(auditLogs.organizationId, id)); await db.delete(payslips).where(eq(payslips.organizationId, id)); await db.delete(payrollRunEmployees).where(eq(payrollRunEmployees.organizationId, id)); await db.delete(payrollAdjustments).where(eq(payrollAdjustments.organizationId, id)); await db.delete(employeeAdvances).where(eq(employeeAdvances.organizationId, id)); await db.delete(employeeAllowances).where(eq(employeeAllowances.organizationId, id)); await db.delete(allowanceTypes).where(eq(allowanceTypes.organizationId, id)); await db.delete(commissionEntries).where(eq(commissionEntries.organizationId, id)); await db.delete(commissionRules).where(eq(commissionRules.organizationId, id)); await db.delete(attendanceRecords).where(eq(attendanceRecords.organizationId, id)); await db.delete(employeeContracts).where(eq(employeeContracts.organizationId, id)); await db.delete(payrollPeriods).where(eq(payrollPeriods.organizationId, id)); await db.delete(employees).where(eq(employees.organizationId, id)); await db.delete(journalLines).where(eq(journalLines.organizationId, id)); await db.delete(journalEntries).where(eq(journalEntries.organizationId, id)); await db.delete(accountingMappings).where(eq(accountingMappings.organizationId, id)); await db.delete(fiscalPeriods).where(eq(fiscalPeriods.organizationId, id)); await db.delete(fiscalYears).where(eq(fiscalYears.organizationId, id)); await db.delete(accountingJournals).where(eq(accountingJournals.organizationId, id)); await db.delete(chartOfAccounts).where(eq(chartOfAccounts.organizationId, id)); await db.delete(organizations).where(eq(organizations.id, id)); organizationId = null; });

describe("تكامل الرواتب", () => {
  it("يحسب لقطة راتب حتمية ويعتمدها ويرحلها ويدفعها دون تكرار", async () => {
    const db = await getDb(); expect(db).toBeTruthy(); if (!db) return;
    const suffix = `${Date.now()}-${Math.floor(Math.random() * 100000)}`; const organization = await db.insert(organizations).values({ name: `رواتب ${suffix}`, slug: `payroll-${suffix}`, status: "active", baseCurrency: "SAR", locale: "ar-SA", monthlyBudget: "0" }); organizationId = Number(organization[0].insertId);
    await seedDefaultChartOfAccounts(organizationId); const year = await createFiscalYear(organizationId, { name: `FY-${suffix}`, startsAt: new Date("2026-01-01T00:00:00Z"), endsAt: new Date("2026-12-31T23:59:59Z") }); await createFiscalPeriod(organizationId, { fiscalYearId: year.id, name: `AUG-${suffix}`, startsAt: new Date("2026-08-01T00:00:00Z"), endsAt: new Date("2026-08-31T23:59:59Z") });
    const employee = await db.insert(employees).values({ organizationId, fullName: "موظف رواتب", employeeNumber: `EMP-${suffix}`, status: "active" }); const employeeId = Number(employee[0].insertId);
    await db.insert(employeeContracts).values({ organizationId, employeeId, contractType: "permanent", startsAt: new Date("2026-01-01T00:00:00Z"), salaryBasis: "monthly", baseSalary: "1000", absenceDeductionPerDay: "50", currencyCode: "SAR", status: "active" }); const allowance = await createAllowanceType(organizationId, 1, { code: `TRANS-${suffix}`, name: "بدل نقل", calculationType: "fixed", defaultValue: 0 }); await assignAllowance(organizationId, 1, { employeeId, allowanceTypeId: allowance.id, amount: 100, startsAt: new Date("2026-01-01T00:00:00Z") });
    const period = await createPayrollPeriod(organizationId, 1, { name: `August ${suffix}`, startsAt: new Date("2026-08-01T00:00:00Z"), endsAt: new Date("2026-08-31T23:59:59Z"), paymentDate: new Date("2026-08-25T00:00:00Z") }); await recordAttendance(organizationId, 1, { employeeId, attendanceDate: new Date("2026-08-15T00:00:00Z"), status: "absent" }); await createPayrollAdjustment(organizationId, 1, { employeeId, payrollPeriodId: period.id, adjustmentType: "bonus", amount: 50, reason: "مكافأة أداء" }); await createPayrollAdjustment(organizationId, 1, { employeeId, payrollPeriodId: period.id, adjustmentType: "deduction", amount: 30, reason: "خصم معتمد" }); await createCommissionEntry(organizationId, 1, { employeeId, sourceModule: "sales", sourceDocumentType: "invoice", sourceDocumentId: 1, occurredAt: new Date("2026-08-18T00:00:00Z"), amount: 25, currencyCode: "SAR" }); await createCommissionEntry(organizationId, 1, { employeeId, sourceModule: "sales", sourceDocumentType: "invoice", sourceDocumentId: 2, occurredAt: new Date("2026-07-31T00:00:00Z"), amount: 99, currencyCode: "SAR" }); const advance = await createEmployeeAdvance(organizationId, 1, { employeeId, occurredAt: new Date("2026-08-10T00:00:00Z"), amount: 200, currencyCode: "SAR", reason: "سلفة طارئة", recoveryMethod: "one_payroll", idempotencyKey: `advance-${suffix}` }); await postEmployeeAdvance(organizationId, 1, advance.id);
    await expect(calculatePayroll(organizationId, 1, period.id)).resolves.toMatchObject({ employees: 1, grossPay: 1175, netPay: 895 }); const [run] = await db.select().from(payrollRunEmployees).where(and(eq(payrollRunEmployees.organizationId, organizationId), eq(payrollRunEmployees.payrollPeriodId, period.id))); expect(run.snapshot).toMatchObject({ baseSalary: 1000, allowances: 100, commissions: 25, bonuses: 50, deductions: 30, absenceDeductions: 50, advanceRecovery: 200, netPay: 895 });
    await approvePayroll(organizationId, 1, period.id); await expect(postPayrollPeriod(organizationId, 1, period.id)).resolves.toMatchObject({ status: "posted", gross: 1175, recovery: 200 }); await expect(payPayrollPeriod(organizationId, 1, period.id)).resolves.toMatchObject({ status: "paid", net: 895 }); const [recoveredAdvance] = await db.select().from(employeeAdvances).where(and(eq(employeeAdvances.organizationId, organizationId), eq(employeeAdvances.id, advance.id))); expect(recoveredAdvance).toMatchObject({ status: "recovered", recoveredAmount: "200.00" }); await expect(postPayrollPeriod(organizationId, 1, period.id)).rejects.toThrow("غير معتمدة");
  }, 15_000);
});
