import { and, eq, gte, inArray, lte, sql } from "drizzle-orm";
import { attendanceRecords, auditLogs, businessParties, distributionCollections, distributionDeliveries, distributionReturns, distributionRoutes, employees, salesInvoiceItems, salesInvoices } from "../drizzle/schema";
import { allowanceTypes, commissionEntries, commissionRules, employeeAdvances, employeeAllowances, employeeContracts, overtimeEntries, payrollAdjustments, payrollPeriods, payrollRunEmployees, payslips } from "../drizzle/hrPayrollSchema";
import { getDb } from "./db";

const value = (input: unknown) => Number(input ?? 0);
const docNumber = (periodId: number, employeeId: number) => `PS-${periodId}-${employeeId}`;

export async function createPayrollPeriod(organizationId: number, actorUserId: number, input: { name: string; startsAt: Date; endsAt: Date; paymentDate?: Date }) { if (input.endsAt < input.startsAt) throw new Error("يجب أن تنتهي فترة الرواتب بعد بدايتها."); const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const result = await db.insert(payrollPeriods).values({ organizationId, name: input.name.trim(), startsAt: input.startsAt, endsAt: input.endsAt, paymentDate: input.paymentDate, createdByUserId: actorUserId, status: "draft" }); const id = Number(result[0].insertId); await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.payroll_period_created", entityType: "payroll_period", entityId: String(id), metadata: {} }); return { id, status: "draft" as const }; }

export async function createAllowanceType(organizationId: number, actorUserId: number, input: { code: string; name: string; calculationType: "fixed" | "percentage"; defaultValue: number }) { if (input.defaultValue < 0) throw new Error("قيمة البدل لا يمكن أن تكون سالبة."); const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const result = await db.insert(allowanceTypes).values({ organizationId, code: input.code.trim(), name: input.name.trim(), calculationType: input.calculationType, defaultValue: String(input.defaultValue) }); const id = Number(result[0].insertId); await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.allowance_type_created", entityType: "allowance_type", entityId: String(id), metadata: {} }); return { id }; }
export async function assignAllowance(organizationId: number, actorUserId: number, input: { employeeId: number; allowanceTypeId: number; amount: number; startsAt: Date; endsAt?: Date }) { if (input.amount < 0) throw new Error("مبلغ البدل لا يمكن أن يكون سالباً."); const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const [employee, type] = await Promise.all([db.select({ id: employees.id }).from(employees).where(and(eq(employees.id, input.employeeId), eq(employees.organizationId, organizationId))).limit(1), db.select({ id: allowanceTypes.id }).from(allowanceTypes).where(and(eq(allowanceTypes.id, input.allowanceTypeId), eq(allowanceTypes.organizationId, organizationId), eq(allowanceTypes.status, "active"))).limit(1)]); if (!employee[0] || !type[0]) throw new Error("الموظف أو نوع البدل غير متاح ضمن المؤسسة."); const result = await db.insert(employeeAllowances).values({ organizationId, employeeId: input.employeeId, allowanceTypeId: input.allowanceTypeId, amount: String(input.amount), startsAt: input.startsAt, endsAt: input.endsAt }); const id = Number(result[0].insertId); await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.allowance_assigned", entityType: "employee_allowance", entityId: String(id), metadata: { employeeId: input.employeeId } }); return { id }; }
export async function createPayrollAdjustment(organizationId: number, actorUserId: number, input: { employeeId: number; payrollPeriodId?: number; adjustmentType: "deduction" | "bonus" | "commission" | "other"; amount: number; reason: string }) { if (input.amount < 0 || input.reason.trim().length < 3) throw new Error("يتطلب التعديل مبلغاً غير سالب وسبباً واضحاً."); const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const result = await db.insert(payrollAdjustments).values({ organizationId, employeeId: input.employeeId, payrollPeriodId: input.payrollPeriodId, adjustmentType: input.adjustmentType, amount: String(input.amount), reason: input.reason.trim(), status: "approved", approvedByUserId: actorUserId, createdByUserId: actorUserId }); const id = Number(result[0].insertId); await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.payroll_adjustment_created", entityType: "payroll_adjustment", entityId: String(id), metadata: { employeeId: input.employeeId, adjustmentType: input.adjustmentType } }); return { id }; }
export async function createEmployeeAdvance(organizationId: number, actorUserId: number, input: { employeeId: number; occurredAt: Date; amount: number; currencyCode: string; reason: string; recoveryMethod: "one_payroll" | "multiple_payrolls"; idempotencyKey: string }) { if (input.amount <= 0 || input.reason.trim().length < 3) throw new Error("تتطلب السلفة مبلغاً موجباً وسبباً واضحاً."); const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const [employee] = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.id, input.employeeId), eq(employees.organizationId, organizationId))).limit(1); if (!employee) throw new Error("الموظف غير متاح ضمن المؤسسة."); const result = await db.insert(employeeAdvances).values({ organizationId, employeeId: input.employeeId, occurredAt: input.occurredAt, amount: String(input.amount), currencyCode: input.currencyCode, reason: input.reason.trim(), recoveryMethod: input.recoveryMethod, idempotencyKey: input.idempotencyKey, status: "approved", approvedByUserId: actorUserId, createdByUserId: actorUserId }); const id = Number(result[0].insertId); await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.advance_created", entityType: "employee_advance", entityId: String(id), metadata: { employeeId: input.employeeId } }); return { id, status: "approved" as const }; }
export async function createCommissionRule(organizationId: number, actorUserId: number, input: { name: string; sourceType: "sales" | "collections" | "deliveries" | "product" | "customer" | "target" | "route_performance"; calculationType: "fixed" | "percentage"; value: number }) { if (input.value < 0) throw new Error("قيمة قاعدة العمولة لا يمكن أن تكون سالبة."); const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const result = await db.insert(commissionRules).values({ organizationId, name: input.name.trim(), sourceType: input.sourceType, calculationType: input.calculationType, value: String(input.value) }); const id = Number(result[0].insertId); await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.commission_rule_created", entityType: "commission_rule", entityId: String(id), metadata: {} }); return { id }; }
export async function createCommissionEntry(organizationId: number, actorUserId: number, input: { employeeId: number; commissionRuleId?: number; sourceModule: string; sourceDocumentType: string; sourceDocumentId: number; occurredAt: Date; amount: number; currencyCode: string }) { if (input.amount < 0) throw new Error("مبلغ العمولة لا يمكن أن يكون سالباً."); const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const [employee] = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.id, input.employeeId), eq(employees.organizationId, organizationId))).limit(1); if (!employee) throw new Error("الموظف غير متاح ضمن المؤسسة."); const result = await db.insert(commissionEntries).values({ organizationId, employeeId: input.employeeId, commissionRuleId: input.commissionRuleId, sourceModule: input.sourceModule, sourceDocumentType: input.sourceDocumentType, sourceDocumentId: input.sourceDocumentId, occurredAt: input.occurredAt, amount: String(input.amount), currencyCode: input.currencyCode, status: "approved", approvedByUserId: actorUserId }); const id = Number(result[0].insertId); await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.commission_entry_created", entityType: "commission_entry", entityId: String(id), metadata: { employeeId: input.employeeId, sourceModule: input.sourceModule, sourceDocumentId: input.sourceDocumentId, occurredAt: input.occurredAt.toISOString() } }); return { id }; }

export async function createSalesCommissionFromIssuedInvoice(organizationId: number, actorUserId: number, invoiceId: number) {
  const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً.");
  const [invoice] = await db.select({ id: salesInvoices.id, customerId: salesInvoices.customerId, status: salesInvoices.status, grandTotal: salesInvoices.grandTotal, currencyCode: salesInvoices.currencyCode, issuedAt: salesInvoices.issuedAt }).from(salesInvoices).where(and(eq(salesInvoices.organizationId, organizationId), eq(salesInvoices.id, invoiceId))).limit(1);
  if (!invoice || !["issued", "partial", "paid", "overdue"].includes(invoice.status) || !invoice.customerId) return { created: false, reason: "invoice_not_eligible" as const };
  const [customer, rule] = await Promise.all([
    db.select({ employeeId: businessParties.assignedRepresentativeEmployeeId }).from(businessParties).where(and(eq(businessParties.organizationId, organizationId), eq(businessParties.id, invoice.customerId))).limit(1),
    db.select().from(commissionRules).where(and(eq(commissionRules.organizationId, organizationId), eq(commissionRules.status, "active"), eq(commissionRules.sourceType, "sales"))).limit(1),
  ]);
  const beneficiaryEmployeeId = customer[0]?.employeeId;
  if (!beneficiaryEmployeeId || !rule[0]) return { created: false, reason: "missing_attribution_or_rule" as const };
  const [employee] = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.organizationId, organizationId), eq(employees.id, beneficiaryEmployeeId))).limit(1);
  if (!employee) return { created: false, reason: "beneficiary_outside_organization" as const };
  const basis = value(invoice.grandTotal); const amount = rule[0].calculationType === "percentage" ? basis * value(rule[0].value) / 100 : value(rule[0].value);
  const [existing] = await db.select({ id: commissionEntries.id }).from(commissionEntries).where(and(eq(commissionEntries.organizationId, organizationId), eq(commissionEntries.employeeId, beneficiaryEmployeeId), eq(commissionEntries.sourceModule, "sales"), eq(commissionEntries.sourceDocumentType, "sales_invoice"), eq(commissionEntries.sourceDocumentId, invoice.id))).limit(1);
  if (existing) return { created: false, reason: "duplicate_source" as const, amount };
  try {
    await db.insert(commissionEntries).values({ organizationId, employeeId: beneficiaryEmployeeId, commissionRuleId: rule[0].id, sourceModule: "sales", sourceDocumentType: "sales_invoice", sourceDocumentId: invoice.id, occurredAt: invoice.issuedAt ?? new Date(), amount: String(amount), currencyCode: invoice.currencyCode, status: "approved", approvedByUserId: actorUserId });
  } catch (error) {
    if (String(error).toLowerCase().includes("duplicate")) return { created: false, reason: "duplicate_source" as const, amount };
    throw error;
  }
  await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.commission_auto_sales_created", entityType: "commission_entry", entityId: String(invoice.id), metadata: { invoiceId: invoice.id, employeeId: beneficiaryEmployeeId, commissionRuleId: rule[0].id, basis, rate: value(rule[0].value), amount, eventDate: (invoice.issuedAt ?? new Date()).toISOString() } });
  return { created: true, reason: "created" as const, amount };
}

export async function createCollectionCommissionFromDistributionReceipt(organizationId: number, actorUserId: number, collectionId: number) {
  const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً.");
  const [collection] = await db.select({ id: distributionCollections.id, employeeId: distributionCollections.representativeEmployeeId, amount: distributionCollections.amount, currencyCode: distributionCollections.currencyCode, collectedAt: distributionCollections.collectedAt }).from(distributionCollections).where(and(eq(distributionCollections.organizationId, organizationId), eq(distributionCollections.id, collectionId))).limit(1);
  if (!collection || !collection.employeeId || value(collection.amount) <= 0) return { created: false, reason: "collection_not_eligible" as const };
  const [rule, employee] = await Promise.all([db.select().from(commissionRules).where(and(eq(commissionRules.organizationId, organizationId), eq(commissionRules.status, "active"), eq(commissionRules.sourceType, "collections"))).limit(1), db.select({ id: employees.id }).from(employees).where(and(eq(employees.organizationId, organizationId), eq(employees.id, collection.employeeId))).limit(1)]);
  if (!rule[0] || !employee[0]) return { created: false, reason: "missing_attribution_or_rule" as const };
  const basis = value(collection.amount); const amount = rule[0].calculationType === "percentage" ? basis * value(rule[0].value) / 100 : value(rule[0].value);
  const [existing] = await db.select({ id: commissionEntries.id }).from(commissionEntries).where(and(eq(commissionEntries.organizationId, organizationId), eq(commissionEntries.employeeId, collection.employeeId), eq(commissionEntries.sourceModule, "distribution"), eq(commissionEntries.sourceDocumentType, "distribution_collection"), eq(commissionEntries.sourceDocumentId, collection.id))).limit(1);
  if (existing) return { created: false, reason: "duplicate_source" as const, amount };
  try { await db.insert(commissionEntries).values({ organizationId, employeeId: collection.employeeId, commissionRuleId: rule[0].id, sourceModule: "distribution", sourceDocumentType: "distribution_collection", sourceDocumentId: collection.id, occurredAt: collection.collectedAt, amount: String(amount), currencyCode: collection.currencyCode, status: "approved", approvedByUserId: actorUserId }); }
  catch (error) { if (String(error).toLowerCase().includes("duplicate")) return { created: false, reason: "duplicate_source" as const, amount }; throw error; }
  await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.commission_auto_collection_created", entityType: "commission_entry", entityId: String(collection.id), metadata: { collectionId: collection.id, employeeId: collection.employeeId, commissionRuleId: rule[0].id, basis, rate: value(rule[0].value), amount, eventDate: collection.collectedAt.toISOString() } });
  return { created: true, reason: "created" as const, amount };
}

export async function createDeliveryCommissionFromCompletedDelivery(organizationId: number, actorUserId: number, deliveryId: number) {
  const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً.");
  const [delivery] = await db.select({ id: distributionDeliveries.id, routeId: distributionDeliveries.routeId, salesInvoiceId: distributionDeliveries.salesInvoiceId, status: distributionDeliveries.status, deliveredAt: distributionDeliveries.deliveredAt }).from(distributionDeliveries).where(and(eq(distributionDeliveries.organizationId, organizationId), eq(distributionDeliveries.id, deliveryId))).limit(1);
  if (!delivery || delivery.status !== "full" || !delivery.salesInvoiceId) return { created: false, reason: "delivery_not_eligible" as const };
  const [route, invoice, rule] = await Promise.all([
    db.select({ representativeEmployeeId: distributionRoutes.representativeEmployeeId, driverEmployeeId: distributionRoutes.driverEmployeeId }).from(distributionRoutes).where(and(eq(distributionRoutes.organizationId, organizationId), eq(distributionRoutes.id, delivery.routeId))).limit(1),
    db.select({ grandTotal: salesInvoices.grandTotal, currencyCode: salesInvoices.currencyCode }).from(salesInvoices).where(and(eq(salesInvoices.organizationId, organizationId), eq(salesInvoices.id, delivery.salesInvoiceId))).limit(1),
    db.select().from(commissionRules).where(and(eq(commissionRules.organizationId, organizationId), eq(commissionRules.status, "active"), eq(commissionRules.sourceType, "deliveries"))).limit(1),
  ]);
  const employeeId = route[0]?.representativeEmployeeId ?? route[0]?.driverEmployeeId;
  if (!employeeId || !invoice[0] || !rule[0]) return { created: false, reason: "missing_attribution_or_rule" as const };
  const [employee, existing] = await Promise.all([
    db.select({ id: employees.id }).from(employees).where(and(eq(employees.organizationId, organizationId), eq(employees.id, employeeId))).limit(1),
    db.select({ id: commissionEntries.id }).from(commissionEntries).where(and(eq(commissionEntries.organizationId, organizationId), eq(commissionEntries.employeeId, employeeId), eq(commissionEntries.sourceModule, "distribution"), eq(commissionEntries.sourceDocumentType, "distribution_delivery"), eq(commissionEntries.sourceDocumentId, delivery.id))).limit(1),
  ]);
  const basis = value(invoice[0].grandTotal); const amount = rule[0].calculationType === "percentage" ? basis * value(rule[0].value) / 100 : value(rule[0].value);
  if (!employee[0]) return { created: false, reason: "beneficiary_outside_organization" as const };
  if (existing[0]) return { created: false, reason: "duplicate_source" as const, amount };
  try { await db.insert(commissionEntries).values({ organizationId, employeeId, commissionRuleId: rule[0].id, sourceModule: "distribution", sourceDocumentType: "distribution_delivery", sourceDocumentId: delivery.id, occurredAt: delivery.deliveredAt ?? new Date(), amount: String(amount), currencyCode: invoice[0].currencyCode, status: "approved", approvedByUserId: actorUserId }); }
  catch (error) { if (String(error).toLowerCase().includes("duplicate")) return { created: false, reason: "duplicate_source" as const, amount }; throw error; }
  await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.commission_auto_delivery_created", entityType: "commission_entry", entityId: String(delivery.id), metadata: { deliveryId: delivery.id, employeeId, commissionRuleId: rule[0].id, basis, rate: value(rule[0].value), amount, eventDate: (delivery.deliveredAt ?? new Date()).toISOString() } });
  return { created: true, reason: "created" as const, amount };
}

export async function reverseDeliveryCommissionFromReturn(organizationId: number, actorUserId: number, returnId: number) {
  const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً.");
  const [returned] = await db.select({ id: distributionReturns.id, deliveryId: distributionReturns.deliveryId, salesInvoiceId: distributionReturns.salesInvoiceId, productId: distributionReturns.productId, quantity: distributionReturns.quantity, createdAt: distributionReturns.createdAt }).from(distributionReturns).where(and(eq(distributionReturns.organizationId, organizationId), eq(distributionReturns.id, returnId))).limit(1);
  if (!returned?.deliveryId || !returned.salesInvoiceId) return { created: false, reason: "return_not_eligible" as const };
  const [original, invoice, line, existing] = await Promise.all([
    db.select().from(commissionEntries).where(and(eq(commissionEntries.organizationId, organizationId), eq(commissionEntries.sourceModule, "distribution"), eq(commissionEntries.sourceDocumentType, "distribution_delivery"), eq(commissionEntries.sourceDocumentId, returned.deliveryId))).limit(1),
    db.select({ grandTotal: salesInvoices.grandTotal }).from(salesInvoices).where(and(eq(salesInvoices.organizationId, organizationId), eq(salesInvoices.id, returned.salesInvoiceId))).limit(1),
    db.select({ quantity: salesInvoiceItems.quantity, lineTotal: salesInvoiceItems.lineTotal }).from(salesInvoiceItems).where(and(eq(salesInvoiceItems.organizationId, organizationId), eq(salesInvoiceItems.invoiceId, returned.salesInvoiceId), eq(salesInvoiceItems.productId, returned.productId))).limit(1),
    db.select({ id: commissionEntries.id }).from(commissionEntries).where(and(eq(commissionEntries.organizationId, organizationId), eq(commissionEntries.sourceModule, "distribution"), eq(commissionEntries.sourceDocumentType, "distribution_return_reversal"), eq(commissionEntries.sourceDocumentId, returned.id))).limit(1),
  ]);
  if (!original[0] || !invoice[0] || !line[0]) return { created: false, reason: "missing_original_or_basis" as const };
  const originalAmount = value(original[0].amount); const unitValue = value(line[0].quantity) > 0 ? value(line[0].lineTotal) / value(line[0].quantity) : 0; const returnedValue = unitValue * value(returned.quantity); const reversal = Math.min(originalAmount, originalAmount * (returnedValue / Math.max(value(invoice[0].grandTotal), 1)));
  if (existing[0] || reversal <= 0) return { created: false, reason: existing[0] ? "duplicate_source" as const : "zero_reversal" as const, amount: reversal };
  try { await db.insert(commissionEntries).values({ organizationId, employeeId: original[0].employeeId, commissionRuleId: original[0].commissionRuleId, sourceModule: "distribution", sourceDocumentType: "distribution_return_reversal", sourceDocumentId: returned.id, occurredAt: returned.createdAt, amount: String(-reversal), currencyCode: original[0].currencyCode, status: "approved", approvedByUserId: actorUserId }); }
  catch (error) { if (String(error).toLowerCase().includes("duplicate")) return { created: false, reason: "duplicate_source" as const, amount: reversal }; throw error; }
  await db.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.commission_delivery_reversed", entityType: "commission_entry", entityId: String(returned.id), metadata: { returnId: returned.id, deliveryId: returned.deliveryId, employeeId: original[0].employeeId, returnedValue, reversal } });
  return { created: true, reason: "reversed" as const, amount: reversal };
}
export async function calculatePayroll(organizationId: number, actorUserId: number, payrollPeriodId: number) {
  const db = await getDb();
  if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً.");
  const [period] = await db.select().from(payrollPeriods).where(and(eq(payrollPeriods.id, payrollPeriodId), eq(payrollPeriods.organizationId, organizationId))).limit(1);
  if (!period || !["draft", "calculated", "under_review"].includes(period.status)) throw new Error("لا يمكن حساب فترة رواتب معتمدة أو مرحّلة أو مدفوعة.");
  const contracts = await db.select().from(employeeContracts).where(and(eq(employeeContracts.organizationId, organizationId), eq(employeeContracts.status, "active"), lte(employeeContracts.startsAt, period.endsAt)));
  const runs = [] as { employeeId: number; contractId: number; currencyCode: string; baseSalary: number; allowances: number; overtime: number; commissions: number; bonuses: number; deductions: number; absenceDeductions: number; advanceRecovery: number; grossPay: number; netPay: number; snapshot: Record<string, unknown> }[];
  for (const contract of contracts) {
    const employeeId = contract.employeeId;
    const [allowanceRows, overtimeRows, commissionRows, adjustments, advances, attendanceRows] = await Promise.all([
      db.select({ amount: employeeAllowances.amount }).from(employeeAllowances).where(and(eq(employeeAllowances.organizationId, organizationId), eq(employeeAllowances.employeeId, employeeId), eq(employeeAllowances.status, "active"), lte(employeeAllowances.startsAt, period.endsAt), sql`(${employeeAllowances.endsAt} IS NULL OR ${employeeAllowances.endsAt} >= ${period.startsAt})`)),
      db.select({ hours: overtimeEntries.hours, multiplier: overtimeEntries.multiplier }).from(overtimeEntries).where(and(eq(overtimeEntries.organizationId, organizationId), eq(overtimeEntries.employeeId, employeeId), eq(overtimeEntries.status, "approved"), eq(overtimeEntries.payrollEligible, "yes"), gte(overtimeEntries.occurredAt, period.startsAt), lte(overtimeEntries.occurredAt, period.endsAt))),
      db.select({ amount: commissionEntries.amount }).from(commissionEntries).where(and(eq(commissionEntries.organizationId, organizationId), eq(commissionEntries.employeeId, employeeId), eq(commissionEntries.status, "approved"), gte(commissionEntries.occurredAt, period.startsAt), lte(commissionEntries.occurredAt, period.endsAt))),
      db.select().from(payrollAdjustments).where(and(eq(payrollAdjustments.organizationId, organizationId), eq(payrollAdjustments.employeeId, employeeId), eq(payrollAdjustments.status, "approved"))),
      db.select().from(employeeAdvances).where(and(eq(employeeAdvances.organizationId, organizationId), eq(employeeAdvances.employeeId, employeeId), inArray(employeeAdvances.status, ["paid", "recovered"]))),
      db.select({ status: attendanceRecords.status }).from(attendanceRecords).where(and(eq(attendanceRecords.organizationId, organizationId), eq(attendanceRecords.employeeId, employeeId), eq(attendanceRecords.status, "absent"), gte(attendanceRecords.attendanceDate, period.startsAt), lte(attendanceRecords.attendanceDate, period.endsAt))),
    ]);
    const allowances = allowanceRows.reduce((sum, row) => sum + value(row.amount), 0);
    const overtime = contract.salaryBasis === "hourly" ? overtimeRows.reduce((sum, row) => sum + value(row.hours) * value(row.multiplier) * value(contract.baseSalary), 0) : 0;
    const commissions = commissionRows.reduce((sum, row) => sum + value(row.amount), 0);
    const applicableAdjustments = adjustments.filter(row => !row.payrollPeriodId || row.payrollPeriodId === payrollPeriodId);
    const bonuses = applicableAdjustments.filter(row => ["bonus", "commission"].includes(row.adjustmentType)).reduce((sum, row) => sum + value(row.amount), 0);
    const deductions = applicableAdjustments.filter(row => row.adjustmentType === "deduction").reduce((sum, row) => sum + value(row.amount), 0);
    const outstanding = advances.reduce((sum, row) => sum + Math.max(value(row.amount) - value(row.recoveredAmount), 0), 0);
    const baseSalary = value(contract.baseSalary);
    const absenceDeductions = attendanceRows.length * value(contract.absenceDeductionPerDay);
    const grossPay = baseSalary + allowances + overtime + commissions + bonuses;
    const advanceRecovery = Math.min(outstanding, Math.max(grossPay - deductions - absenceDeductions, 0));
    const netPay = grossPay - deductions - absenceDeductions - advanceRecovery;
    const snapshot = { contractId: contract.id, salaryBasis: contract.salaryBasis, baseSalary, allowances, overtime, commissions, bonuses, deductions, absenceDeductions, absenceDays: attendanceRows.length, advanceRecovery, grossPay, netPay, calculatedAt: new Date().toISOString() };
    runs.push({ employeeId, contractId: contract.id, currencyCode: contract.currencyCode, baseSalary, allowances, overtime, commissions, bonuses, deductions, absenceDeductions, advanceRecovery, grossPay, netPay, snapshot });
  }
  await db.transaction(async tx => { for (const run of runs) await tx.insert(payrollRunEmployees).values({ organizationId, payrollPeriodId, employeeId: run.employeeId, contractId: run.contractId, currencyCode: run.currencyCode, baseSalary: String(run.baseSalary), allowances: String(run.allowances), overtime: String(run.overtime), commissions: String(run.commissions), bonuses: String(run.bonuses), deductions: String(run.deductions), absenceDeductions: String(run.absenceDeductions), advanceRecovery: String(run.advanceRecovery), grossPay: String(run.grossPay), netPay: String(run.netPay), snapshot: run.snapshot, status: "calculated" }).onDuplicateKeyUpdate({ set: { baseSalary: String(run.baseSalary), allowances: String(run.allowances), overtime: String(run.overtime), commissions: String(run.commissions), bonuses: String(run.bonuses), deductions: String(run.deductions), absenceDeductions: String(run.absenceDeductions), advanceRecovery: String(run.advanceRecovery), grossPay: String(run.grossPay), netPay: String(run.netPay), snapshot: run.snapshot, status: "calculated" } }); await tx.update(payrollPeriods).set({ status: "calculated" }).where(and(eq(payrollPeriods.id, payrollPeriodId), eq(payrollPeriods.organizationId, organizationId))); await tx.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.payroll_calculated", entityType: "payroll_period", entityId: String(payrollPeriodId), metadata: { employees: runs.length } }); });
  return { payrollPeriodId, employees: runs.length, grossPay: runs.reduce((sum, row) => sum + row.grossPay, 0), netPay: runs.reduce((sum, row) => sum + row.netPay, 0) };
}
export async function approvePayroll(organizationId: number, actorUserId: number, payrollPeriodId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const [period] = await db.select().from(payrollPeriods).where(and(eq(payrollPeriods.id, payrollPeriodId), eq(payrollPeriods.organizationId, organizationId))).limit(1); if (!period || !["calculated", "under_review"].includes(period.status)) throw new Error("يلزم حساب الرواتب قبل الاعتماد."); const runs = await db.select().from(payrollRunEmployees).where(and(eq(payrollRunEmployees.organizationId, organizationId), eq(payrollRunEmployees.payrollPeriodId, payrollPeriodId))); await db.transaction(async tx => { await tx.update(payrollPeriods).set({ status: "approved" }).where(and(eq(payrollPeriods.id, payrollPeriodId), eq(payrollPeriods.organizationId, organizationId))); await tx.update(payrollRunEmployees).set({ status: "approved" }).where(and(eq(payrollRunEmployees.organizationId, organizationId), eq(payrollRunEmployees.payrollPeriodId, payrollPeriodId))); for (const run of runs) await tx.insert(payslips).values({ organizationId, payrollRunEmployeeId: run.id, employeeId: run.employeeId, documentNumber: docNumber(payrollPeriodId, run.employeeId), snapshot: run.snapshot }).onDuplicateKeyUpdate({ set: { snapshot: run.snapshot } }); await tx.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.payroll_approved", entityType: "payroll_period", entityId: String(payrollPeriodId), metadata: { employees: runs.length } }); }); return { payrollPeriodId, status: "approved" as const }; }
export async function reopenPayroll(organizationId: number, actorUserId: number, payrollPeriodId: number, reason: string) { if (reason.trim().length < 3) throw new Error("يلزم سبب واضح لإعادة فتح الرواتب."); const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const [period] = await db.select().from(payrollPeriods).where(and(eq(payrollPeriods.id, payrollPeriodId), eq(payrollPeriods.organizationId, organizationId))).limit(1); if (!period || period.status !== "approved") throw new Error("لا يمكن إعادة فتح رواتب مرحّلة أو مدفوعة أو غير معتمدة."); await db.transaction(async tx => { await tx.update(payrollPeriods).set({ status: "draft" }).where(and(eq(payrollPeriods.id, payrollPeriodId), eq(payrollPeriods.organizationId, organizationId))); await tx.update(payrollRunEmployees).set({ status: "calculated" }).where(and(eq(payrollRunEmployees.organizationId, organizationId), eq(payrollRunEmployees.payrollPeriodId, payrollPeriodId))); await tx.insert(auditLogs).values({ organizationId, actorUserId, action: "hr.payroll_reopened", entityType: "payroll_period", entityId: String(payrollPeriodId), metadata: { reason: reason.trim() } }); }); return { payrollPeriodId, status: "draft" as const }; }

export async function getPayrollDashboard(organizationId: number) { const db = await getDb(); if (!db) throw new Error("قاعدة البيانات غير متاحة حالياً."); const periods = await db.select().from(payrollPeriods).where(eq(payrollPeriods.organizationId, organizationId)); const runs = await db.select().from(payrollRunEmployees).where(eq(payrollRunEmployees.organizationId, organizationId)); const advances = await db.select().from(employeeAdvances).where(eq(employeeAdvances.organizationId, organizationId)); const outstandingAdvances = advances.reduce((sum, row) => sum + Math.max(value(row.amount) - value(row.recoveredAmount), 0), 0); return { periods, totals: { gross: runs.reduce((sum, row) => sum + value(row.grossPay), 0), net: runs.reduce((sum, row) => sum + value(row.netPay), 0), allowances: runs.reduce((sum, row) => sum + value(row.allowances), 0), deductions: runs.reduce((sum, row) => sum + value(row.deductions) + value(row.advanceRecovery), 0), outstandingAdvances }, pendingPeriods: periods.filter(period => !["paid", "closed"].includes(period.status)).length }; }
