export const moduleViewCopy = {
  ar: {
    inventory: { title: "رؤية لحظية للمخزون", detail: "راقب مستويات الأصناف والتنبيهات والمخزون المحجوز من مساحة واحدة.", stat: "14 تنبيهاً تتطلب الإجراء", action: "إضافة صنف" },
    sales: { title: "دورة مبيعات أكثر وضوحاً", detail: "أنشئ الفواتير وتابع العملاء والطلبات والتحصيلات بصورة منظمة.", stat: "6 فواتير قيد التحصيل", action: "إنشاء فاتورة" },
    purchases: { title: "إمداد مضبوط منذ الطلب", detail: "نسّق الموردين وأوامر الشراء والاستلام قبل أن تؤثر الفجوات على البيع.", stat: "3 أوامر بانتظار الاستلام", action: "طلب شراء" },
    finance: { title: "الصورة المالية للمؤسسة", detail: "تابع التدفقات والمعاملات والأرباح والخسائر بصلاحيات واضحة.", stat: "هامش الربح 31.8%", action: "تسجيل معاملة" },
    hr: { title: "إدارة فريقك بثقة", detail: "نظّم الموظفين والحضور وكشوف الرواتب ضمن منظومة المؤسسة.", stat: "96.4% معدل الحضور", action: "إضافة موظف" },
    reports: { title: "تقارير تصنع القرار", detail: "استخدم فلاتر زمنية ورسومات قابلة للتصدير ضمن نطاق البيانات المصرح به.", stat: "12 تقريراً محفوظاً", action: "إنشاء تقرير" },
    settings: { title: "الحوكمة والصلاحيات", detail: "تحكم بالمؤسسة والوحدات والأدوار مع سجل تدقيق قابل للمراجعة.", stat: "7 وحدات ضمن الاشتراك", action: "إدارة الأدوار" },
  },
  fr: {
    inventory: { title: "Une vision instantanée du stock", detail: "Suivez les articles, alertes et réservations depuis un seul espace.", stat: "14 alertes nécessitent une action", action: "Ajouter un article" },
    sales: { title: "Un cycle de vente plus clair", detail: "Créez les factures et suivez clients, commandes et encaissements.", stat: "6 factures en recouvrement", action: "Créer une facture" },
    purchases: { title: "Un approvisionnement maîtrisé", detail: "Coordonnez fournisseurs, commandes et réceptions avant tout impact sur les ventes.", stat: "3 commandes en attente de réception", action: "Créer une commande" },
    finance: { title: "La vision financière de l’entreprise", detail: "Suivez flux, transactions, profits et pertes avec des droits maîtrisés.", stat: "Marge bénéficiaire de 31,8 %", action: "Enregistrer une transaction" },
    hr: { title: "Gérez votre équipe sereinement", detail: "Organisez collaborateurs, présence et paie dans le contexte de l’entreprise.", stat: "Taux de présence de 96,4 %", action: "Ajouter un employé" },
    reports: { title: "Des rapports pour décider", detail: "Utilisez des filtres temporels et graphiques exportables dans votre périmètre autorisé.", stat: "12 rapports enregistrés", action: "Créer un rapport" },
    settings: { title: "Gouvernance et autorisations", detail: "Pilotez l’entreprise, les modules et les rôles avec une piste d’audit.", stat: "7 modules inclus", action: "Gérer les rôles" },
  },
  en: {
    inventory: { title: "Instant inventory visibility", detail: "Monitor items, alerts, and reserved stock from one workspace.", stat: "14 alerts need action", action: "Add product" },
    sales: { title: "A clearer sales cycle", detail: "Create invoices and follow customers, orders, and collections in one place.", stat: "6 invoices in collection", action: "Create invoice" },
    purchases: { title: "Controlled procurement", detail: "Coordinate suppliers, purchase orders, and receipts before gaps affect sales.", stat: "3 orders awaiting receipt", action: "Create purchase order" },
    finance: { title: "The organization’s financial view", detail: "Track flows, transactions, profit, and loss with governed access.", stat: "31.8% profit margin", action: "Record transaction" },
    hr: { title: "Manage your team confidently", detail: "Organize employees, attendance, and payroll within your organization.", stat: "96.4% attendance rate", action: "Add employee" },
    reports: { title: "Reports that support decisions", detail: "Use time filters and exportable charts within your authorized data scope.", stat: "12 saved reports", action: "Create report" },
    settings: { title: "Governance and permissions", detail: "Manage your organization, modules, and roles with an auditable record.", stat: "7 modules in subscription", action: "Manage roles" },
  },
} as const;

export const moduleViewUiCopy = {
  ar: { backToDashboard: "العودة إلى لوحة التحكم", recentRecords: "آخر السجلات", previewFor: (module: string) => `عرض تجريبي لواجهة ${module}`, filter: "تصفية", filterApplied: "تم تطبيق الفلتر الافتراضي.", item: "العنصر", reference: "المرجع", valueOrQuantity: "القيمة / الكمية", status: "الحالة", quickSummary: "ملخص سريع", moduleMetric: "مؤشر الوحدة", emptyMetrics: "ستظهر الأرقام الفعلية هنا من بيانات المؤسسة بعد الدخول وربط الوحدة بسياق الاشتراك.", customizeModule: "تخصيص لوحة الوحدة", customizationAvailable: "يمكن تخصيص هذه المساحة لكل دور وظيفي.", fallbackNames: ["عملية تشغيلية", "سجل مراجع", "طلب قيد المعالجة", "تقرير دوري"], fallbackPeriods: ["اليوم", "أمس", "هذا الأسبوع", "هذا الشهر"], sampleProducts: ["منتج تجريبي 01", "منتج تجريبي 02", "منتج تجريبي 03", "منتج تجريبي 04"], sampleCustomers: ["عميل تجريبي 01", "عميل تجريبي 02", "عميل تجريبي 03", "عميل تجريبي 04"] },
  fr: { backToDashboard: "Retour au tableau de bord", recentRecords: "Derniers enregistrements", previewFor: (module: string) => `Aperçu de l’interface ${module}`, filter: "Filtrer", filterApplied: "Le filtre par défaut a été appliqué.", item: "Élément", reference: "Référence", valueOrQuantity: "Valeur / quantité", status: "Statut", quickSummary: "Résumé rapide", moduleMetric: "Indicateur du module", emptyMetrics: "Les chiffres réels apparaîtront ici après la connexion et le rattachement du module à l’abonnement.", customizeModule: "Personnaliser le tableau du module", customizationAvailable: "Cet espace peut être personnalisé selon chaque rôle.", fallbackNames: ["Activité opérationnelle", "Registre vérifié", "Demande en cours", "Rapport périodique"], fallbackPeriods: ["Aujourd’hui", "Hier", "Cette semaine", "Ce mois-ci"], sampleProducts: ["Produit d’exemple 01", "Produit d’exemple 02", "Produit d’exemple 03", "Produit d’exemple 04"], sampleCustomers: ["Client d’exemple 01", "Client d’exemple 02", "Client d’exemple 03", "Client d’exemple 04"] },
  en: { backToDashboard: "Back to dashboard", recentRecords: "Recent records", previewFor: (module: string) => `Preview of the ${module} interface`, filter: "Filter", filterApplied: "The default filter was applied.", item: "Item", reference: "Reference", valueOrQuantity: "Value / quantity", status: "Status", quickSummary: "Quick summary", moduleMetric: "Module metric", emptyMetrics: "Actual figures will appear here after sign-in and module subscription linkage.", customizeModule: "Customize module dashboard", customizationAvailable: "This workspace can be tailored for each role.", fallbackNames: ["Operational activity", "Reviewed record", "Request in progress", "Periodic report"], fallbackPeriods: ["Today", "Yesterday", "This week", "This month"], sampleProducts: ["Sample product 01", "Sample product 02", "Sample product 03", "Sample product 04"], sampleCustomers: ["Sample customer 01", "Sample customer 02", "Sample customer 03", "Sample customer 04"] },
} as const;
