export type AppLanguage = "ar" | "fr" | "en";

export const moduleViewCopy = {
  ar: { inventory: { title: "رؤية لحظية للمخزون", detail: "راقب مستويات الأصناف والتنبيهات والمخزون المحجوز من مساحة واحدة.", stat: "14 تنبيهاً تتطلب الإجراء", action: "إضافة صنف" }, sales: { title: "دورة مبيعات أكثر وضوحاً", detail: "أنشئ الفواتير وتابع العملاء والطلبات والتحصيلات بصورة منظمة.", stat: "6 فواتير قيد التحصيل", action: "إنشاء فاتورة" }, purchases: { title: "إمداد مضبوط منذ الطلب", detail: "نسّق الموردين وأوامر الشراء والاستلام قبل أن تؤثر الفجوات على البيع.", stat: "3 أوامر بانتظار الاستلام", action: "طلب شراء" }, finance: { title: "الصورة المالية للمؤسسة", detail: "تابع التدفقات والمعاملات والأرباح والخسائر بصلاحيات واضحة.", stat: "هامش الربح 31.8%", action: "تسجيل معاملة" }, hr: { title: "إدارة فريقك بثقة", detail: "نظّم الموظفين والحضور وكشوف الرواتب ضمن منظومة المؤسسة.", stat: "96.4% معدل الحضور", action: "إضافة موظف" }, reports: { title: "تقارير تصنع القرار", detail: "استخدم فلاتر زمنية ورسومات قابلة للتصدير ضمن نطاق البيانات المصرح به.", stat: "12 تقريراً محفوظاً", action: "إنشاء تقرير" }, settings: { title: "الحوكمة والصلاحيات", detail: "تحكم بالمؤسسة والوحدات والأدوار مع سجل تدقيق قابل للمراجعة.", stat: "7 وحدات ضمن الاشتراك", action: "إدارة الأدوار" } },
  fr: { inventory: { title: "Une vision instantanée du stock", detail: "Suivez les articles, alertes et réservations depuis un seul espace.", stat: "14 alertes nécessitent une action", action: "Ajouter un article" }, sales: { title: "Un cycle de vente plus clair", detail: "Créez les factures et suivez clients, commandes et encaissements.", stat: "6 factures en recouvrement", action: "Créer une facture" }, purchases: { title: "Un approvisionnement maîtrisé", detail: "Coordonnez fournisseurs, commandes et réceptions avant tout impact sur les ventes.", stat: "3 commandes en attente de réception", action: "Créer une commande" }, finance: { title: "La vision financière de l’entreprise", detail: "Suivez flux, transactions, profits et pertes avec des droits maîtrisés.", stat: "Marge bénéficiaire de 31,8 %", action: "Enregistrer une transaction" }, hr: { title: "Gérez votre équipe sereinement", detail: "Organisez collaborateurs, présence et paie dans le contexte de l’entreprise.", stat: "Taux de présence de 96,4 %", action: "Ajouter un employé" }, reports: { title: "Des rapports pour décider", detail: "Utilisez des filtres temporels et graphiques exportables dans votre périmètre autorisé.", stat: "12 rapports enregistrés", action: "Créer un rapport" }, settings: { title: "Gouvernance et autorisations", detail: "Pilotez l’entreprise, les modules et les rôles avec une piste d’audit.", stat: "7 modules inclus", action: "Gérer les rôles" } },
  en: { inventory: { title: "Instant inventory visibility", detail: "Monitor items, alerts, and reserved stock from one workspace.", stat: "14 alerts need action", action: "Add product" }, sales: { title: "A clearer sales cycle", detail: "Create invoices and follow customers, orders, and collections in one place.", stat: "6 invoices in collection", action: "Create invoice" }, purchases: { title: "Controlled procurement", detail: "Coordinate suppliers, purchase orders, and receipts before gaps affect sales.", stat: "3 orders awaiting receipt", action: "Create purchase order" }, finance: { title: "The organization’s financial view", detail: "Track flows, transactions, profit, and loss with governed access.", stat: "31.8% profit margin", action: "Record transaction" }, hr: { title: "Manage your team confidently", detail: "Organize employees, attendance, and payroll within your organization.", stat: "96.4% attendance rate", action: "Add employee" }, reports: { title: "Reports that support decisions", detail: "Use time filters and exportable charts within your authorized data scope.", stat: "12 saved reports", action: "Create report" }, settings: { title: "Governance and permissions", detail: "Manage your organization, modules, and roles with an auditable record.", stat: "7 modules in subscription", action: "Manage roles" } },
} as const;

export const moduleViewUiCopy = {
  ar: { backToDashboard: "العودة إلى لوحة التحكم", recentRecords: "آخر السجلات", previewFor: (module: string) => `عرض تجريبي لواجهة ${module}`, filter: "تصفية", filterApplied: "تم تطبيق الفلتر الافتراضي.", item: "العنصر", reference: "المرجع", valueOrQuantity: "القيمة / الكمية", status: "الحالة", quickSummary: "ملخص سريع", moduleMetric: "مؤشر الوحدة", emptyMetrics: "ستظهر الأرقام الفعلية هنا من بيانات المؤسسة بعد الدخول وربط الوحدة بسياق الاشتراك.", customizeModule: "تخصيص لوحة الوحدة", customizationAvailable: "يمكن تخصيص هذه المساحة لكل دور وظيفي.", fallbackNames: ["عملية تشغيلية", "سجل مراجع", "طلب قيد المعالجة", "تقرير دوري"], fallbackPeriods: ["اليوم", "أمس", "هذا الأسبوع", "هذا الشهر"], sampleProducts: ["منتج تجريبي 01", "منتج تجريبي 02", "منتج تجريبي 03", "منتج تجريبي 04"], sampleCustomers: ["عميل تجريبي 01", "عميل تجريبي 02", "عميل تجريبي 03", "عميل تجريبي 04"] },
  fr: { backToDashboard: "Retour au tableau de bord", recentRecords: "Derniers enregistrements", previewFor: (module: string) => `Aperçu de l’interface ${module}`, filter: "Filtrer", filterApplied: "Le filtre par défaut a été appliqué.", item: "Élément", reference: "Référence", valueOrQuantity: "Valeur / quantité", status: "Statut", quickSummary: "Résumé rapide", moduleMetric: "Indicateur du module", emptyMetrics: "Les chiffres réels apparaîtront ici après la connexion et le rattachement du module à l’abonnement.", customizeModule: "Personnaliser le tableau du module", customizationAvailable: "Cet espace peut être personnalisé selon chaque rôle.", fallbackNames: ["Activité opérationnelle", "Registre vérifié", "Demande en cours", "Rapport périodique"], fallbackPeriods: ["Aujourd’hui", "Hier", "Cette semaine", "Ce mois-ci"], sampleProducts: ["Produit d’exemple 01", "Produit d’exemple 02", "Produit d’exemple 03", "Produit d’exemple 04"], sampleCustomers: ["Client d’exemple 01", "Client d’exemple 02", "Client d’exemple 03", "Client d’exemple 04"] },
  en: { backToDashboard: "Back to dashboard", recentRecords: "Recent records", previewFor: (module: string) => `Preview of the ${module} interface`, filter: "Filter", filterApplied: "The default filter was applied.", item: "Item", reference: "Reference", valueOrQuantity: "Value / quantity", status: "Status", quickSummary: "Quick summary", moduleMetric: "Module metric", emptyMetrics: "Actual figures will appear here after sign-in and module subscription linkage.", customizeModule: "Customize module dashboard", customizationAvailable: "This workspace can be tailored for each role.", fallbackNames: ["Operational activity", "Reviewed record", "Request in progress", "Periodic report"], fallbackPeriods: ["Today", "Yesterday", "This week", "This month"], sampleProducts: ["Sample product 01", "Sample product 02", "Sample product 03", "Sample product 04"], sampleCustomers: ["Sample customer 01", "Sample customer 02", "Sample customer 03", "Sample customer 04"] },
} as const;

export const operationalPanelCopy = {
  ar: { title: "الوحدات التشغيلية", description: "إدارة سجلات المؤسسة الفعلية ضمن نطاق العضوية والاشتراك.", item: "العنصر", reference: "المرجع", value: "القيمة", status: "الحالة", loading: "جارٍ تحميل سجلات الوحدة...", empty: "لا توجد سجلات بعد. أضف أول سجل لهذه الوحدة.", organizationScope: "ينشأ السجل داخل المؤسسة الحالية فقط.", employeeName: "اسم الموظف", recordName: "اسم السجل", optionalReference: "مرجع اختياري", optionalValue: "القيمة (اختياري)" },
  fr: { title: "Modules opérationnels", description: "Gérez les registres réels de l’entreprise dans le périmètre de l’adhésion et de l’abonnement.", item: "Élément", reference: "Référence", value: "Valeur", status: "Statut", loading: "Chargement des registres du module…", empty: "Aucun registre pour le moment. Ajoutez le premier registre de ce module.", organizationScope: "Le registre est créé uniquement dans l’organisation actuelle.", employeeName: "Nom de l’employé", recordName: "Nom du registre", optionalReference: "Référence facultative", optionalValue: "Valeur facultative" },
  en: { title: "Operational modules", description: "Manage real organization records within membership and subscription scope.", item: "Item", reference: "Reference", value: "Value", status: "Status", loading: "Loading module records…", empty: "No records yet. Add the first record for this module.", organizationScope: "The record is created only within the current organization.", employeeName: "Employee name", recordName: "Record name", optionalReference: "Optional reference", optionalValue: "Optional value" },
} as const;

export const glossary = {
  ar: { inventory: "المخزون", sales: "المبيعات", purchases: "المشتريات", finance: "المالية والمحاسبة", hr: "الموارد البشرية", modules: "الوحدات", settings: "الإعدادات", subscriptions: "الاشتراكات" },
  fr: { inventory: "Stocks", sales: "Ventes", purchases: "Achats", finance: "Finance et comptabilité", hr: "Ressources humaines", modules: "Modules", settings: "Paramètres", subscriptions: "Abonnements" },
  en: { inventory: "Inventory", sales: "Sales", purchases: "Purchases", finance: "Finance & accounting", hr: "Human resources", modules: "Modules", settings: "Settings", subscriptions: "Subscriptions" },
} as const;

export const documentPreviewActionLabels = {
  ar: { download: "تنزيل ملف HTML", print: "طباعة أو حفظ PDF" },
  fr: { download: "Télécharger le fichier HTML", print: "Imprimer ou enregistrer en PDF" },
  en: { download: "Download HTML file", print: "Print or save as PDF" },
} as const;

export const workspaceAssistantCopy = {
  ar: { assistantDescription: "استفسر عن مؤشرات مؤسستك أو اطلب تلخيصاً عملياً. يمر كل طلب بحارس العضوية والوحدة قبل الوصول إلى أي ملخص تشغيلي.", enabledModules: "وحدات مفعلة", chatEmpty: "كيف يمكنني مساعدتك في إدارة مؤسستك اليوم؟", chatPlaceholder: "اكتب استفسارك التشغيلي هنا...", promptMetrics: "ما أهم المؤشرات التي تستحق المراجعة؟", promptCommerce: "لخّص حالة الفواتير والمخزون.", promptRecommendation: "ما التوصية التشغيلية التالية؟", scopeDescription: "يتلقى المساعد ملخصاً مخصصاً للمؤسسة الحالية فقط. لا يملك وصولاً مستقلاً إلى المؤسسات الأخرى ولا يغير السجلات التشغيلية.", practicalSuggestion: "اقتراح عملي", practicalSuggestionDetail: "ابدأ بمراجعة التنبيهات الحرجة ثم الفواتير المستحقة.", practicalSuggestionNote: "تعتمد التوصيات على البيانات المتاحة ضمن اشتراك مؤسستك وصلاحياتك.", evaluateDescription: "يفحص مؤشرات المؤسسة الحالية ويرسل لمالك المنصة عند وجود حالة حرجة." },
  fr: { assistantDescription: "Interrogez les indicateurs de votre organisation ou demandez une synthèse opérationnelle. Chaque demande passe par les contrôles d’adhésion et de module avant tout accès aux résumés.", enabledModules: "modules activés", chatEmpty: "Comment puis-je vous aider à gérer votre organisation aujourd’hui ?", chatPlaceholder: "Saisissez votre question opérationnelle…", promptMetrics: "Quels indicateurs faut-il examiner en priorité ?", promptCommerce: "Résumez la situation des factures et des stocks.", promptRecommendation: "Quelle est la prochaine recommandation opérationnelle ?", scopeDescription: "L’assistant reçoit uniquement une synthèse de l’organisation actuelle. Il n’accède pas aux autres organisations et ne modifie aucun enregistrement opérationnel.", practicalSuggestion: "Suggestion pratique", practicalSuggestionDetail: "Commencez par les alertes critiques, puis les factures dues.", practicalSuggestionNote: "Les recommandations s’appuient sur les données, l’abonnement et les autorisations disponibles.", evaluateDescription: "Analyse les indicateurs de l’organisation actuelle et informe le propriétaire de la plateforme en cas de situation critique." },
  en: { assistantDescription: "Ask about your organization’s indicators or request an operational summary. Every request passes membership and module guards before any summary is accessed.", enabledModules: "enabled modules", chatEmpty: "How can I help you manage your organization today?", chatPlaceholder: "Enter your operational question here…", promptMetrics: "Which indicators deserve priority review?", promptCommerce: "Summarize the state of invoices and inventory.", promptRecommendation: "What is the next operational recommendation?", scopeDescription: "The assistant receives a summary for the current organization only. It has no independent access to other organizations and does not modify operational records.", practicalSuggestion: "Practical suggestion", practicalSuggestionDetail: "Start by reviewing critical alerts, then due invoices.", practicalSuggestionNote: "Recommendations use only the data, subscription, and permissions available to you.", evaluateDescription: "Checks current-organization indicators and informs the platform owner when a critical condition exists." },
} as const;

export const dashboardHeroCopy = {
  ar: { welcome: "مرحباً بك، فريق النواة", title: "نبض مؤسستك في مكان واحد", description: "راقب الأداء، عالج التنبيهات، وانتقل مباشرة إلى ما يحتاج قرارك اليوم.", salesTrend: "اتجاه المبيعات", weeklyUpdate: "تحديث أسبوعي", interfacePreview: "عرض معاينة للواجهة", currentYear: "هذا العام", periodHint: "يمكن تعديل الفترة من واجهة التقارير." },
  fr: { welcome: "Bienvenue, équipe Nawa", title: "Le pouls de votre organisation en un seul endroit", description: "Suivez la performance, traitez les alertes et accédez directement aux décisions prioritaires.", salesTrend: "Tendance des ventes", weeklyUpdate: "Mise à jour hebdomadaire", interfacePreview: "Aperçu de l’interface", currentYear: "Cette année", periodHint: "La période peut être modifiée depuis les rapports." },
  en: { welcome: "Welcome, Nawa team", title: "Your organization’s pulse in one place", description: "Monitor performance, resolve alerts, and go directly to today’s priority decisions.", salesTrend: "Sales trend", weeklyUpdate: "Weekly update", interfacePreview: "Interface preview", currentYear: "This year", periodHint: "You can change the period from the reports interface." },
} as const;

export const modulesPageCopy = {
  ar: { heroTitle: "اختر المساحة التي تقود أعمالك", heroDescription: "تظهر جميع الوحدات المتاحة لخطة مؤسستك، بينما تبقى الوحدات غير المشترك بها في وضع معاينة آمن من دون وصول إلى بيانات أو إجراءات تشغيلية.", activeDescription: "الوحدة مفعلة في اشتراك مؤسستك ويمكنك الانتقال إلى مساحة العمل لإدارة سجلاتها.", upgradeRequested: "تم فتح مسار طلب الترقية لمسؤول المؤسسة.", titles: { commerce: "التجارة والمخزون", distribution: "التوزيع والأسطول", manufacturing: "التصنيع والإنتاج", finance: "المالية والمحاسبة", hr: "الموارد البشرية" } },
  fr: { heroTitle: "Choisissez l’espace qui pilote votre activité", heroDescription: "Tous les modules sont visibles. Les modules non inclus restent dans un aperçu sécurisé, sans accès aux données ni aux opérations.", activeDescription: "Ce module est actif dans votre abonnement et prêt pour les opérations.", upgradeRequested: "La demande de mise à niveau est prête pour l’administrateur.", titles: { commerce: "Commerce et stocks", distribution: "Distribution et flotte", manufacturing: "Fabrication et production", finance: "Finance et comptabilité", hr: "Ressources humaines" } },
  en: { heroTitle: "Choose the space that drives your business", heroDescription: "All modules remain visible. Modules outside your plan stay in a secure preview with no data or operational access.", activeDescription: "This module is active in your subscription and ready for operations.", upgradeRequested: "The upgrade request path is ready for your administrator.", titles: { commerce: "Commerce & inventory", distribution: "Distribution & fleet", manufacturing: "Manufacturing & production", finance: "Finance & accounting", hr: "Human resources" } },
} as const;

export const homeShellCopy = {
  ar: { assistantQuestionRequired: "اكتب استفسارك أولاً.", assistantQueryAdded: "تمت إضافة الاستفسار إلى سياق المؤسسة التجريبي." },
  fr: { assistantQuestionRequired: "Saisissez d’abord une question.", assistantQueryAdded: "La question a été ajoutée au contexte de démonstration de l’organisation." },
  en: { assistantQuestionRequired: "Enter a question first.", assistantQueryAdded: "The question was added to the organization demo context." },
} as const;

const messages = {
  ar: {
    branchCode: "رمز الفرع", branchName: "اسم الفرع", createBranch: "إضافة فرع", branchCreated: "تمت إضافة الفرع", branchCodeConflict: "رمز الفرع مستخدم بالفعل داخل المؤسسة.", branchSaveError: "تعذر حفظ الفرع حالياً. حاول مرة أخرى.", createTransaction: "تسجيل معاملة", addEmployee: "إضافة موظف", customer: "العميل", recentInvoices: "الفواتير الأخيرة", recentCommercialActivity: "آخر الحركة التجارية المسجلة", viewAll: "عرض الكل", invoiceOptions: "خيارات الفاتورة", decisionAlerts: "تنبيهات تحتاج قراراً", todayPriority: "أولوية اليوم", criticalStockAlert: "مستوى مخزون حرج", criticalStockDetail: "سكر أبيض فاخر — 75 وحدة", dueInvoiceAlert: "فاتورة مستحقة", dueInvoiceDetail: "مؤسسة الربيع — 8,720 د.ج", purchaseReceiptAlert: "طلب استلام اليوم", purchaseReceiptDetail: "أمر شراء PO-1843", inventoryHealth: "صحة المخزون", inventoryDistribution: "توزيع الأصناف حسب الحالة", details: "التفاصيل", todayMovements: "حركات اليوم", safeStock: "آمن", monitoringStock: "مراقبة", lowStock: "منخفض", criticalStock: "حرج", collecting: "قيد التحصيل",
    monday: "الاثنين", sunday: "الأحد", saturday: "السبت", space: "مسافة", barcode: "الباركود",
    exchangeHistoryTitle: "سجل أسعار الصرف", exchangeHistoryDescription: "سجل يدوي تاريخي؛ لا يغيّر أسعار المعاملات السابقة.", addExchangeRate: "إضافة سعر", quoteCurrency: "الاقتباس", exchangeRate: "السعر", filterExchangeRates: "تصفية السجل", effectiveDate: "تاريخ السريان", rateSource: "المصدر", noMatchingExchangeRates: "لا توجد أسعار صرف مطابقة", retry: "إعادة المحاولة", exportSpreadsheet: "تصدير جدول البيانات", downloadPdf: "تنزيل PDF", exchangeRateAdded: "تمت إضافة سعر الصرف", validRateRequired: "أدخل سعراً صحيحاً", refreshingExchangeRates: "جارٍ تحديث الأسعار…", exchangeRatesLoadError: "تعذر تحميل سجل أسعار الصرف.", clearFilters: "مسح المرشحات", currency: "العملة", from: "من", to: "إلى",
    exchangeRates: "أسعار الصرف", commerceSnapshot: "مؤشرات التجارة", openInvoices: "فواتير مفتوحة", openPurchaseOrders: "طلبات شراء قيد الاستلام", lowStockProducts: "أصناف منخفضة المخزون", issuedValue: "قيمة الفواتير الصادرة", recentDocuments: "أحدث المستندات", commerceAlerts: "تنبيهات التجارة", financialSummary: "ملخص مالي", currentMonth: "الشهر الحالي", revenue: "الإيرادات", expenses: "المصروفات", netProfit: "صافي الربح", totalSalesMetric: "إجمالي المبيعات", netRevenueMetric: "صافي الإيرادات", inventoryValueMetric: "قيمة المخزون", dueInvoicesMetric: "فواتير مستحقة", notificationCenter: "مركز الإشعارات", organizationAlerts: "تنبيهات المؤسسة", subscriptionModules: "الوحدات والاشتراك", organizationAccessStatus: "حالة وصول مؤسستك", noNotifications: "لا توجد إشعارات مسجلة.", enabled: "مفعلة", requestModuleUpgrade: "تواصل مع مسؤول الاشتراك لطلب ترقية الوحدة.", reportLoadError: "تعذر تحميل ملخص التقرير.", exportCsv: "تصدير CSV",
    issuedInvoices: "الفواتير الصادرة", productsCount: "عدد الأصناف", metric: "المؤشر", value: "القيمة", numeralStyle: "نمط الأرقام", westernDigits: "أرقام غربية 123", arabicIndicDigits: "أرقام عربية هندية ١٢٣", resetAppearance: "استعادة الإعدادات الافتراضية", livePreview: "معاينة مباشرة", totalSales: "إجمالي المبيعات", sampleCustomer: "اسم عميل تجريبي", extraLarge: "كبير جداً", documentFont: "خط المستند", documentFontSize: "حجم خط المستند", thermalPaper: "حراري", documentPreviewTitle: "مستند نواة", baseCurrency: "العملة الأساسية", enabledCurrencies: "العملات المفعلة", activateCurrency: "تفعيل العملة",
    signInToContinue: "سجّل الدخول للمتابعة", workspaceAccountRequired: "تتطلب مساحة المؤسسة حساباً موثقاً لحماية بياناتك.", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", aiAssistantTitle: "مساعد نواة الذكي", assistantScope: "حدود المساعد", evaluateAlerts: "تقييم التنبيهات", checkNow: "فحص الآن", assistantRequestError: "تعذر تنفيذ طلب المساعد الآن.", noCriticalAlerts: "لا توجد تنبيهات حرجة ضمن البيانات الحالية.", alertsNotified: "تم تقييم التنبيهات وإرسال إشعار لمالك المنصة.", alertsDeliveryDeferred: "تم تقييم التنبيهات، وتعذر تسليم الإشعار الخارجي مؤقتاً.", alertsEvaluationError: "تعذر تقييم التنبيهات الآن.", pageNotFound: "الصفحة غير موجودة", pageNotFoundDescription: "قد تكون الصفحة قد نُقلت أو حُذفت.", goHome: "العودة للرئيسية",
    onboardingEyebrow: "خطوة واحدة للبدء", onboardingTitle: "أنشئ مساحة مؤسستك الآمنة", onboardingDescription: "سننشئ المؤسسة وعضوية المالك والوحدات الأساسية في سياق معزول. لا نضيف منتجات أو فواتير أو سجلات افتراضية إلى بياناتك.", organizationNamePlaceholder: "اسم المؤسسة", setupOrganization: "إعداد المؤسسة", tenantIsolation: "عزل متعدد المؤسسات", tenantIsolationDescription: "لكل مؤسسة سياق وصول مستقل.", enabledModules: "وحدات مفعلة", enabledModulesDescription: "المخزون والمبيعات والمالية وغيرها.", governedAssistant: "مساعد محكوم", governedAssistantDescription: "إجابات ضمن بيانات مؤسستك فقط.",
    moduleView: "طريقة عرض الوحدات", fefo: "الأقرب انتهاءً أولاً", product: "المنتج", productName: "اسم المنتج", sku: "رمز المنتج", salePrice: "سعر البيع", createProduct: "إضافة منتج", productCreated: "تمت إضافة المنتج", warehouses: "المخازن", warehouse: "المخزن", warehouseCode: "رمز المخزن", warehouseName: "اسم المخزن", createWarehouse: "إضافة مخزن", batchManagement: "إدارة الدفعات", batchStatus: "حالة الدفعة", updateBatchStatus: "تحديث الحالة", adjustQuantity: "تسوية الكمية", quantityAdjusted: "تمت تسوية كمية الدفعة", blocked: "محجوبة", quarantined: "قيد الحجر", expired: "منتهية", inactive: "غير نشط", archived: "مؤرشف", batches: "الدفعات", salesInvoices: "فواتير المبيعات", purchaseOrders: "أوامر الشراء", createInvoice: "إنشاء فاتورة", createOrder: "إنشاء أمر شراء", issue: "إصدار", sendOrder: "إرسال", receive: "استلام", pay: "تسجيل سداد", quantity: "الكمية", unitCost: "تكلفة الوحدة", invoiceNumber: "رقم الفاتورة", orderNumber: "رقم الأمر", dueDate: "تاريخ الاستحقاق", expectedDate: "التاريخ المتوقع", draft: "مسودة", issued: "صادرة", sent: "مرسل", partial: "جزئي", paid: "مدفوعة", overdue: "متأخرة", cancelled: "ملغاة", returned: "مرتجعة", received: "مستلمة", documentCreated: "تم إنشاء المستند", documentIssued: "تم إصدار الفاتورة وصرف المخزون وفق FEFO", paymentRecorded: "تم تسجيل السداد", batchStatusUpdated: "تم تحديث حالة الدفعة", warehouseCreated: "تمت إضافة المخزن", createWarehouseFirst: "أضف مخزناً أولاً للبدء في إنشاء المستندات",
    navigation: "التنقل", dashboard: "لوحة التحكم", workspace: "مساحة العمل", modules: "الوحدات", settings: "الإعدادات", reports: "التقارير", notifications: "الإشعارات", save: "حفظ التغييرات", saved: "تم حفظ الإعدادات", cancel: "إلغاء", language: "اللغة", appearance: "المظهر", typography: "الخطوط", currencies: "العملات", dateAndNumbers: "التواريخ والأرقام", printing: "الطباعة والمستندات", security: "الأمان", organization: "المؤسسة", branches: "الفروع", users: "المستخدمون", light: "فاتح", dark: "داكن", system: "تلقائي", active: "مفعلة", locked: "مقفلة", explore: "استكشف الوحدة", upgrade: "ترقية الاشتراك", empty: "لا توجد بيانات لعرضها", loading: "جارٍ التحميل...", error: "تعذر إتمام العملية", printPreview: "معاينة الطباعة", downloadCsv: "تصدير CSV", dateFormat: "تنسيق التاريخ", timeFormat: "تنسيق الوقت", timeZone: "المنطقة الزمنية", firstDay: "أول يوم في الأسبوع", decimalSeparator: "الفاصل العشري", thousandsSeparator: "فاصل الآلاف", documentTemplate: "قالب المستند", paperSize: "مقاس الورق", header: "الترويسة", footer: "التذييل", signature: "منطقة التوقيع", themeMode: "نمط السمة", accentColor: "اللون المميز", density: "كثافة الواجهة", radius: "استدارة الحواف", fontFamily: "عائلة الخط", fontScale: "حجم الخط", sidebar: "الشريط الجانبي", comfortable: "مريح", compact: "مضغوط", expanded: "موسع", collapsed: "مطوي", companyName: "اسم المؤسسة", address: "العنوان", phone: "الهاتف", legalInfo: "البيانات القانونية", moduleHub: "مركز الوحدات", premiumModule: "وحدة احترافية", noAccess: "لا يتضمن اشتراك مؤسستك هذه الوحدة حالياً.", preferences: "التفضيلات", print: "طباعة", document: "مستند", status: "الحالة", actions: "الإجراءات", inventory: "المخزون", sales: "المبيعات", purchases: "المشتريات", finance: "المالية والمحاسبة", hr: "الموارد البشرية", moduleViewMode: "طريقة عرض الوحدات", classic: "تقليدي", nawaFlow: "Nawa Flow", businessFlowMap: "خريطة سير الأعمال", openModule: "فتح الوحدة", restricted: "مقيّدة", available: "متاحة", flowOverview: "نظرة عامة على التدفق", commerceInventory: "التجارة والمخزون", distributionFleet: "التوزيع والأسطول", manufacturingProduction: "التصنيع والإنتاج", financialAccounting: "المالية والمحاسبة", humanResources: "الموارد البشرية", internalFlow: "سير العمل الداخلي", backToFlow: "العودة إلى الخريطة", flowLockedDescription: "هذه الوحدة غير مفعلة ضمن اشتراك المؤسسة.", flowRestrictedDescription: "لا تملك الصلاحية المطلوبة لعرض تفاصيل هذه الوحدة.",
  },
  fr: {
    branchCode: "Code de succursale", branchName: "Nom de la succursale", createBranch: "Ajouter une succursale", branchCreated: "Succursale ajoutée", branchCodeConflict: "Ce code de succursale est déjà utilisé dans l’organisation.", branchSaveError: "Impossible d’enregistrer la succursale pour le moment. Réessayez.", createTransaction: "Enregistrer une transaction", addEmployee: "Ajouter un employé", customer: "Client", recentInvoices: "Factures récentes", recentCommercialActivity: "Dernière activité commerciale enregistrée", viewAll: "Voir tout", invoiceOptions: "Options de facture", decisionAlerts: "Alertes à traiter", todayPriority: "Priorité du jour", criticalStockAlert: "Niveau de stock critique", criticalStockDetail: "Sucre blanc premium — 75 unités", dueInvoiceAlert: "Facture échue", dueInvoiceDetail: "Fondation Al Rabie — 8 720 DZD", purchaseReceiptAlert: "Réception prévue aujourd’hui", purchaseReceiptDetail: "Commande PO-1843", inventoryHealth: "Santé du stock", inventoryDistribution: "Répartition des articles par état", details: "Détails", todayMovements: "Mouvements du jour", safeStock: "Sain", monitoringStock: "À surveiller", lowStock: "Faible", criticalStock: "Critique", collecting: "En recouvrement",
    monday: "Lundi", sunday: "Dimanche", saturday: "Samedi", space: "Espace", barcode: "Code-barres",
    exchangeHistoryTitle: "Historique des taux", exchangeHistoryDescription: "Historique manuel; les transactions passées ne sont jamais modifiées.", addExchangeRate: "Ajouter un taux", quoteCurrency: "Contrepartie", exchangeRate: "Taux", filterExchangeRates: "Filtrer l’historique", effectiveDate: "Date d’effet", rateSource: "Source", noMatchingExchangeRates: "Aucun taux correspondant", retry: "Réessayer", exportSpreadsheet: "Exporter le tableur", downloadPdf: "Télécharger le PDF", exchangeRateAdded: "Taux de change ajouté", validRateRequired: "Saisissez un taux valide", refreshingExchangeRates: "Mise à jour des taux…", exchangeRatesLoadError: "Impossible de charger l’historique.", clearFilters: "Effacer les filtres", currency: "Devise", from: "Du", to: "Au",
    exchangeRates: "Taux de change", commerceSnapshot: "Indicateurs commerce", openInvoices: "Factures ouvertes", openPurchaseOrders: "Achats en attente", lowStockProducts: "Produits à faible stock", issuedValue: "Valeur facturée", recentDocuments: "Documents récents", commerceAlerts: "Alertes commerciales", financialSummary: "Résumé financier", currentMonth: "Mois en cours", revenue: "Revenus", expenses: "Dépenses", netProfit: "Bénéfice net", totalSalesMetric: "Total des ventes", netRevenueMetric: "Revenu net", inventoryValueMetric: "Valeur du stock", dueInvoicesMetric: "Factures dues", notificationCenter: "Centre de notifications", organizationAlerts: "Alertes de l’organisation", subscriptionModules: "Modules et abonnement", organizationAccessStatus: "État d’accès de l’organisation", noNotifications: "Aucune notification enregistrée.", enabled: "Activé", requestModuleUpgrade: "Contactez l’administrateur de l’abonnement pour demander une mise à niveau.", reportLoadError: "Impossible de charger le résumé du rapport.", exportCsv: "Exporter CSV",
    issuedInvoices: "Factures émises", productsCount: "Nombre de produits", metric: "Indicateur", value: "Valeur", numeralStyle: "Style des chiffres", westernDigits: "Chiffres occidentaux 123", arabicIndicDigits: "Chiffres arabo-indiens ١٢٣", resetAppearance: "Réinitialiser les préférences", livePreview: "Aperçu en direct", totalSales: "Total des ventes", sampleCustomer: "Nom de client exemple", extraLarge: "Très grand", documentFont: "Police du document", documentFontSize: "Taille du document", thermalPaper: "Thermique", documentPreviewTitle: "Document Nawa", baseCurrency: "Devise de base", enabledCurrencies: "Devises activées", activateCurrency: "Activer la devise",
    signInToContinue: "Connectez-vous pour continuer", workspaceAccountRequired: "L’espace de l’organisation nécessite un compte vérifié pour protéger vos données.", signIn: "Se connecter", signOut: "Se déconnecter", aiAssistantTitle: "Assistant Nawa intelligent", assistantScope: "Périmètre de l’assistant", evaluateAlerts: "Évaluer les alertes", checkNow: "Vérifier maintenant", assistantRequestError: "Impossible d’exécuter la demande de l’assistant.", noCriticalAlerts: "Aucune alerte critique dans les données actuelles.", alertsNotified: "Les alertes ont été évaluées et le propriétaire de la plateforme a été informé.", alertsDeliveryDeferred: "Les alertes ont été évaluées, mais la notification externe est temporairement différée.", alertsEvaluationError: "Impossible d’évaluer les alertes.", pageNotFound: "Page introuvable", pageNotFoundDescription: "La page a peut-être été déplacée ou supprimée.", goHome: "Retour à l’accueil",
    onboardingEyebrow: "Une étape pour commencer", onboardingTitle: "Créez l’espace sécurisé de votre organisation", onboardingDescription: "Nous créons l’organisation, l’adhésion du propriétaire et les modules de base dans un contexte isolé. Aucune donnée fictive n’est ajoutée.", organizationNamePlaceholder: "Nom de l’organisation", setupOrganization: "Configurer l’organisation", tenantIsolation: "Isolation multi-organisations", tenantIsolationDescription: "Chaque organisation possède son propre contexte d’accès.", enabledModules: "Modules activés", enabledModulesDescription: "Stocks, ventes, finance et plus encore.", governedAssistant: "Assistant gouverné", governedAssistantDescription: "Des réponses limitées au contexte de votre organisation.",
    moduleView: "Affichage des modules", fefo: "Premier expiré, premier sorti", product: "Produit", productName: "Nom du produit", sku: "Référence produit", salePrice: "Prix de vente", createProduct: "Ajouter un produit", productCreated: "Produit ajouté", warehouses: "Entrepôts", warehouse: "Entrepôt", warehouseCode: "Code entrepôt", warehouseName: "Nom de l’entrepôt", createWarehouse: "Ajouter un entrepôt", batchManagement: "Gestion des lots", batchStatus: "Statut du lot", updateBatchStatus: "Mettre à jour le statut", adjustQuantity: "Ajuster la quantité", quantityAdjusted: "Quantité du lot ajustée", blocked: "Bloqué", quarantined: "En quarantaine", expired: "Expiré", inactive: "Inactif", archived: "Archivé", batches: "Lots", salesInvoices: "Factures de vente", purchaseOrders: "Bons de commande", createInvoice: "Créer une facture", createOrder: "Créer une commande", issue: "Émettre", sendOrder: "Envoyer", receive: "Réception", pay: "Enregistrer le règlement", quantity: "Quantité", unitCost: "Coût unitaire", invoiceNumber: "Numéro de facture", orderNumber: "Numéro de commande", dueDate: "Date d’échéance", expectedDate: "Date prévue", draft: "Brouillon", issued: "Émise", sent: "Envoyée", partial: "Partiel", paid: "Payée", overdue: "En retard", cancelled: "Annulée", returned: "Retournée", received: "Reçue", documentCreated: "Document créé", documentIssued: "Facture émise et stock sorti selon FEFO", paymentRecorded: "Règlement enregistré", batchStatusUpdated: "Statut du lot mis à jour", warehouseCreated: "Entrepôt ajouté", createWarehouseFirst: "Ajoutez d’abord un entrepôt pour créer des documents",
    inventory: "Stocks", sales: "Ventes", purchases: "Achats", finance: "Finance et comptabilité", hr: "Ressources humaines",
    navigation: "Navigation", dashboard: "Tableau de bord", workspace: "Espace de travail", modules: "Modules", settings: "Paramètres", reports: "Rapports", notifications: "Notifications", save: "Enregistrer", saved: "Paramètres enregistrés", cancel: "Annuler", language: "Langue", appearance: "Apparence", typography: "Typographie", currencies: "Devises", dateAndNumbers: "Dates et nombres", printing: "Impression et documents", security: "Sécurité", organization: "Organisation", branches: "Succursales", users: "Utilisateurs", light: "Clair", dark: "Sombre", system: "Système", active: "Actif", locked: "Verrouillé", explore: "Découvrir le module", upgrade: "Mettre à niveau", empty: "Aucune donnée à afficher", loading: "Chargement...", error: "Opération impossible", printPreview: "Aperçu avant impression", downloadCsv: "Exporter CSV", dateFormat: "Format de date", timeFormat: "Format d’heure", timeZone: "Fuseau horaire", firstDay: "Premier jour de la semaine", decimalSeparator: "Séparateur décimal", thousandsSeparator: "Séparateur des milliers", documentTemplate: "Modèle de document", paperSize: "Format du papier", header: "En-tête", footer: "Pied de page", signature: "Zone de signature", themeMode: "Mode de thème", accentColor: "Couleur d’accent", density: "Densité d’interface", radius: "Rayon des bordures", fontFamily: "Police", fontScale: "Taille du texte", sidebar: "Barre latérale", comfortable: "Confortable", compact: "Compact", expanded: "Développée", collapsed: "Réduite", companyName: "Nom de l’organisation", address: "Adresse", phone: "Téléphone", legalInfo: "Informations légales", moduleHub: "Centre des modules", premiumModule: "Module premium", noAccess: "Ce module n’est pas inclus dans votre abonnement actuel.", preferences: "Préférences", print: "Imprimer", document: "Document", status: "Statut", actions: "Actions", moduleViewMode: "Mode d’affichage des modules", classic: "Classique", nawaFlow: "Nawa Flow", businessFlowMap: "Carte des flux métier", openModule: "Ouvrir le module", restricted: "Restreint", available: "Disponible", flowOverview: "Vue d’ensemble du flux", commerceInventory: "Commerce et stocks", distributionFleet: "Distribution et flotte", manufacturingProduction: "Fabrication et production", financialAccounting: "Finance et comptabilité", humanResources: "Ressources humaines", internalFlow: "Flux interne", backToFlow: "Retour à la carte", flowLockedDescription: "Ce module n’est pas activé dans l’abonnement de l’organisation.", flowRestrictedDescription: "Vous ne disposez pas de l’autorisation requise pour afficher les détails de ce module.",
  },
  en: {
    branchCode: "Branch code", branchName: "Branch name", createBranch: "Add branch", branchCreated: "Branch added", branchCodeConflict: "This branch code is already used in the organization.", branchSaveError: "The branch could not be saved right now. Please try again.", createTransaction: "Record transaction", addEmployee: "Add employee", customer: "Customer", recentInvoices: "Recent invoices", recentCommercialActivity: "Latest recorded commercial activity", viewAll: "View all", invoiceOptions: "Invoice options", decisionAlerts: "Alerts requiring a decision", todayPriority: "Today’s priority", criticalStockAlert: "Critical stock level", criticalStockDetail: "Premium white sugar — 75 units", dueInvoiceAlert: "Invoice due", dueInvoiceDetail: "Al Rabie Foundation — DZD 8,720", purchaseReceiptAlert: "Receipt scheduled today", purchaseReceiptDetail: "Purchase order PO-1843", inventoryHealth: "Inventory health", inventoryDistribution: "Item distribution by status", details: "Details", todayMovements: "Today’s movements", safeStock: "Safe", monitoringStock: "Monitoring", lowStock: "Low", criticalStock: "Critical", collecting: "In collection",
    monday: "Monday", sunday: "Sunday", saturday: "Saturday", space: "Space", barcode: "Barcode",
    exchangeHistoryTitle: "Exchange rate history", exchangeHistoryDescription: "Manual historical ledger; it never changes past transaction rates.", addExchangeRate: "Add rate", quoteCurrency: "Quote", exchangeRate: "Rate", filterExchangeRates: "Filter history", effectiveDate: "Effective date", rateSource: "Source", noMatchingExchangeRates: "No matching exchange rates", retry: "Retry", exportSpreadsheet: "Export spreadsheet", downloadPdf: "Download PDF", exchangeRateAdded: "Exchange rate added", validRateRequired: "Enter a valid rate", refreshingExchangeRates: "Refreshing rates…", exchangeRatesLoadError: "Could not load exchange-rate history.", clearFilters: "Clear filters", currency: "Currency", from: "From", to: "To",
    exchangeRates: "Exchange rates", commerceSnapshot: "Commerce indicators", openInvoices: "Open invoices", openPurchaseOrders: "Purchase orders awaiting receipt", lowStockProducts: "Low-stock products", issuedValue: "Issued invoice value", recentDocuments: "Recent documents", commerceAlerts: "Commerce alerts", financialSummary: "Financial summary", currentMonth: "Current month", revenue: "Revenue", expenses: "Expenses", netProfit: "Net profit", totalSalesMetric: "Total sales", netRevenueMetric: "Net revenue", inventoryValueMetric: "Inventory value", dueInvoicesMetric: "Due invoices", notificationCenter: "Notification center", organizationAlerts: "Organization alerts", subscriptionModules: "Modules & subscription", organizationAccessStatus: "Your organization access status", noNotifications: "No notifications recorded.", enabled: "Enabled", requestModuleUpgrade: "Contact the subscription administrator to request a module upgrade.", reportLoadError: "Could not load the report summary.", exportCsv: "Export CSV",
    issuedInvoices: "Issued invoices", productsCount: "Product count", metric: "Metric", value: "Value", numeralStyle: "Numeral Style", westernDigits: "Western digits 123", arabicIndicDigits: "Arabic-Indic digits ١٢٣", resetAppearance: "Reset to defaults", livePreview: "Live preview", totalSales: "Total sales", sampleCustomer: "Sample customer name", extraLarge: "Extra Large", documentFont: "Document font", documentFontSize: "Document font size", thermalPaper: "Thermal", documentPreviewTitle: "Nawa document", baseCurrency: "Base currency", enabledCurrencies: "Enabled currencies", activateCurrency: "Activate currency",
    signInToContinue: "Sign in to continue", workspaceAccountRequired: "The organization workspace requires a verified account to protect your data.", signIn: "Sign in", signOut: "Sign out", aiAssistantTitle: "Nawa smart assistant", assistantScope: "Assistant boundaries", evaluateAlerts: "Evaluate alerts", checkNow: "Check now", assistantRequestError: "Could not process the assistant request.", noCriticalAlerts: "There are no critical alerts in the current data.", alertsNotified: "Alerts were evaluated and the platform owner was notified.", alertsDeliveryDeferred: "Alerts were evaluated, but external delivery is temporarily deferred.", alertsEvaluationError: "Could not evaluate alerts.", pageNotFound: "Page not found", pageNotFoundDescription: "The page may have been moved or deleted.", goHome: "Go home",
    onboardingEyebrow: "One step to get started", onboardingTitle: "Create your secure organization workspace", onboardingDescription: "We create the organization, owner membership, and core modules in an isolated context. No mock products, invoices, or records are added.", organizationNamePlaceholder: "Organization name", setupOrganization: "Set up organization", tenantIsolation: "Multi-organization isolation", tenantIsolationDescription: "Each organization has an independent access context.", enabledModules: "Enabled modules", enabledModulesDescription: "Inventory, sales, finance, and more.", governedAssistant: "Governed assistant", governedAssistantDescription: "Answers stay within your organization context.",
    moduleView: "Module view", fefo: "First Expiry, First Out", product: "Product", productName: "Product name", sku: "Product SKU", salePrice: "Sale price", createProduct: "Add product", productCreated: "Product added", warehouses: "Warehouses", warehouse: "Warehouse", warehouseCode: "Warehouse code", warehouseName: "Warehouse name", createWarehouse: "Add warehouse", batchManagement: "Batch management", batchStatus: "Batch status", updateBatchStatus: "Update status", adjustQuantity: "Adjust quantity", quantityAdjusted: "Batch quantity adjusted", blocked: "Blocked", quarantined: "Quarantined", expired: "Expired", inactive: "Inactive", archived: "Archived", batches: "Batches", salesInvoices: "Sales invoices", purchaseOrders: "Purchase orders", createInvoice: "Create invoice", createOrder: "Create order", issue: "Issue", sendOrder: "Send", receive: "Receive", pay: "Record payment", quantity: "Quantity", unitCost: "Unit cost", invoiceNumber: "Invoice number", orderNumber: "Order number", dueDate: "Due date", expectedDate: "Expected date", draft: "Draft", issued: "Issued", sent: "Sent", partial: "Partial", paid: "Paid", overdue: "Overdue", cancelled: "Cancelled", returned: "Returned", received: "Received", documentCreated: "Document created", documentIssued: "Invoice issued and stock allocated by FEFO", paymentRecorded: "Payment recorded", batchStatusUpdated: "Batch status updated", warehouseCreated: "Warehouse added", createWarehouseFirst: "Add a warehouse before creating documents",
    inventory: "Inventory", sales: "Sales", purchases: "Purchases", finance: "Finance & accounting", hr: "Human resources",
    navigation: "Navigation", dashboard: "Dashboard", workspace: "Workspace", modules: "Modules", settings: "Settings", reports: "Reports", notifications: "Notifications", save: "Save changes", saved: "Settings saved", cancel: "Cancel", language: "Language", appearance: "Appearance", typography: "Typography", currencies: "Currencies", dateAndNumbers: "Dates & numbers", printing: "Print & documents", security: "Security", organization: "Organization", branches: "Branches", users: "Users", light: "Light", dark: "Dark", system: "System", active: "Active", locked: "Locked", explore: "Explore module", upgrade: "Upgrade subscription", empty: "No data to display", loading: "Loading...", error: "Operation could not be completed", printPreview: "Print preview", downloadCsv: "Export CSV", dateFormat: "Date format", timeFormat: "Time format", timeZone: "Time zone", firstDay: "First day of week", decimalSeparator: "Decimal separator", thousandsSeparator: "Thousands separator", documentTemplate: "Document template", paperSize: "Paper size", header: "Header", footer: "Footer", signature: "Signature area", themeMode: "Theme mode", accentColor: "Accent color", density: "Interface density", radius: "Border radius", fontFamily: "Font family", fontScale: "Font scale", sidebar: "Sidebar", comfortable: "Comfortable", compact: "Compact", expanded: "Expanded", collapsed: "Collapsed", companyName: "Organization name", address: "Address", phone: "Phone", legalInfo: "Legal information", moduleHub: "Module hub", premiumModule: "Premium module", noAccess: "This module is not included in your current subscription.", preferences: "Preferences", print: "Print", document: "Document", status: "Status", actions: "Actions", moduleViewMode: "Module View Mode", classic: "Classic", nawaFlow: "Nawa Flow", businessFlowMap: "Business flow map", openModule: "Open module", restricted: "Restricted", available: "Available", flowOverview: "Flow overview", commerceInventory: "Commerce & inventory", distributionFleet: "Distribution & fleet", manufacturingProduction: "Manufacturing & production", financialAccounting: "Finance & accounting", humanResources: "Human resources", internalFlow: "Internal flow", backToFlow: "Back to map", flowLockedDescription: "This module is not active in the organization subscription.", flowRestrictedDescription: "You do not have the permission required to view this module’s details.",
  },
} as const;

export type TranslationKey = keyof typeof messages.ar;
export const translations = messages;
export function getDirection(language: AppLanguage): "rtl" | "ltr" { return language === "ar" ? "rtl" : "ltr"; }
