export type AppLanguage = "ar" | "fr" | "en";

export const glossary = {
  ar: { inventory: "المخزون", sales: "المبيعات", purchases: "المشتريات", finance: "المالية والمحاسبة", hr: "الموارد البشرية", modules: "الوحدات", settings: "الإعدادات", subscriptions: "الاشتراكات" },
  fr: { inventory: "Stocks", sales: "Ventes", purchases: "Achats", finance: "Finance et comptabilité", hr: "Ressources humaines", modules: "Modules", settings: "Paramètres", subscriptions: "Abonnements" },
  en: { inventory: "Inventory", sales: "Sales", purchases: "Purchases", finance: "Finance & accounting", hr: "Human resources", modules: "Modules", settings: "Settings", subscriptions: "Subscriptions" },
} as const;

const messages = {
ar: {
    exchangeRates: "أسعار الصرف",
    numeralStyle: "نمط الأرقام", westernDigits: "أرقام غربية 123", arabicIndicDigits: "أرقام عربية هندية ١٢٣", resetAppearance: "استعادة الإعدادات الافتراضية", livePreview: "معاينة مباشرة", totalSales: "إجمالي المبيعات", sampleCustomer: "اسم عميل تجريبي", extraLarge: "كبير جداً", documentFont: "خط المستند", documentFontSize: "حجم خط المستند", baseCurrency: "العملة الأساسية", enabledCurrencies: "العملات المفعلة", activateCurrency: "تفعيل العملة",
    signInToContinue: "سجّل الدخول للمتابعة", workspaceAccountRequired: "تتطلب مساحة المؤسسة حساباً موثقاً لحماية بياناتك.", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج",
    onboardingEyebrow: "خطوة واحدة للبدء", onboardingTitle: "أنشئ مساحة مؤسستك الآمنة", onboardingDescription: "سننشئ المؤسسة وعضوية المالك والوحدات الأساسية في سياق معزول. لا نضيف منتجات أو فواتير أو سجلات افتراضية إلى بياناتك.", organizationNamePlaceholder: "اسم المؤسسة", setupOrganization: "إعداد المؤسسة", tenantIsolation: "عزل متعدد المؤسسات", tenantIsolationDescription: "لكل مؤسسة سياق وصول مستقل.", enabledModules: "وحدات مفعلة", enabledModulesDescription: "المخزون والمبيعات والمالية وغيرها.", governedAssistant: "مساعد محكوم", governedAssistantDescription: "إجابات ضمن بيانات مؤسستك فقط.",
    moduleView: "طريقة عرض الوحدات", fefo: "الأقرب انتهاءً أولاً",
    navigation: "التنقل", dashboard: "لوحة التحكم", workspace: "مساحة العمل", modules: "الوحدات", settings: "الإعدادات", reports: "التقارير", notifications: "الإشعارات", save: "حفظ التغييرات", saved: "تم حفظ الإعدادات", cancel: "إلغاء", language: "اللغة", appearance: "المظهر", typography: "الخطوط", currencies: "العملات", dateAndNumbers: "التواريخ والأرقام", printing: "الطباعة والمستندات", security: "الأمان", organization: "المؤسسة", branches: "الفروع", users: "المستخدمون", light: "فاتح", dark: "داكن", system: "تلقائي", active: "مفعلة", locked: "مقفلة", explore: "استكشف الوحدة", upgrade: "ترقية الاشتراك", empty: "لا توجد بيانات لعرضها", loading: "جارٍ التحميل...", error: "تعذر إتمام العملية", printPreview: "معاينة الطباعة", downloadCsv: "تصدير CSV", dateFormat: "تنسيق التاريخ", timeFormat: "تنسيق الوقت", timeZone: "المنطقة الزمنية", firstDay: "أول يوم في الأسبوع", decimalSeparator: "الفاصل العشري", thousandsSeparator: "فاصل الآلاف", documentTemplate: "قالب المستند", paperSize: "مقاس الورق", header: "الترويسة", footer: "التذييل", signature: "منطقة التوقيع", themeMode: "نمط السمة", accentColor: "اللون المميز", density: "كثافة الواجهة", radius: "استدارة الحواف", fontFamily: "عائلة الخط", fontScale: "حجم الخط", sidebar: "الشريط الجانبي", comfortable: "مريح", compact: "مضغوط", expanded: "موسع", collapsed: "مطوي", companyName: "اسم المؤسسة", address: "العنوان", phone: "الهاتف", legalInfo: "البيانات القانونية", moduleHub: "مركز الوحدات", premiumModule: "وحدة احترافية", noAccess: "لا يتضمن اشتراك مؤسستك هذه الوحدة حالياً.", preferences: "التفضيلات", print: "طباعة", document: "مستند", status: "الحالة", actions: "الإجراءات", inventory: "المخزون", sales: "المبيعات", purchases: "المشتريات", finance: "المالية والمحاسبة", hr: "الموارد البشرية", moduleViewMode: "طريقة عرض الوحدات", classic: "تقليدي", nawaFlow: "Nawa Flow", businessFlowMap: "خريطة سير الأعمال", openModule: "فتح الوحدة", restricted: "مقيّدة", available: "متاحة", flowOverview: "نظرة عامة على التدفق", commerceInventory: "التجارة والمخزون", distributionFleet: "التوزيع والأسطول", manufacturingProduction: "التصنيع والإنتاج", financialAccounting: "المالية والمحاسبة", humanResources: "الموارد البشرية", internalFlow: "سير العمل الداخلي", backToFlow: "العودة إلى الخريطة", flowLockedDescription: "هذه الوحدة غير مفعلة ضمن اشتراك المؤسسة.", flowRestrictedDescription: "لا تملك الصلاحية المطلوبة لعرض تفاصيل هذه الوحدة.",
  },
fr: {
    exchangeRates: "Taux de change",
    numeralStyle: "Style des chiffres", westernDigits: "Chiffres occidentaux 123", arabicIndicDigits: "Chiffres arabo-indiens ١٢٣", resetAppearance: "Réinitialiser les préférences", livePreview: "Aperçu en direct", totalSales: "Total des ventes", sampleCustomer: "Nom de client exemple", extraLarge: "Très grand", documentFont: "Police du document", documentFontSize: "Taille du document", baseCurrency: "Devise de base", enabledCurrencies: "Devises activées", activateCurrency: "Activer la devise",
    signInToContinue: "Connectez-vous pour continuer", workspaceAccountRequired: "L’espace de l’organisation nécessite un compte vérifié pour protéger vos données.", signIn: "Se connecter", signOut: "Se déconnecter",
    onboardingEyebrow: "Une étape pour commencer", onboardingTitle: "Créez l’espace sécurisé de votre organisation", onboardingDescription: "Nous créons l’organisation, l’adhésion du propriétaire et les modules de base dans un contexte isolé. Aucune donnée fictive n’est ajoutée.", organizationNamePlaceholder: "Nom de l’organisation", setupOrganization: "Configurer l’organisation", tenantIsolation: "Isolation multi-organisations", tenantIsolationDescription: "Chaque organisation possède son propre contexte d’accès.", enabledModules: "Modules activés", enabledModulesDescription: "Stocks, ventes, finance et plus encore.", governedAssistant: "Assistant gouverné", governedAssistantDescription: "Des réponses limitées au contexte de votre organisation.",
    moduleView: "Affichage des modules", fefo: "Premier expiré, premier sorti",
    inventory: "Stocks", sales: "Ventes", purchases: "Achats", finance: "Finance et comptabilité", hr: "Ressources humaines",
    navigation: "Navigation", dashboard: "Tableau de bord", workspace: "Espace de travail", modules: "Modules", settings: "Paramètres", reports: "Rapports", notifications: "Notifications", save: "Enregistrer", saved: "Paramètres enregistrés", cancel: "Annuler", language: "Langue", appearance: "Apparence", typography: "Typographie", currencies: "Devises", dateAndNumbers: "Dates et nombres", printing: "Impression et documents", security: "Sécurité", organization: "Organisation", branches: "Succursales", users: "Utilisateurs", light: "Clair", dark: "Sombre", system: "Système", active: "Actif", locked: "Verrouillé", explore: "Découvrir le module", upgrade: "Mettre à niveau", empty: "Aucune donnée à afficher", loading: "Chargement...", error: "Opération impossible", printPreview: "Aperçu avant impression", downloadCsv: "Exporter CSV", dateFormat: "Format de date", timeFormat: "Format d’heure", timeZone: "Fuseau horaire", firstDay: "Premier jour de la semaine", decimalSeparator: "Séparateur décimal", thousandsSeparator: "Séparateur des milliers", documentTemplate: "Modèle de document", paperSize: "Format du papier", header: "En-tête", footer: "Pied de page", signature: "Zone de signature", themeMode: "Mode de thème", accentColor: "Couleur d’accent", density: "Densité d’interface", radius: "Rayon des bordures", fontFamily: "Police", fontScale: "Taille du texte", sidebar: "Barre latérale", comfortable: "Confortable", compact: "Compact", expanded: "Développée", collapsed: "Réduite", companyName: "Nom de l’organisation", address: "Adresse", phone: "Téléphone", legalInfo: "Informations légales", moduleHub: "Centre des modules", premiumModule: "Module premium", noAccess: "Ce module n’est pas inclus dans votre abonnement actuel.", preferences: "Préférences", print: "Imprimer", document: "Document", status: "Statut", actions: "Actions", moduleViewMode: "Mode d’affichage des modules", classic: "Classique", nawaFlow: "Nawa Flow", businessFlowMap: "Carte des flux métier", openModule: "Ouvrir le module", restricted: "Restreint", available: "Disponible", flowOverview: "Vue d’ensemble du flux", commerceInventory: "Commerce et stocks", distributionFleet: "Distribution et flotte", manufacturingProduction: "Fabrication et production", financialAccounting: "Finance et comptabilité", humanResources: "Ressources humaines", internalFlow: "Flux interne", backToFlow: "Retour à la carte", flowLockedDescription: "Ce module n’est pas activé dans l’abonnement de l’organisation.", flowRestrictedDescription: "Vous ne disposez pas de l’autorisation requise pour afficher les détails de ce module.",
  },
en: {
    exchangeRates: "Exchange rates",
    numeralStyle: "Numeral Style", westernDigits: "Western digits 123", arabicIndicDigits: "Arabic-Indic digits ١٢٣", resetAppearance: "Reset to defaults", livePreview: "Live preview", totalSales: "Total sales", sampleCustomer: "Sample customer name", extraLarge: "Extra Large", documentFont: "Document font", documentFontSize: "Document font size", baseCurrency: "Base currency", enabledCurrencies: "Enabled currencies", activateCurrency: "Activate currency",
    signInToContinue: "Sign in to continue", workspaceAccountRequired: "The organization workspace requires a verified account to protect your data.", signIn: "Sign in", signOut: "Sign out",
    onboardingEyebrow: "One step to get started", onboardingTitle: "Create your secure organization workspace", onboardingDescription: "We create the organization, owner membership, and core modules in an isolated context. No mock products, invoices, or records are added.", organizationNamePlaceholder: "Organization name", setupOrganization: "Set up organization", tenantIsolation: "Multi-organization isolation", tenantIsolationDescription: "Each organization has an independent access context.", enabledModules: "Enabled modules", enabledModulesDescription: "Inventory, sales, finance, and more.", governedAssistant: "Governed assistant", governedAssistantDescription: "Answers stay within your organization context.",
    moduleView: "Module view", fefo: "First Expiry, First Out",
    inventory: "Inventory", sales: "Sales", purchases: "Purchases", finance: "Finance & accounting", hr: "Human resources",
    navigation: "Navigation", dashboard: "Dashboard", workspace: "Workspace", modules: "Modules", settings: "Settings", reports: "Reports", notifications: "Notifications", save: "Save changes", saved: "Settings saved", cancel: "Cancel", language: "Language", appearance: "Appearance", typography: "Typography", currencies: "Currencies", dateAndNumbers: "Dates & numbers", printing: "Print & documents", security: "Security", organization: "Organization", branches: "Branches", users: "Users", light: "Light", dark: "Dark", system: "System", active: "Active", locked: "Locked", explore: "Explore module", upgrade: "Upgrade subscription", empty: "No data to display", loading: "Loading...", error: "Operation could not be completed", printPreview: "Print preview", downloadCsv: "Export CSV", dateFormat: "Date format", timeFormat: "Time format", timeZone: "Time zone", firstDay: "First day of week", decimalSeparator: "Decimal separator", thousandsSeparator: "Thousands separator", documentTemplate: "Document template", paperSize: "Paper size", header: "Header", footer: "Footer", signature: "Signature area", themeMode: "Theme mode", accentColor: "Accent color", density: "Interface density", radius: "Border radius", fontFamily: "Font family", fontScale: "Font scale", sidebar: "Sidebar", comfortable: "Comfortable", compact: "Compact", expanded: "Expanded", collapsed: "Collapsed", companyName: "Organization name", address: "Address", phone: "Phone", legalInfo: "Legal information", moduleHub: "Module hub", premiumModule: "Premium module", noAccess: "This module is not included in your current subscription.", preferences: "Preferences", print: "Print", document: "Document", status: "Status", actions: "Actions", moduleViewMode: "Module View Mode", classic: "Classic", nawaFlow: "Nawa Flow", businessFlowMap: "Business flow map", openModule: "Open module", restricted: "Restricted", available: "Available", flowOverview: "Flow overview", commerceInventory: "Commerce & inventory", distributionFleet: "Distribution & fleet", manufacturingProduction: "Manufacturing & production", financialAccounting: "Finance & accounting", humanResources: "Human resources", internalFlow: "Internal flow", backToFlow: "Back to map", flowLockedDescription: "This module is not active in the organization subscription.", flowRestrictedDescription: "You do not have the permission required to view this module’s details.",
  },
} as const;

export type TranslationKey = keyof typeof messages.ar;
export const translations = messages;
export function getDirection(language: AppLanguage): "rtl" | "ltr" { return language === "ar" ? "rtl" : "ltr"; }
