export type AppLanguage = "ar" | "fr" | "en";

export const glossary = {
  ar: { inventory: "المخزون", sales: "المبيعات", purchases: "المشتريات", finance: "المالية والمحاسبة", hr: "الموارد البشرية", modules: "الوحدات", settings: "الإعدادات", subscriptions: "الاشتراكات" },
  fr: { inventory: "Stocks", sales: "Ventes", purchases: "Achats", finance: "Finance et comptabilité", hr: "Ressources humaines", modules: "Modules", settings: "Paramètres", subscriptions: "Abonnements" },
  en: { inventory: "Inventory", sales: "Sales", purchases: "Purchases", finance: "Finance & accounting", hr: "Human resources", modules: "Modules", settings: "Settings", subscriptions: "Subscriptions" },
} as const;

export const documentPreviewActionLabels = {
  ar: { download: "تنزيل ملف HTML", print: "طباعة أو حفظ PDF" },
  fr: { download: "Télécharger le fichier HTML", print: "Imprimer ou enregistrer en PDF" },
  en: { download: "Download HTML file", print: "Print or save as PDF" },
} as const;

const messages = {
  ar: {
    monday: "الاثنين", sunday: "الأحد", saturday: "السبت", space: "مسافة", barcode: "الباركود",
    exchangeHistoryTitle: "سجل أسعار الصرف", exchangeHistoryDescription: "سجل يدوي تاريخي؛ لا يغيّر أسعار المعاملات السابقة.", addExchangeRate: "إضافة سعر", quoteCurrency: "الاقتباس", exchangeRate: "السعر", filterExchangeRates: "تصفية السجل", effectiveDate: "تاريخ السريان", rateSource: "المصدر", noMatchingExchangeRates: "لا توجد أسعار صرف مطابقة", retry: "إعادة المحاولة", exportSpreadsheet: "تصدير جدول البيانات", downloadPdf: "تنزيل PDF", exchangeRateAdded: "تمت إضافة سعر الصرف", validRateRequired: "أدخل سعراً صحيحاً", refreshingExchangeRates: "جارٍ تحديث الأسعار…", exchangeRatesLoadError: "تعذر تحميل سجل أسعار الصرف.", clearFilters: "مسح المرشحات", currency: "العملة", from: "من", to: "إلى",
    exchangeRates: "أسعار الصرف", commerceSnapshot: "مؤشرات التجارة", openInvoices: "فواتير مفتوحة", openPurchaseOrders: "طلبات شراء قيد الاستلام", lowStockProducts: "أصناف منخفضة المخزون", issuedValue: "قيمة الفواتير الصادرة", recentDocuments: "أحدث المستندات", commerceAlerts: "تنبيهات التجارة", financialSummary: "ملخص مالي", currentMonth: "الشهر الحالي", revenue: "الإيرادات", expenses: "المصروفات", netProfit: "صافي الربح", totalSalesMetric: "إجمالي المبيعات", netRevenueMetric: "صافي الإيرادات", inventoryValueMetric: "قيمة المخزون", dueInvoicesMetric: "فواتير مستحقة", notificationCenter: "مركز الإشعارات", organizationAlerts: "تنبيهات المؤسسة", subscriptionModules: "الوحدات والاشتراك", organizationAccessStatus: "حالة وصول مؤسستك", noNotifications: "لا توجد إشعارات مسجلة.", enabled: "مفعلة", requestModuleUpgrade: "تواصل مع مسؤول الاشتراك لطلب ترقية الوحدة.", reportLoadError: "تعذر تحميل ملخص التقرير.", exportCsv: "تصدير CSV",
    issuedInvoices: "الفواتير الصادرة", productsCount: "عدد الأصناف", metric: "المؤشر", value: "القيمة", numeralStyle: "نمط الأرقام", westernDigits: "أرقام غربية 123", arabicIndicDigits: "أرقام عربية هندية ١٢٣", resetAppearance: "استعادة الإعدادات الافتراضية", livePreview: "معاينة مباشرة", totalSales: "إجمالي المبيعات", sampleCustomer: "اسم عميل تجريبي", extraLarge: "كبير جداً", documentFont: "خط المستند", documentFontSize: "حجم خط المستند", thermalPaper: "حراري", documentPreviewTitle: "مستند نواة", baseCurrency: "العملة الأساسية", enabledCurrencies: "العملات المفعلة", activateCurrency: "تفعيل العملة",
    signInToContinue: "سجّل الدخول للمتابعة", workspaceAccountRequired: "تتطلب مساحة المؤسسة حساباً موثقاً لحماية بياناتك.", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", aiAssistantTitle: "مساعد نواة الذكي", assistantScope: "حدود المساعد", evaluateAlerts: "تقييم التنبيهات", checkNow: "فحص الآن", assistantRequestError: "تعذر تنفيذ طلب المساعد الآن.", noCriticalAlerts: "لا توجد تنبيهات حرجة ضمن البيانات الحالية.", alertsNotified: "تم تقييم التنبيهات وإرسال إشعار لمالك المنصة.", alertsDeliveryDeferred: "تم تقييم التنبيهات، وتعذر تسليم الإشعار الخارجي مؤقتاً.", alertsEvaluationError: "تعذر تقييم التنبيهات الآن.", pageNotFound: "الصفحة غير موجودة", pageNotFoundDescription: "قد تكون الصفحة قد نُقلت أو حُذفت.", goHome: "العودة للرئيسية",
    onboardingEyebrow: "خطوة واحدة للبدء", onboardingTitle: "أنشئ مساحة مؤسستك الآمنة", onboardingDescription: "سننشئ المؤسسة وعضوية المالك والوحدات الأساسية في سياق معزول. لا نضيف منتجات أو فواتير أو سجلات افتراضية إلى بياناتك.", organizationNamePlaceholder: "اسم المؤسسة", setupOrganization: "إعداد المؤسسة", tenantIsolation: "عزل متعدد المؤسسات", tenantIsolationDescription: "لكل مؤسسة سياق وصول مستقل.", enabledModules: "وحدات مفعلة", enabledModulesDescription: "المخزون والمبيعات والمالية وغيرها.", governedAssistant: "مساعد محكوم", governedAssistantDescription: "إجابات ضمن بيانات مؤسستك فقط.",
    moduleView: "طريقة عرض الوحدات", fefo: "الأقرب انتهاءً أولاً", product: "المنتج", productName: "اسم المنتج", sku: "رمز المنتج", salePrice: "سعر البيع", createProduct: "إضافة منتج", productCreated: "تمت إضافة المنتج", warehouses: "المخازن", warehouse: "المخزن", warehouseCode: "رمز المخزن", warehouseName: "اسم المخزن", createWarehouse: "إضافة مخزن", batchManagement: "إدارة الدفعات", batchStatus: "حالة الدفعة", updateBatchStatus: "تحديث الحالة", adjustQuantity: "تسوية الكمية", quantityAdjusted: "تمت تسوية كمية الدفعة", blocked: "محجوبة", quarantined: "قيد الحجر", expired: "منتهية", inactive: "غير نشط", archived: "مؤرشف", batches: "الدفعات", salesInvoices: "فواتير المبيعات", purchaseOrders: "أوامر الشراء", createInvoice: "إنشاء فاتورة", createOrder: "إنشاء أمر شراء", issue: "إصدار", sendOrder: "إرسال", receive: "استلام", pay: "تسجيل سداد", quantity: "الكمية", unitCost: "تكلفة الوحدة", invoiceNumber: "رقم الفاتورة", orderNumber: "رقم الأمر", dueDate: "تاريخ الاستحقاق", expectedDate: "التاريخ المتوقع", draft: "مسودة", issued: "صادرة", sent: "مرسل", partial: "جزئي", paid: "مدفوعة", overdue: "متأخرة", cancelled: "ملغاة", returned: "مرتجعة", received: "مستلمة", documentCreated: "تم إنشاء المستند", documentIssued: "تم إصدار الفاتورة وصرف المخزون وفق FEFO", paymentRecorded: "تم تسجيل السداد", batchStatusUpdated: "تم تحديث حالة الدفعة", warehouseCreated: "تمت إضافة المخزن", createWarehouseFirst: "أضف مخزناً أولاً للبدء في إنشاء المستندات",
    navigation: "التنقل", dashboard: "لوحة التحكم", workspace: "مساحة العمل", modules: "الوحدات", settings: "الإعدادات", reports: "التقارير", notifications: "الإشعارات", save: "حفظ التغييرات", saved: "تم حفظ الإعدادات", cancel: "إلغاء", language: "اللغة", appearance: "المظهر", typography: "الخطوط", currencies: "العملات", dateAndNumbers: "التواريخ والأرقام", printing: "الطباعة والمستندات", security: "الأمان", organization: "المؤسسة", branches: "الفروع", users: "المستخدمون", light: "فاتح", dark: "داكن", system: "تلقائي", active: "مفعلة", locked: "مقفلة", explore: "استكشف الوحدة", upgrade: "ترقية الاشتراك", empty: "لا توجد بيانات لعرضها", loading: "جارٍ التحميل...", error: "تعذر إتمام العملية", printPreview: "معاينة الطباعة", downloadCsv: "تصدير CSV", dateFormat: "تنسيق التاريخ", timeFormat: "تنسيق الوقت", timeZone: "المنطقة الزمنية", firstDay: "أول يوم في الأسبوع", decimalSeparator: "الفاصل العشري", thousandsSeparator: "فاصل الآلاف", documentTemplate: "قالب المستند", paperSize: "مقاس الورق", header: "الترويسة", footer: "التذييل", signature: "منطقة التوقيع", themeMode: "نمط السمة", accentColor: "اللون المميز", density: "كثافة الواجهة", radius: "استدارة الحواف", fontFamily: "عائلة الخط", fontScale: "حجم الخط", sidebar: "الشريط الجانبي", comfortable: "مريح", compact: "مضغوط", expanded: "موسع", collapsed: "مطوي", companyName: "اسم المؤسسة", address: "العنوان", phone: "الهاتف", legalInfo: "البيانات القانونية", moduleHub: "مركز الوحدات", premiumModule: "وحدة احترافية", noAccess: "لا يتضمن اشتراك مؤسستك هذه الوحدة حالياً.", preferences: "التفضيلات", print: "طباعة", document: "مستند", status: "الحالة", actions: "الإجراءات", inventory: "المخزون", sales: "المبيعات", purchases: "المشتريات", finance: "المالية والمحاسبة", hr: "الموارد البشرية", moduleViewMode: "طريقة عرض الوحدات", classic: "تقليدي", nawaFlow: "Nawa Flow", businessFlowMap: "خريطة سير الأعمال", openModule: "فتح الوحدة", restricted: "مقيّدة", available: "متاحة", flowOverview: "نظرة عامة على التدفق", commerceInventory: "التجارة والمخزون", distributionFleet: "التوزيع والأسطول", manufacturingProduction: "التصنيع والإنتاج", financialAccounting: "المالية والمحاسبة", humanResources: "الموارد البشرية", internalFlow: "سير العمل الداخلي", backToFlow: "العودة إلى الخريطة", flowLockedDescription: "هذه الوحدة غير مفعلة ضمن اشتراك المؤسسة.", flowRestrictedDescription: "لا تملك الصلاحية المطلوبة لعرض تفاصيل هذه الوحدة.",
  },
  fr: {
    monday: "Lundi", sunday: "Dimanche", saturday: "Samedi", space: "Espace", barcode: "Code-barres",
    exchangeHistoryTitle: "Historique des taux", exchangeHistoryDescription: "Historique manuel; les transactions passées ne sont jamais modifiées.", addExchangeRate: "Ajouter un taux", quoteCurrency: "Contrepartie", exchangeRate: "Taux", filterExchangeRates: "Filtrer l’historique", effectiveDate: "Date d’effet", rateSource: "Source", noMatchingExchangeRates: "Aucun taux correspondant", retry: "Réessayer", exportSpreadsheet: "Exporter le tableur", downloadPdf: "Télécharger le PDF", exchangeRateAdded: "Taux de change ajouté", validRateRequired: "Saisissez un taux valide", refreshingExchangeRates: "Mise à jour des taux…", exchangeRatesLoadError: "Impossible de charger l’historique.", clearFilters: "Effacer les filtres", currency: "Devise", from: "Du", to: "Au",
    exchangeRates: "Taux de change", commerceSnapshot: "Indicateurs commerce", openInvoices: "Factures ouvertes", openPurchaseOrders: "Achats en attente", lowStockProducts: "Produits à faible stock", issuedValue: "Valeur facturée", recentDocuments: "Documents récents", commerceAlerts: "Alertes commerciales", financialSummary: "Résumé financier", currentMonth: "Mois en cours", revenue: "Revenus", expenses: "Dépenses", netProfit: "Bénéfice net", totalSalesMetric: "Total des ventes", netRevenueMetric: "Revenu net", inventoryValueMetric: "Valeur du stock", dueInvoicesMetric: "Factures dues", notificationCenter: "Centre de notifications", organizationAlerts: "Alertes de l’organisation", subscriptionModules: "Modules et abonnement", organizationAccessStatus: "État d’accès de l’organisation", noNotifications: "Aucune notification enregistrée.", enabled: "Activé", requestModuleUpgrade: "Contactez l’administrateur de l’abonnement pour demander une mise à niveau.", reportLoadError: "Impossible de charger le résumé du rapport.", exportCsv: "Exporter CSV",
    issuedInvoices: "Factures émises", productsCount: "Nombre de produits", metric: "Indicateur", value: "Valeur", numeralStyle: "Style des chiffres", westernDigits: "Chiffres occidentaux 123", arabicIndicDigits: "Chiffres arabo-indiens ١٢٣", resetAppearance: "Réinitialiser les préférences", livePreview: "Aperçu en direct", totalSales: "Total des ventes", sampleCustomer: "Nom de client exemple", extraLarge: "Très grand", documentFont: "Police du document", documentFontSize: "Taille du document", thermalPaper: "Thermique", documentPreviewTitle: "Document Nawa", baseCurrency: "Devise de base", enabledCurrencies: "Devises activées", activateCurrency: "Activer la devise",
    signInToContinue: "Connectez-vous pour continuer", workspaceAccountRequired: "L’espace de l’organisation nécessite un compte vérifié pour protéger vos données.", signIn: "Se connecter", signOut: "Se déconnecter", aiAssistantTitle: "Assistant Nawa intelligent", assistantScope: "Périmètre de l’assistant", evaluateAlerts: "Évaluer les alertes", checkNow: "Vérifier maintenant", assistantRequestError: "Impossible d’exécuter la demande de l’assistant.", noCriticalAlerts: "Aucune alerte critique dans les données actuelles.", alertsNotified: "Les alertes ont été évaluées et le propriétaire de la plateforme a été informé.", alertsDeliveryDeferred: "Les alertes ont été évaluées, mais la notification externe est temporairement différée.", alertsEvaluationError: "Impossible d’évaluer les alertes.", pageNotFound: "Page introuvable", pageNotFoundDescription: "La page a peut-être été déplacée ou supprimée.", goHome: "Retour à l’accueil",
    onboardingEyebrow: "Une étape pour commencer", onboardingTitle: "Créez l’espace sécurisé de votre organisation", onboardingDescription: "Nous créons l’organisation, l’adhésion du propriétaire et les modules de base dans un contexte isolé. Aucune donnée fictive n’est ajoutée.", organizationNamePlaceholder: "Nom de l’organisation", setupOrganization: "Configurer l’organisation", tenantIsolation: "Isolation multi-organisations", tenantIsolationDescription: "Chaque organisation possède son propre contexte d’accès.", enabledModules: "Modules activés", enabledModulesDescription: "Stocks, ventes, finance et plus encore.", governedAssistant: "Assistant gouverné", governedAssistantDescription: "Des réponses limitées au contexte de votre organisation.",
    moduleView: "Affichage des modules", fefo: "Premier expiré, premier sorti", product: "Produit", productName: "Nom du produit", sku: "Référence produit", salePrice: "Prix de vente", createProduct: "Ajouter un produit", productCreated: "Produit ajouté", warehouses: "Entrepôts", warehouse: "Entrepôt", warehouseCode: "Code entrepôt", warehouseName: "Nom de l’entrepôt", createWarehouse: "Ajouter un entrepôt", batchManagement: "Gestion des lots", batchStatus: "Statut du lot", updateBatchStatus: "Mettre à jour le statut", adjustQuantity: "Ajuster la quantité", quantityAdjusted: "Quantité du lot ajustée", blocked: "Bloqué", quarantined: "En quarantaine", expired: "Expiré", inactive: "Inactif", archived: "Archivé", batches: "Lots", salesInvoices: "Factures de vente", purchaseOrders: "Bons de commande", createInvoice: "Créer une facture", createOrder: "Créer une commande", issue: "Émettre", sendOrder: "Envoyer", receive: "Réception", pay: "Enregistrer le règlement", quantity: "Quantité", unitCost: "Coût unitaire", invoiceNumber: "Numéro de facture", orderNumber: "Numéro de commande", dueDate: "Date d’échéance", expectedDate: "Date prévue", draft: "Brouillon", issued: "Émise", sent: "Envoyée", partial: "Partiel", paid: "Payée", overdue: "En retard", cancelled: "Annulée", returned: "Retournée", received: "Reçue", documentCreated: "Document créé", documentIssued: "Facture émise et stock sorti selon FEFO", paymentRecorded: "Règlement enregistré", batchStatusUpdated: "Statut du lot mis à jour", warehouseCreated: "Entrepôt ajouté", createWarehouseFirst: "Ajoutez d’abord un entrepôt pour créer des documents",
    inventory: "Stocks", sales: "Ventes", purchases: "Achats", finance: "Finance et comptabilité", hr: "Ressources humaines",
    navigation: "Navigation", dashboard: "Tableau de bord", workspace: "Espace de travail", modules: "Modules", settings: "Paramètres", reports: "Rapports", notifications: "Notifications", save: "Enregistrer", saved: "Paramètres enregistrés", cancel: "Annuler", language: "Langue", appearance: "Apparence", typography: "Typographie", currencies: "Devises", dateAndNumbers: "Dates et nombres", printing: "Impression et documents", security: "Sécurité", organization: "Organisation", branches: "Succursales", users: "Utilisateurs", light: "Clair", dark: "Sombre", system: "Système", active: "Actif", locked: "Verrouillé", explore: "Découvrir le module", upgrade: "Mettre à niveau", empty: "Aucune donnée à afficher", loading: "Chargement...", error: "Opération impossible", printPreview: "Aperçu avant impression", downloadCsv: "Exporter CSV", dateFormat: "Format de date", timeFormat: "Format d’heure", timeZone: "Fuseau horaire", firstDay: "Premier jour de la semaine", decimalSeparator: "Séparateur décimal", thousandsSeparator: "Séparateur des milliers", documentTemplate: "Modèle de document", paperSize: "Format du papier", header: "En-tête", footer: "Pied de page", signature: "Zone de signature", themeMode: "Mode de thème", accentColor: "Couleur d’accent", density: "Densité d’interface", radius: "Rayon des bordures", fontFamily: "Police", fontScale: "Taille du texte", sidebar: "Barre latérale", comfortable: "Confortable", compact: "Compact", expanded: "Développée", collapsed: "Réduite", companyName: "Nom de l’organisation", address: "Adresse", phone: "Téléphone", legalInfo: "Informations légales", moduleHub: "Centre des modules", premiumModule: "Module premium", noAccess: "Ce module n’est pas inclus dans votre abonnement actuel.", preferences: "Préférences", print: "Imprimer", document: "Document", status: "Statut", actions: "Actions", moduleViewMode: "Mode d’affichage des modules", classic: "Classique", nawaFlow: "Nawa Flow", businessFlowMap: "Carte des flux métier", openModule: "Ouvrir le module", restricted: "Restreint", available: "Disponible", flowOverview: "Vue d’ensemble du flux", commerceInventory: "Commerce et stocks", distributionFleet: "Distribution et flotte", manufacturingProduction: "Fabrication et production", financialAccounting: "Finance et comptabilité", humanResources: "Ressources humaines", internalFlow: "Flux interne", backToFlow: "Retour à la carte", flowLockedDescription: "Ce module n’est pas activé dans l’abonnement de l’organisation.", flowRestrictedDescription: "Vous ne disposez pas de l’autorisation requise pour afficher les détails de ce module.",
  },
  en: {
    monday: "Monday", sunday: "Sunday", saturday: "Saturday", space: "Space", barcode: "Barcode",
    exchangeHistoryTitle: "Exchange rate history", exchangeHistoryDescription: "Manual historical ledger; it never changes past transaction rates.", addExchangeRate: "Add rate", quoteCurrency: "Quote", exchangeRate: "Rate", filterExchangeRates: "Filter history", effectiveDate: "Effective date", rateSource: "Source", noMatchingExchangeRates: "No matching exchange rates", retry: "Retry", exportSpreadsheet: "Export spreadsheet", downloadPdf: "Download PDF", exchangeRateAdded: "Exchange rate added", validRateRequired: "Enter a valid rate", refreshingExchangeRates: "Refreshing rates…", exchangeRatesLoadError: "Could not load exchange-rate history.", clearFilters: "Clear filters", currency: "Currency", from: "From", to: "To",
    exchangeRates: "Exchange rates", commerceSnapshot: "Commerce indicators", openInvoices: "Open invoices", openPurchaseOrders: "Purchase orders awaiting receipt", lowStockProducts: "Low-stock products", issuedValue: "Issued invoice value", recentDocuments: "Recent documents", commerceAlerts: "Commerce alerts", financialSummary: "Financial summary", currentMonth: "Current month", revenue: "Revenue", expenses: "Expenses", netProfit: "Net profit", totalSalesMetric: "Total sales", netRevenueMetric: "Net revenue", inventoryValueMetric: "Inventory value", dueInvoicesMetric: "Due invoices", notificationCenter: "Notification center", organizationAlerts: "Organization alerts", subscriptionModules: "Modules & subscription", organizationAccessStatus: "Your organization access status", noNotifications: "No notifications recorded.", enabled: "Enabled", requestModuleUpgrade: "Contact the subscription administrator to request a module upgrade.", reportLoadError: "Could not load the report summary.", exportCsv: "Export CSV",
    issuedInvoices: "Issued invoices", productsCount: "Product count", metric: "Metric", value: "Value", numeralStyle: "Numeral Style", westernDigits: "Western digits 123", arabicIndicDigits: "Arabic-Indic digits ١٢٣", resetAppearance: "Reset to defaults", livePreview: "Live preview", totalSales: "Total sales", sampleCustomer: "Sample customer name", extraLarge: "Extra Large", documentFont: "Document font", documentFontSize: "Document font size", thermalPaper: "Thermal", documentPreviewTitle: "Nawa document", baseCurrency: "Base currency", enabledCurrencies: "Enabled currencies", activateCurrency: "Activate currency",
    signInToContinue: "Sign in to continue", workspaceAccountRequired: "The organization workspace requires a verified account to protect your data.", signIn: "Sign in", signOut: "Sign out", aiAssistantTitle: "Nawa smart assistant", assistantScope: "Assistant boundaries", evaluateAlerts: "Evaluate alerts", checkNow: "Check now", assistantRequestError: "Could not process the assistant request.", noCriticalAlerts: "There are no critical alerts in the current data.", alertsNotified: "Alerts were evaluated and the platform owner was notified.", alertsDeliveryDeferred: "Alerts were evaluated, but external delivery is temporarily deferred.", alertsEvaluationError: "Could not evaluate alerts.", pageNotFound: "Page not found", pageNotFoundDescription: "The page may have been moved or deleted.", goHome: "Go home",
    onboardingEyebrow: "One step to get started", onboardingTitle: "Create your secure organization workspace", onboardingDescription: "We create the organization, owner membership, and core modules in an isolated context. No mock products, invoices, or records are added.", organizationNamePlaceholder: "Organization name", setupOrganization: "Set up organization", tenantIsolation: "Multi-organization isolation", tenantIsolationDescription: "Each organization has an independent access context.", enabledModules: "Enabled modules", enabledModulesDescription: "Inventory, sales, finance, and more.", governedAssistant: "Governed assistant", governedAssistantDescription: "Answers stay within your organization context.",
    moduleView: "Module view", fefo: "First Expiry, First Out", product: "Product", productName: "Product name", sku: "Product SKU", salePrice: "Sale price", createProduct: "Add product", productCreated: "Product added", warehouses: "Warehouses", warehouse: "Warehouse", warehouseCode: "Warehouse code", warehouseName: "Warehouse name", createWarehouse: "Add warehouse", batchManagement: "Batch management", batchStatus: "Batch status", updateBatchStatus: "Update status", adjustQuantity: "Adjust quantity", quantityAdjusted: "Batch quantity adjusted", blocked: "Blocked", quarantined: "Quarantined", expired: "Expired", inactive: "Inactive", archived: "Archived", batches: "Batches", salesInvoices: "Sales invoices", purchaseOrders: "Purchase orders", createInvoice: "Create invoice", createOrder: "Create order", issue: "Issue", sendOrder: "Send", receive: "Receive", pay: "Record payment", quantity: "Quantity", unitCost: "Unit cost", invoiceNumber: "Invoice number", orderNumber: "Order number", dueDate: "Due date", expectedDate: "Expected date", draft: "Draft", issued: "Issued", sent: "Sent", partial: "Partial", paid: "Paid", overdue: "Overdue", cancelled: "Cancelled", returned: "Returned", received: "Received", documentCreated: "Document created", documentIssued: "Invoice issued and stock allocated by FEFO", paymentRecorded: "Payment recorded", batchStatusUpdated: "Batch status updated", warehouseCreated: "Warehouse added", createWarehouseFirst: "Add a warehouse before creating documents",
    inventory: "Inventory", sales: "Sales", purchases: "Purchases", finance: "Finance & accounting", hr: "Human resources",
    navigation: "Navigation", dashboard: "Dashboard", workspace: "Workspace", modules: "Modules", settings: "Settings", reports: "Reports", notifications: "Notifications", save: "Save changes", saved: "Settings saved", cancel: "Cancel", language: "Language", appearance: "Appearance", typography: "Typography", currencies: "Currencies", dateAndNumbers: "Dates & numbers", printing: "Print & documents", security: "Security", organization: "Organization", branches: "Branches", users: "Users", light: "Light", dark: "Dark", system: "System", active: "Active", locked: "Locked", explore: "Explore module", upgrade: "Upgrade subscription", empty: "No data to display", loading: "Loading...", error: "Operation could not be completed", printPreview: "Print preview", downloadCsv: "Export CSV", dateFormat: "Date format", timeFormat: "Time format", timeZone: "Time zone", firstDay: "First day of week", decimalSeparator: "Decimal separator", thousandsSeparator: "Thousands separator", documentTemplate: "Document template", paperSize: "Paper size", header: "Header", footer: "Footer", signature: "Signature area", themeMode: "Theme mode", accentColor: "Accent color", density: "Interface density", radius: "Border radius", fontFamily: "Font family", fontScale: "Font scale", sidebar: "Sidebar", comfortable: "Comfortable", compact: "Compact", expanded: "Expanded", collapsed: "Collapsed", companyName: "Organization name", address: "Address", phone: "Phone", legalInfo: "Legal information", moduleHub: "Module hub", premiumModule: "Premium module", noAccess: "This module is not included in your current subscription.", preferences: "Preferences", print: "Print", document: "Document", status: "Status", actions: "Actions", moduleViewMode: "Module View Mode", classic: "Classic", nawaFlow: "Nawa Flow", businessFlowMap: "Business flow map", openModule: "Open module", restricted: "Restricted", available: "Available", flowOverview: "Flow overview", commerceInventory: "Commerce & inventory", distributionFleet: "Distribution & fleet", manufacturingProduction: "Manufacturing & production", financialAccounting: "Finance & accounting", humanResources: "Human resources", internalFlow: "Internal flow", backToFlow: "Back to map", flowLockedDescription: "This module is not active in the organization subscription.", flowRestrictedDescription: "You do not have the permission required to view this module’s details.",
  },
} as const;

export type TranslationKey = keyof typeof messages.ar;
export const translations = messages;
export function getDirection(language: AppLanguage): "rtl" | "ltr" { return language === "ar" ? "rtl" : "ltr"; }
