import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Banknote, CircleDollarSign, PackageCheck, ReceiptText, RotateCcw, WalletCards } from "lucide-react";
import React, { useMemo, useState } from "react";
import { toast } from "sonner";

type Stop = { id: number; customerId: number; customerName: string; deliveryStatus: string };
type InventoryLine = { batchId: number; productId: number; productName: string; sku: string; unit: string; lotNumber: string; expiryDate: Date | null; loadedQuantity: unknown; remainingQuantity: unknown };
type Labels = { delivery: string; partial: string; failed: string; collect: string; return: string; expense: string; closing: string; quantity: string; amount: string; reason: string; save: string; actualCash: string; currency: string; receipt: string; inventory: string; noInventory: string; operationDone: string; operationFailed: string; paymentMethod: string; condition: string };
const key = () => crypto.randomUUID();

export function DriverDailyOperations({ routeId, vehicleId, stop, inventory, labels, onSuccess }: { routeId: number; vehicleId?: number | null; stop?: Stop; inventory: InventoryLine[]; labels: Labels; onSuccess: () => void }) {
  const [batchId, setBatchId] = useState<string>(""); const [quantity, setQuantity] = useState("1"); const [amount, setAmount] = useState(""); const [reason, setReason] = useState(""); const [actualCash, setActualCash] = useState(""); const [condition, setCondition] = useState<"resalable" | "damaged" | "quarantined">("resalable");
  const batch = useMemo(() => inventory.find(item => item.batchId === Number(batchId)), [inventory, batchId]);
  const complete = () => { onSuccess(); toast.success(labels.operationDone); };
  const failed = () => toast.error(labels.operationFailed);
  const delivery = trpc.erp.distribution.deliveries.record.useMutation({ onSuccess: complete, onError: failed });
  const collection = trpc.erp.distribution.collections.record.useMutation({ onSuccess: complete, onError: failed });
  const returning = trpc.erp.distribution.returns.record.useMutation({ onSuccess: complete, onError: failed });
  const expense = trpc.erp.distribution.expenses.create.useMutation({ onSuccess: complete, onError: failed });
  const closing = trpc.erp.distribution.closings.submit.useMutation({ onSuccess: complete, onError: failed });
  const positiveQuantity = Number(quantity);
  const selectInventory = <div className="space-y-2"><Label>{labels.inventory}</Label><Select value={batchId} onValueChange={setBatchId}><SelectTrigger><SelectValue placeholder={labels.inventory} /></SelectTrigger><SelectContent>{inventory.map(item => <SelectItem key={item.batchId} value={String(item.batchId)}>{item.productName} · {item.lotNumber} · {String(item.remainingQuantity)}</SelectItem>)}</SelectContent></Select></div>;
  if (!inventory.length) return <Card><CardContent className="p-4 text-sm text-muted-foreground">{labels.noInventory}</CardContent></Card>;
  return <section className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><PackageCheck className="h-5 w-5 text-primary" />{labels.delivery}</CardTitle></CardHeader><CardContent className="space-y-3">{selectInventory}<div className="grid grid-cols-2 gap-2"><div><Label>{labels.quantity}</Label><Input type="number" min="0" value={quantity} onChange={event => setQuantity(event.target.value)} /></div><div><Label>{labels.reason}</Label><Input value={reason} onChange={event => setReason(event.target.value)} /></div></div><div className="flex flex-wrap gap-2"><Button size="sm" disabled={!stop || !batch || !(positiveQuantity > 0) || delivery.isPending} onClick={() => delivery.mutate({ routeId, stopId: stop!.id, customerId: stop!.customerId, idempotencyKey: key(), notes: reason || undefined, items: [{ productId: batch!.productId, vehicleBatchId: batch!.batchId, expectedQuantity: positiveQuantity, deliveredQuantity: positiveQuantity, unit: batch!.unit }] })}>{labels.delivery}</Button><Button size="sm" variant="outline" disabled={!stop || !batch || !(positiveQuantity >= 0) || delivery.isPending} onClick={() => delivery.mutate({ routeId, stopId: stop!.id, customerId: stop!.customerId, idempotencyKey: key(), notes: reason || labels.partial, items: [{ productId: batch!.productId, vehicleBatchId: batch!.batchId, expectedQuantity: Number(batch!.remainingQuantity), deliveredQuantity: positiveQuantity, rejectedQuantity: Math.max(0, Number(batch!.remainingQuantity) - positiveQuantity), unit: batch!.unit }] })}>{labels.partial}</Button><Button size="sm" variant="destructive" disabled={!stop || !batch || delivery.isPending || !reason.trim()} onClick={() => delivery.mutate({ routeId, stopId: stop!.id, customerId: stop!.customerId, idempotencyKey: key(), notes: reason, items: [{ productId: batch!.productId, vehicleBatchId: batch!.batchId, expectedQuantity: Number(batch!.remainingQuantity), deliveredQuantity: 0, rejectedQuantity: Number(batch!.remainingQuantity), unit: batch!.unit }] })}>{labels.failed}</Button></div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><WalletCards className="h-5 w-5 text-primary" />{labels.collect}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-2 gap-2"><div><Label>{labels.amount}</Label><Input type="number" min="0" value={amount} onChange={event => setAmount(event.target.value)} /></div><div><Label>{labels.paymentMethod}</Label><Select defaultValue="cash"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="cash">Cash</SelectItem><SelectItem value="card">Card</SelectItem><SelectItem value="transfer">Transfer</SelectItem></SelectContent></Select></div></div><Button size="sm" disabled={!stop || !(Number(amount) > 0) || collection.isPending} onClick={() => collection.mutate({ routeId, customerId: stop!.customerId, collectionType: "previous_debt", amount: Number(amount), currencyCode: "DZD", paymentMethod: "cash", idempotencyKey: key() })}>{labels.collect}</Button></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><RotateCcw className="h-5 w-5 text-primary" />{labels.return}</CardTitle></CardHeader><CardContent className="space-y-3">{selectInventory}<div className="grid grid-cols-2 gap-2"><div><Label>{labels.quantity}</Label><Input type="number" min="0" value={quantity} onChange={event => setQuantity(event.target.value)} /></div><div><Label>{labels.condition}</Label><Select value={condition} onValueChange={value => setCondition(value as typeof condition)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="resalable">Resalable</SelectItem><SelectItem value="damaged">Damaged</SelectItem><SelectItem value="quarantined">Quarantine</SelectItem></SelectContent></Select></div></div><Button size="sm" disabled={!stop || !batch || !(positiveQuantity > 0) || returning.isPending} onClick={() => returning.mutate({ routeId, customerId: stop!.customerId, productId: batch!.productId, vehicleBatchId: batch!.batchId, quantity: positiveQuantity, unit: batch!.unit, reason: reason || undefined, condition, idempotencyKey: key() })}>{labels.return}</Button></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ReceiptText className="h-5 w-5 text-primary" />{labels.expense}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-2 gap-2"><div><Label>{labels.amount}</Label><Input type="number" min="0" value={amount} onChange={event => setAmount(event.target.value)} /></div><div><Label>{labels.reason}</Label><Input value={reason} onChange={event => setReason(event.target.value)} /></div></div><Button size="sm" disabled={!(Number(amount) > 0) || expense.isPending} onClick={() => expense.mutate({ routeId, vehicleId: vehicleId ?? undefined, category: "minor", amount: Number(amount), currencyCode: "DZD", notes: reason || undefined })}>{labels.expense}</Button></CardContent></Card>
  <Card className="md:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Banknote className="h-5 w-5 text-primary" />{labels.closing}</CardTitle></CardHeader><CardContent className="flex flex-wrap items-end gap-3"><div><Label>{labels.actualCash}</Label><Input className="w-44" type="number" min="0" value={actualCash} onChange={event => setActualCash(event.target.value)} /></div><Button disabled={!(Number(actualCash) >= 0) || closing.isPending} onClick={() => closing.mutate({ routeId, actualCash: Number(actualCash) })}>{labels.closing}</Button></CardContent></Card></section>;
}
