import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { GitBranchPlus, Search } from "lucide-react";
import React, { useState } from "react";

const labels = { ar: { title: "شجرة تتبّع الدفعة", description: "أدخل رقم الدفعة الداخلي لتتبّع الخام إلى النهائي أو العكس.", placeholder: "معرّف الدفعة", search: "تتبّع", raw: "دفعة خام", order: "أمر الإنتاج", finished: "دفعة نهائية", none: "لم تُسجل علاقة إنتاج لهذه الدفعة بعد.", error: "تعذر تحميل تتبّع الدفعة." }, fr: { title: "Généalogie du lot", description: "Saisissez l’identifiant interne du lot pour retracer le flux dans les deux sens.", placeholder: "Identifiant du lot", search: "Tracer", raw: "Lot matière", order: "Ordre de production", finished: "Lot fini", none: "Aucun lien de production n’est encore enregistré pour ce lot.", error: "Impossible de charger la traçabilité du lot." }, en: { title: "Batch genealogy", description: "Enter an internal batch ID to trace raw-to-finished or finished-to-raw flow.", placeholder: "Batch ID", search: "Trace", raw: "Raw batch", order: "Production order", finished: "Finished batch", none: "No production relation is recorded for this batch yet.", error: "Unable to load batch genealogy." } } as const;

export function ManufacturingBatchGenealogy() {
  const { language, direction } = useLanguage(); const copy = labels[language];
  const [value, setValue] = useState(""); const [batchId, setBatchId] = useState<number | null>(null);
  const genealogy = trpc.erp.manufacturing.batchGenealogy.useQuery({ batchId: batchId ?? 1 }, { enabled: Boolean(batchId) });
  const run = () => { const parsed = Number(value); if (Number.isInteger(parsed) && parsed > 0) setBatchId(parsed); };
  const hasRelations = Boolean(genealogy.data?.usedAsRawMaterial.length || genealogy.data?.finishedFrom.length);
  return <Card dir={direction} className="mt-5"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><GitBranchPlus className="h-5 w-5 text-primary" />{copy.title}</CardTitle><p className="text-sm text-muted-foreground">{copy.description}</p></CardHeader><CardContent><div className="flex flex-wrap gap-2"><Input className="max-w-xs" inputMode="numeric" placeholder={copy.placeholder} value={value} onChange={event => setValue(event.target.value)} onKeyDown={event => event.key === "Enter" && run()} /><Button variant="outline" onClick={run}><Search className="me-2 h-4 w-4" />{copy.search}</Button></div>{genealogy.isError ? <p className="mt-4 text-sm text-destructive">{copy.error}</p> : genealogy.data ? <div className="mt-5 grid gap-3 lg:grid-cols-2"><div className="rounded-xl border p-4"><p className="font-medium">{copy.raw} #{genealogy.data.batch.id}</p>{genealogy.data.usedAsRawMaterial.map(item => <div key={item.order.id} className="mt-3 rounded-lg bg-muted/50 p-3 text-sm"><p>{copy.order}: {item.order.orderNumber}</p>{item.outputs.map(output => <p key={output.output.id} className="mt-1 text-muted-foreground">{copy.finished}: #{output.batch?.id ?? "—"}</p>)}</div>)}</div><div className="rounded-xl border p-4"><p className="font-medium">{copy.finished} #{genealogy.data.batch.id}</p>{genealogy.data.finishedFrom.map(item => <div key={item.order.id} className="mt-3 rounded-lg bg-muted/50 p-3 text-sm"><p>{copy.order}: {item.order.orderNumber}</p>{item.rawMaterials.map(raw => <p key={raw.reservation.id} className="mt-1 text-muted-foreground">{copy.raw}: #{raw.batch?.id ?? "—"}</p>)}</div>)}</div>{!hasRelations ? <p className="text-sm text-muted-foreground lg:col-span-2">{copy.none}</p> : null}</div> : null}</CardContent></Card>;
}
